from django.urls import path

from .application_views import (
    AdminPlanApplicationCloseView,
    AdminPlanApplicationContactView,
    AdminPlanApplicationDetailView,
    AdminPlanApplicationListView,
    PlanApplicationCancelView,
    PlanApplicationDetailView,
    PlanApplicationListCreateView,
)
from .subscription_views import (
    AdminGrantTrialView,
    AdminOpenSubscriptionView,
    AdminSubscriptionChangeCancelView,
    AdminSubscriptionChangeCreateView,
    AdminSubscriptionChangeDetailView,
    AdminSubscriptionChangeListView,
    AdminSubscriptionChangePreviewView,
    AdminSubscriptionDetailView,
    AdminSubscriptionListView,
    AdminTerminateSubscriptionView,
    CurrentSubscriptionView,
    UserSubscriptionChangeListView,
)
from .views import (
    AdminPlanArchiveView,
    AdminPlanCopyView,
    AdminPlanDetailView,
    AdminPlanLimitDefinitionListView,
    AdminPlanListView,
    AdminPlanOfflineView,
    AdminPlanOnlineView,
    AdminPlanVersionDetailView,
    AdminPlanVersionListView,
    AdminPlanVersionPublishView,
    AdminPlanVersionRetireView,
    PublicPlanDetailView,
    PublicPlanListView,
)

urlpatterns = [
    path("admin/plans", AdminPlanListView.as_view(), name="admin-plan-list"),
    path(
        "admin/plan-limit-definitions",
        AdminPlanLimitDefinitionListView.as_view(),
        name="admin-plan-limit-definitions",
    ),
    path("admin/plans/<uuid:plan_id>", AdminPlanDetailView.as_view(), name="admin-plan-detail"),
    path("admin/plans/<uuid:plan_id>/copy", AdminPlanCopyView.as_view(), name="admin-plan-copy"),
    path(
        "admin/plans/<uuid:plan_id>/online", AdminPlanOnlineView.as_view(), name="admin-plan-online"
    ),
    path(
        "admin/plans/<uuid:plan_id>/offline",
        AdminPlanOfflineView.as_view(),
        name="admin-plan-offline",
    ),
    path(
        "admin/plans/<uuid:plan_id>/archive",
        AdminPlanArchiveView.as_view(),
        name="admin-plan-archive",
    ),
    path(
        "admin/plans/<uuid:plan_id>/versions",
        AdminPlanVersionListView.as_view(),
        name="admin-plan-version-list",
    ),
    path(
        "admin/plan-versions/<uuid:version_id>",
        AdminPlanVersionDetailView.as_view(),
        name="admin-plan-version-detail",
    ),
    path(
        "admin/plan-versions/<uuid:version_id>/publish",
        AdminPlanVersionPublishView.as_view(),
        name="admin-plan-version-publish",
    ),
    path(
        "admin/plan-versions/<uuid:version_id>/retire",
        AdminPlanVersionRetireView.as_view(),
        name="admin-plan-version-retire",
    ),
    path(
        "plan-applications",
        PlanApplicationListCreateView.as_view(),
        name="plan-application-list-create",
    ),
    path(
        "plan-applications/<uuid:application_id>",
        PlanApplicationDetailView.as_view(),
        name="plan-application-detail",
    ),
    path(
        "plan-applications/<uuid:application_id>/cancel",
        PlanApplicationCancelView.as_view(),
        name="plan-application-cancel",
    ),
    path(
        "admin/plan-applications",
        AdminPlanApplicationListView.as_view(),
        name="admin-plan-application-list",
    ),
    path(
        "admin/plan-applications/<uuid:application_id>",
        AdminPlanApplicationDetailView.as_view(),
        name="admin-plan-application-detail",
    ),
    path(
        "admin/plan-applications/<uuid:application_id>/contact",
        AdminPlanApplicationContactView.as_view(),
        name="admin-plan-application-contact",
    ),
    path(
        "admin/plan-applications/<uuid:application_id>/close",
        AdminPlanApplicationCloseView.as_view(),
        name="admin-plan-application-close",
    ),
    path("subscription", CurrentSubscriptionView.as_view(), name="current-subscription"),
    path(
        "admin/subscriptions",
        AdminSubscriptionListView.as_view(),
        name="admin-subscription-list",
    ),
    path(
        "admin/subscriptions/<uuid:subscription_id>",
        AdminSubscriptionDetailView.as_view(),
        name="admin-subscription-detail",
    ),
    path(
        "admin/plan-applications/<uuid:application_id>/activate",
        AdminOpenSubscriptionView.as_view(),
        name="admin-plan-application-activate",
    ),
    path(
        "admin/users/<uuid:user_id>/subscriptions/trial",
        AdminGrantTrialView.as_view(),
        name="admin-grant-trial",
    ),
    path(
        "admin/subscriptions/<uuid:subscription_id>/terminate",
        AdminTerminateSubscriptionView.as_view(),
        name="admin-subscription-terminate",
    ),
    path(
        "admin/subscriptions/<uuid:subscription_id>/change/preview",
        AdminSubscriptionChangePreviewView.as_view(),
        name="admin-subscription-change-preview",
    ),
    path(
        "admin/subscriptions/<uuid:subscription_id>/change",
        AdminSubscriptionChangeCreateView.as_view(),
        name="admin-subscription-change-create",
    ),
    path(
        "admin/subscription-changes",
        AdminSubscriptionChangeListView.as_view(),
        name="admin-subscription-change-list",
    ),
    path(
        "admin/subscription-changes/<uuid:change_id>",
        AdminSubscriptionChangeDetailView.as_view(),
        name="admin-subscription-change-detail",
    ),
    path(
        "admin/subscription-changes/<uuid:change_id>/cancel",
        AdminSubscriptionChangeCancelView.as_view(),
        name="admin-subscription-change-cancel",
    ),
    path(
        "subscription/changes",
        UserSubscriptionChangeListView.as_view(),
        name="subscription-change-list",
    ),
    path("plans", PublicPlanListView.as_view(), name="public-plan-list"),
    path("plans/<uuid:plan_id>", PublicPlanDetailView.as_view(), name="public-plan-detail"),
]
