# Generated by Django 5.2.16 on 2026-08-02 06:07

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0007_subscription_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_type', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('subscription', '订阅'), ('account', '账号'), ('account_cycle', '账号周期')], max_length=24)),
                ('unit', models.CharField(max_length=32)),
                ('batch_key', models.UUIDField(default=uuid.uuid4)),
                ('entitlement_amount', models.BigIntegerField()),
                ('available', models.BigIntegerField(default=0)),
                ('frozen', models.BigIntegerField(default=0)),
                ('cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_ends_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_sequence', models.BigIntegerField(default=0)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_accounts', to='plans.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quota_accounts',
                'ordering': ('quota_type', 'cycle_started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuotaHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_type', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=64)),
                ('business_id', models.UUIDField()),
                ('requested_amount', models.BigIntegerField()),
                ('consumed_amount', models.BigIntegerField(default=0)),
                ('released_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', '待结算'), ('partially_settled', '部分结算'), ('settled', '已结算')], default='open', max_length=24)),
                ('freeze_idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('freeze_idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('freeze_idempotency_scope_digest', models.CharField(max_length=64)),
                ('freeze_request_digest', models.CharField(max_length=64)),
                ('version', models.BigIntegerField(default=1)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='quotas.quotaaccount')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_holds', to='plans.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quota_holds',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuotaLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_type', models.CharField(max_length=100)),
                ('sequence', models.BigIntegerField()),
                ('action', models.CharField(choices=[('initialize', '初始化'), ('freeze', '冻结'), ('consume', '扣除'), ('release', '返还'), ('grant', '赠送'), ('compensate', '补偿'), ('manual_deduct', '人工扣减')], max_length=24)),
                ('available_before', models.BigIntegerField()),
                ('available_delta', models.BigIntegerField()),
                ('available_after', models.BigIntegerField()),
                ('frozen_before', models.BigIntegerField()),
                ('frozen_delta', models.BigIntegerField()),
                ('frozen_after', models.BigIntegerField()),
                ('account_version_before', models.BigIntegerField()),
                ('account_version_after', models.BigIntegerField()),
                ('business_type', models.CharField(max_length=64)),
                ('business_id', models.UUIDField(blank=True, null=True)),
                ('safe_reason', models.CharField(blank=True, max_length=500)),
                ('request_id', models.UUIDField()),
                ('idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('idempotency_scope_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='quotas.quotaaccount')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acted_quota_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='quotas.quotahold')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_ledger_entries', to='plans.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quota_ledger_entries',
                'ordering': ('account_id', 'sequence'),
            },
        ),
        migrations.AddField(
            model_name='quotaaccount',
            name='last_ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_accounts', to='quotas.quotaledgerentry'),
        ),
        migrations.AddIndex(
            model_name='quotahold',
            index=models.Index(fields=['user', 'status', 'created_at'], name='quota_hold_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quotahold',
            index=models.Index(fields=['account', 'status'], name='quota_hold_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.UniqueConstraint(fields=('account', 'business_type', 'business_id'), name='quota_hold_unique_business_target'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='quota_hold_requested_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_amount__gte', 0)), name='quota_hold_consumed_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.CheckConstraint(condition=models.Q(('released_amount__gte', 0)), name='quota_hold_released_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_amount__lte', django.db.models.expressions.CombinedExpression(models.F('requested_amount'), '-', models.F('released_amount')))), name='quota_hold_total_lte_requested'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='quota_hold_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumed_amount', 0), ('released_amount', 0), ('settled_at__isnull', True), ('status', 'open')), models.Q(('settled_at__isnull', True), ('status', 'partially_settled'), models.Q(('consumed_amount__gt', 0), ('released_amount__gt', 0), _connector='OR'), ('consumed_amount__lt', django.db.models.expressions.CombinedExpression(models.F('requested_amount'), '-', models.F('released_amount')))), models.Q(('settled_at__isnull', False), ('status', 'settled'), ('consumed_amount', django.db.models.expressions.CombinedExpression(models.F('requested_amount'), '-', models.F('released_amount')))), _connector='OR'), name='quota_hold_status_amounts'),
        ),
        migrations.AddIndex(
            model_name='quotaledgerentry',
            index=models.Index(fields=['user', 'quota_type', 'created_at'], name='quota_ledger_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaledgerentry',
            index=models.Index(fields=['subscription', 'created_at'], name='quota_ledger_subscription_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaledgerentry',
            index=models.Index(fields=['hold', 'sequence'], name='quota_ledger_hold_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.UniqueConstraint(fields=('account', 'sequence'), name='quota_ledger_account_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='quota_ledger_sequence_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('available_after', django.db.models.expressions.CombinedExpression(models.F('available_before'), '+', models.F('available_delta')))), name='quota_ledger_available_formula'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('frozen_after', django.db.models.expressions.CombinedExpression(models.F('frozen_before'), '+', models.F('frozen_delta')))), name='quota_ledger_frozen_formula'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('available_after__gte', 0)), name='quota_ledger_available_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('frozen_after__gte', 0)), name='quota_ledger_frozen_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('account_version_after', django.db.models.expressions.CombinedExpression(models.F('account_version_before'), '+', models.Value(1)))), name='quota_ledger_version_step'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ('freeze', 'consume', 'release')), ('hold__isnull', False)), models.Q(('action__in', ('initialize', 'grant', 'compensate', 'manual_deduct')), ('hold__isnull', True)), _connector='OR'), name='quota_ledger_hold_by_action'),
        ),
        migrations.AddIndex(
            model_name='quotaaccount',
            index=models.Index(fields=['user', 'quota_type'], name='quota_account_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaaccount',
            index=models.Index(fields=['subscription', 'quota_type', 'cycle_ends_at'], name='quota_account_cycle_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(fields=('subscription', 'quota_type', 'batch_key'), name='quota_account_unique_batch'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(fields=('subscription', 'quota_type', 'cycle_started_at'), name='quota_account_unique_cycle', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(('entitlement_amount__gte', 0)), name='quota_entitlement_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(('available__gte', 0)), name='quota_available_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(('frozen__gte', 0)), name='quota_frozen_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(('ledger_sequence__gte', 0)), name='quota_sequence_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='quota_account_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cycle_started_at__isnull', True), ('cycle_ends_at__isnull', True)), models.Q(('cycle_started_at__isnull', False), ('cycle_ends_at__isnull', False), ('cycle_started_at__lt', models.F('cycle_ends_at'))), _connector='OR'), name='quota_account_cycle_window'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cycle_started_at__isnull', False), ('scope', 'account_cycle')), models.Q(models.Q(('scope', 'account_cycle'), _negated=True), ('cycle_started_at__isnull', True)), _connector='OR'), name='quota_account_scope_cycle'),
        ),
    ]
