# Generated by Django 5.2.16 on 2026-08-02 09:27

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models

def backfill_hold_groups(apps, schema_editor):
    Hold = apps.get_model("quotas", "QuotaHold")
    Group = apps.get_model("quotas", "QuotaHoldGroup")
    seen = set()
    for hold in Hold.objects.order_by("id").iterator():
        key = (hold.user_id, hold.quota_type, hold.business_type, hold.business_id)
        if key in seen:
            raise RuntimeError("existing quota holds conflict with business-level uniqueness")
        seen.add(key)
        group = Group.objects.create(
            user_id=hold.user_id,
            quota_type=hold.quota_type,
            business_type=hold.business_type,
            business_id=hold.business_id,
            requested_amount=hold.requested_amount,
            consumed_amount=hold.consumed_amount,
            released_amount=hold.released_amount,
            status=hold.status,
            freeze_idempotency_key_version=hold.freeze_idempotency_key_version,
            freeze_idempotency_key_digest=hold.freeze_idempotency_key_digest,
            freeze_idempotency_scope_digest=hold.freeze_idempotency_scope_digest,
            freeze_request_digest=hold.freeze_request_digest,
            version=hold.version,
            settled_at=hold.settled_at,
        )
        Group.objects.filter(pk=group.pk).update(
            created_at=hold.created_at,
            updated_at=hold.updated_at,
        )
        Hold.objects.filter(pk=hold.pk).update(group_id=group.pk)



class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_subscriptionchange_subscriptionchangeevent_and_more'),
        ('quotas', '0003_backfill_subscription_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaHoldGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_type', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=64)),
                ('business_id', models.UUIDField()),
                ('requested_amount', models.BigIntegerField()),
                ('consumed_amount', models.BigIntegerField(default=0)),
                ('released_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', '待结算'), ('partially_settled', '部分结算'), ('settled', '已结算')], default='open', max_length=24)),
                ('freeze_idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('freeze_idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('freeze_idempotency_scope_digest', models.CharField(max_length=64)),
                ('freeze_request_digest', models.CharField(max_length=64)),
                ('version', models.BigIntegerField(default=1)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quota_hold_groups',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuotaTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_type', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quota_transfers',
                'ordering': ('change_id', 'quota_type', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='quotaaccount',
            name='quota_account_unique_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='quotahold',
            name='quota_hold_unique_business_target',
        ),
        migrations.RemoveConstraint(
            model_name='quotaledgerentry',
            name='quota_ledger_hold_by_action',
        ),
        migrations.AddField(
            model_name='quotaaccount',
            name='batch_type',
            field=models.CharField(choices=[('primary', '套餐基础批次'), ('carryover', '保留额度批次')], default='primary', max_length=16),
        ),
        migrations.AddField(
            model_name='quotaaccount',
            name='source_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carryover_quota_accounts', to='plans.subscriptionchange'),
        ),
        migrations.AddField(
            model_name='quotaaccount',
            name='spendable_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotaledgerentry',
            name='action',
            field=models.CharField(choices=[('initialize', '初始化'), ('freeze', '冻结'), ('consume', '扣除'), ('release', '返还'), ('grant', '赠送'), ('compensate', '补偿'), ('manual_deduct', '人工扣减'), ('plan_change_forfeit', '套餐变更清零'), ('plan_change_transfer_out', '套餐变更转出'), ('plan_change_transfer_in', '套餐变更转入')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_type', 'primary'), ('cycle_started_at__isnull', True)), fields=('subscription', 'quota_type'), name='quota_account_unique_noncycle'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_type', 'primary'), ('cycle_started_at__isnull', False)), fields=('subscription', 'quota_type', 'cycle_started_at'), name='quota_account_unique_cycle'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(('batch_type__in', ('primary', 'carryover'))), name='quota_account_batch_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch_type', 'primary'), ('source_change__isnull', True), ('spendable_until__isnull', True)), models.Q(('batch_type', 'carryover'), ('entitlement_amount', 0), ('source_change__isnull', False), ('spendable_until__isnull', False)), _connector='OR'), name='quota_account_batch_consistent'),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ('freeze', 'consume', 'release')), ('hold__isnull', False)), models.Q(('action__in', ('initialize', 'grant', 'compensate', 'manual_deduct', 'plan_change_forfeit', 'plan_change_transfer_out', 'plan_change_transfer_in')), ('hold__isnull', True)), _connector='OR'), name='quota_ledger_hold_by_action'),
        ),
        migrations.AddField(
            model_name='quotaholdgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_hold_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotahold',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='quotas.quotaholdgroup'),
        ),
        migrations.RunPython(backfill_hold_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quotahold',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='quotas.quotaholdgroup'),
        ),
        migrations.AddConstraint(
            model_name='quotahold',
            constraint=models.UniqueConstraint(fields=('group', 'account'), name='quota_hold_group_account_unique'),
        ),
        migrations.AddField(
            model_name='quotatransfer',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_transfers', to='plans.subscriptionchange'),
        ),
        migrations.AddField(
            model_name='quotatransfer',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='quotas.quotaaccount'),
        ),
        migrations.AddField(
            model_name='quotatransfer',
            name='target_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='quotas.quotaaccount'),
        ),
        migrations.AddField(
            model_name='quotatransfer',
            name='transfer_in_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer', to='quotas.quotaledgerentry'),
        ),
        migrations.AddField(
            model_name='quotatransfer',
            name='transfer_out_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer', to='quotas.quotaledgerentry'),
        ),
        migrations.AddIndex(
            model_name='quotaholdgroup',
            index=models.Index(fields=['user', 'status', 'created_at'], name='quota_hold_group_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotaholdgroup',
            constraint=models.UniqueConstraint(fields=('user', 'quota_type', 'business_type', 'business_id'), name='quota_hold_group_business_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotaholdgroup',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='quota_hold_group_requested_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaholdgroup',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_amount__gte', 0)), name='quota_hold_group_consumed_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaholdgroup',
            constraint=models.CheckConstraint(condition=models.Q(('released_amount__gte', 0)), name='quota_hold_group_released_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='quotaholdgroup',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_amount__lte', django.db.models.expressions.CombinedExpression(models.F('requested_amount'), '-', models.F('released_amount')))), name='quota_hold_group_total_lte'),
        ),
        migrations.AddConstraint(
            model_name='quotaholdgroup',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='quota_hold_group_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='quotaholdgroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumed_amount', 0), ('released_amount', 0), ('settled_at__isnull', True), ('status', 'open')), models.Q(('settled_at__isnull', True), ('status', 'partially_settled'), models.Q(('consumed_amount__gt', 0), ('released_amount__gt', 0), _connector='OR'), ('consumed_amount__lt', django.db.models.expressions.CombinedExpression(models.F('requested_amount'), '-', models.F('released_amount')))), models.Q(('settled_at__isnull', False), ('status', 'settled'), ('consumed_amount', django.db.models.expressions.CombinedExpression(models.F('requested_amount'), '-', models.F('released_amount')))), _connector='OR'), name='quota_hold_group_status_amounts'),
        ),
        migrations.AddConstraint(
            model_name='quotatransfer',
            constraint=models.UniqueConstraint(fields=('change', 'source_account', 'target_account'), name='quota_transfer_account_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotatransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='quota_transfer_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='quotatransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_account', models.F('target_account')), _negated=True), name='quota_transfer_distinct_accounts'),
        ),
    ]
