# Generated by Django 5.2.16 on 2026-08-03 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_remove_subscriptionchange_sub_change_status_valid_and_more'),
        ('quotas', '0007_plan_change_transfer_change_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaCycleReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_type', models.CharField(max_length=100)),
                ('boundary', models.DateTimeField()),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quota_cycle_resets',
                'ordering': ('boundary', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuotaExpiryDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy', models.CharField(choices=[('zero', 'Zero'), ('freeze', 'Freeze'), ('retain', 'Retain')], max_length=16)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quota_expiry_dispositions',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='quotaledgerentry',
            name='quota_ledger_hold_by_action',
        ),
        migrations.AlterField(
            model_name='quotaledgerentry',
            name='action',
            field=models.CharField(choices=[('initialize', '初始化'), ('freeze', '冻结'), ('consume', '扣除'), ('release', '返还'), ('grant', '赠送'), ('compensate', '补偿'), ('manual_deduct', '人工扣减'), ('plan_change_forfeit', '套餐变更清零'), ('plan_change_transfer_out', '套餐变更转出'), ('plan_change_transfer_in', '套餐变更转入'), ('cycle_forfeit', 'Cycle forfeit'), ('cycle_late_release_forfeit', 'Late cycle release forfeit'), ('expiry_forfeit', 'Expiry forfeit'), ('expiry_late_release_forfeit', 'Late expiry release forfeit')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='quotaledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ('freeze', 'consume', 'release')), ('hold__isnull', False)), models.Q(('action__in', ('initialize', 'grant', 'compensate', 'manual_deduct', 'plan_change_forfeit', 'plan_change_transfer_out', 'plan_change_transfer_in', 'cycle_forfeit', 'cycle_late_release_forfeit', 'expiry_forfeit', 'expiry_late_release_forfeit')), ('hold__isnull', True)), _connector='OR'), name='quota_ledger_hold_by_action'),
        ),
        migrations.AddField(
            model_name='quotacyclereset',
            name='forfeit_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_reset_forfeit', to='quotas.quotaledgerentry'),
        ),
        migrations.AddField(
            model_name='quotacyclereset',
            name='initialize_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_reset_initialize', to='quotas.quotaledgerentry'),
        ),
        migrations.AddField(
            model_name='quotacyclereset',
            name='next_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_cycle_reset', to='quotas.quotaaccount'),
        ),
        migrations.AddField(
            model_name='quotacyclereset',
            name='previous_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_cycle_reset', to='quotas.quotaaccount'),
        ),
        migrations.AddField(
            model_name='quotacyclereset',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_cycle_resets', to='plans.subscription'),
        ),
        migrations.AddField(
            model_name='quotaexpirydisposition',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expiry_disposition', to='quotas.quotaaccount'),
        ),
        migrations.AddField(
            model_name='quotaexpirydisposition',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expiry_disposition', to='quotas.quotaledgerentry'),
        ),
        migrations.AddField(
            model_name='quotaexpirydisposition',
            name='renewal_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quota_expiry_dispositions', to='plans.subscriptionchange'),
        ),
        migrations.AddField(
            model_name='quotaexpirydisposition',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_expiry_dispositions', to='plans.subscription'),
        ),
        migrations.AddConstraint(
            model_name='quotacyclereset',
            constraint=models.UniqueConstraint(fields=('subscription', 'quota_type', 'boundary'), name='quota_cycle_reset_unique_boundary'),
        ),
        migrations.AddConstraint(
            model_name='quotaexpirydisposition',
            constraint=models.CheckConstraint(condition=models.Q(('policy__in', ('zero', 'freeze', 'retain'))), name='quota_expiry_policy_valid'),
        ),
        migrations.AddConstraint(
            model_name='quotaexpirydisposition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('policy', 'zero'), ('renewal_change__isnull', True)), models.Q(('ledger_entry__isnull', True), ('policy', 'freeze'), ('renewal_change__isnull', True)), models.Q(('ledger_entry__isnull', True), ('policy', 'retain')), _connector='OR'), name='quota_expiry_evidence_consistent'),
        ),
    ]
