# Generated by Django 5.2.16 on 2026-08-15 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_lifecycle_postgresql_guards'),
        ('quotas', '0010_remove_quotaledgerentry_quota_ledger_hold_by_action_and_more'),
        ('subjects', '0013_subject_enrichment_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotaaccount',
            name='quota_account_unique_batch',
        ),
        migrations.RemoveConstraint(
            model_name='quotaaccount',
            name='quota_account_scope_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='quotaaccount',
            name='quota_account_unique_noncycle',
        ),
        migrations.RemoveConstraint(
            model_name='quotaaccount',
            name='quota_account_unique_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='quotacyclereset',
            name='quota_cycle_reset_unique_boundary',
        ),
        migrations.AddField(
            model_name='quotaaccount',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quota_accounts', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='quotacyclereset',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quota_cycle_resets', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='quotaaccount',
            name='scope',
            field=models.CharField(choices=[('subscription', '订阅'), ('account', '账号'), ('account_cycle', '账号周期'), ('subject_cycle', '主体周期')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(fields=('subscription', 'quota_type', 'subject', 'batch_key'), name='quota_account_unique_batch', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_type', 'primary'), ('cycle_started_at__isnull', True), ('subject__isnull', True)), fields=('subscription', 'quota_type'), name='quota_account_unique_noncycle'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_type', 'primary'), ('cycle_started_at__isnull', False), ('subject__isnull', True)), fields=('subscription', 'quota_type', 'cycle_started_at'), name='quota_account_unique_cycle'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_type', 'primary'), ('cycle_started_at__isnull', False), ('subject__isnull', False)), fields=('subscription', 'quota_type', 'subject', 'cycle_started_at'), name='quota_account_unique_subject_cycle'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cycle_started_at__isnull', False), ('scope__in', ('account_cycle', 'subject_cycle'))), models.Q(models.Q(('scope__in', ('account_cycle', 'subject_cycle')), _negated=True), ('cycle_started_at__isnull', True)), _connector='OR'), name='quota_account_scope_cycle'),
        ),
        migrations.AddConstraint(
            model_name='quotaaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'subject_cycle'), ('subject__isnull', False)), models.Q(models.Q(('scope', 'subject_cycle'), _negated=True), ('subject__isnull', True)), _connector='OR'), name='quota_account_subject_scope'),
        ),
        migrations.AddConstraint(
            model_name='quotacyclereset',
            constraint=models.UniqueConstraint(fields=('subscription', 'quota_type', 'subject', 'boundary'), name='quota_cycle_reset_unique_boundary', nulls_distinct=False),
        ),
    ]
