# Generated by Django 5.2.16 on 2026-08-15 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_postgresql_guards'),
        ('plans', '0013_lifecycle_postgresql_guards'),
        ('quotas', '0010_remove_quotaledgerentry_quota_ledger_hold_by_action_and_more'),
        ('subjects', '0013_subject_enrichment_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordGenerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('retry_scheduled', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('conflict', 'Conflict'), ('superseded', 'Superseded')], max_length=24)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('safe_summary', models.JSONField(default=dict)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'keyword_generation_events',
                'ordering': ('job_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='KeywordGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry_wait', 'Retry wait'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('conflict', 'Conflict'), ('superseded', 'Superseded')], default='queued', max_length=16)),
                ('billing_mode', models.CharField(choices=[('free_initial', 'Free initial'), ('regeneration', 'Regeneration')], max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('expected_keyword_set_version', models.PositiveBigIntegerField()),
                ('target_count', models.PositiveIntegerField()),
                ('include_short', models.BooleanField(default=False)),
                ('include_long_tail', models.BooleanField(default=False)),
                ('include_regional', models.BooleanField(default=False)),
                ('regions', models.JSONField(default=list)),
                ('input_subject_values', models.JSONField(default=dict)),
                ('historical_exclusions', models.JSONField(default=list)),
                ('provider_key', models.CharField(max_length=32)),
                ('model_key', models.CharField(max_length=64)),
                ('adapter_version', models.CharField(max_length=32)),
                ('prompt_version', models.CharField(max_length=32)),
                ('input_digest', models.CharField(max_length=64)),
                ('idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('generation', models.UUIDField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'keyword_generation_jobs',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='KeywordGenerationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_snapshot', models.JSONField()),
                ('output_digest', models.CharField(max_length=64)),
                ('item_count', models.PositiveIntegerField()),
                ('applied_keyword_set_version', models.PositiveBigIntegerField()),
                ('provider_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'keyword_generation_results',
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='ai_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='base_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_keywords', to='keywords.keyword'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='business_category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='relevance_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_intent',
            field=models.CharField(blank=True, choices=[('informational', 'Informational'), ('navigational', 'Navigational'), ('commercial', 'Commercial'), ('transactional', 'Transactional')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='keyworddraftitem',
            name='ai_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='keyworddraftitem',
            name='base_keyword_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='keyworddraftitem',
            name='business_category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='keyworddraftitem',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='keyworddraftitem',
            name='relevance_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyworddraftitem',
            name='search_intent',
            field=models.CharField(blank=True, choices=[('informational', 'Informational'), ('navigational', 'Navigational'), ('commercial', 'Commercial'), ('transactional', 'Transactional')], max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.CheckConstraint(condition=models.Q(('search_intent__isnull', True), ('search_intent__in', ('informational', 'navigational', 'commercial', 'transactional')), _connector='OR'), name='keyword_formal_intent_valid'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.CheckConstraint(condition=models.Q(('priority__isnull', True), ('priority__in', ('high', 'medium', 'low')), _connector='OR'), name='keyword_formal_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.CheckConstraint(condition=models.Q(('relevance_score__isnull', True), ('relevance_score__lte', 100), _connector='OR'), name='keyword_formal_relevance_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='keyworddraftitem',
            constraint=models.CheckConstraint(condition=models.Q(('search_intent__isnull', True), ('search_intent__in', ('informational', 'navigational', 'commercial', 'transactional')), _connector='OR'), name='keyword_draft_intent_valid'),
        ),
        migrations.AddConstraint(
            model_name='keyworddraftitem',
            constraint=models.CheckConstraint(condition=models.Q(('priority__isnull', True), ('priority__in', ('high', 'medium', 'low')), _connector='OR'), name='keyword_draft_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='keyworddraftitem',
            constraint=models.CheckConstraint(condition=models.Q(('relevance_score__isnull', True), ('relevance_score__lte', 100), _connector='OR'), name='keyword_draft_relevance_lte_100'),
        ),
        migrations.AddField(
            model_name='keywordgenerationjob',
            name='keyword_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='keywords.keywordset'),
        ),
        migrations.AddField(
            model_name='keywordgenerationjob',
            name='quota_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keyword_generation_jobs', to='quotas.quotaholdgroup'),
        ),
        migrations.AddField(
            model_name='keywordgenerationjob',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keyword_generation_jobs', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='keywordgenerationjob',
            name='subject_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keyword_generation_jobs', to='subjects.subjectversion'),
        ),
        migrations.AddField(
            model_name='keywordgenerationjob',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keyword_generation_jobs', to='plans.subscription'),
        ),
        migrations.AddField(
            model_name='keywordgenerationjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keyword_generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keywordgenerationevent',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='keywords.keywordgenerationjob'),
        ),
        migrations.AddField(
            model_name='keywordgenerationresult',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='keywords.keywordgenerationjob'),
        ),
        migrations.AddIndex(
            model_name='keywordgenerationjob',
            index=models.Index(fields=['subject', 'status', 'created_at'], name='kw_gen_status_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordgenerationjob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='kw_gen_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='keywordgenerationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running', 'retry_wait'))), fields=('subject',), name='keyword_generation_one_open'),
        ),
        migrations.AddConstraint(
            model_name='keywordgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('queued', 'running', 'retry_wait', 'succeeded', 'failed', 'conflict', 'superseded'))), name='keyword_generation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='keywordgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_mode', 'free_initial'), ('quota_hold__isnull', True)), models.Q(('billing_mode', 'regeneration'), ('quota_hold__isnull', False)), _connector='OR'), name='keyword_generation_billing_hold'),
        ),
        migrations.AddConstraint(
            model_name='keywordgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1), ('target_count__gte', 1), ('attempts__gte', 0), ('retry_count__gte', 0)), name='keyword_generation_counts_valid'),
        ),
        migrations.AddConstraint(
            model_name='keywordgenerationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('generation__isnull', True), ('started_at__isnull', True), ('status', 'queued')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('started_at__isnull', False), ('status', 'running')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('next_attempt_at__isnull', False), ('status', 'retry_wait')), models.Q(('finished_at__isnull', False), ('generation__isnull', False), ('status__in', ('succeeded', 'failed', 'conflict', 'superseded'))), _connector='OR'), name='keyword_generation_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='keywordgenerationresult',
            constraint=models.CheckConstraint(condition=models.Q(('item_count__gte', 1), ('applied_keyword_set_version__gte', 1), models.Q(('output_digest', ''), _negated=True)), name='keyword_generation_result_valid'),
        ),
    ]
