# Generated by Django 5.2.16 on 2026-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_keywordgenerationevent_keywordgenerationjob_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keywordgenerationevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('started', 'retry_scheduled', 'succeeded', 'failed', 'conflict', 'superseded'))), name='keyword_generation_event_type_valid'),
        ),
    ]
