# Generated by Django 5.2.16 on 2026-08-15 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_keyword_generation_postgresql_guards'),
        ('plans', '0013_lifecycle_postgresql_guards'),
        ('quotas', '0012_subject_cycle_postgresql_guards'),
        ('subjects', '0013_subject_enrichment_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistillationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry_wait', 'Retry wait'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('conflict', 'Conflict'), ('superseded', 'Superseded')], default='queued', max_length=16)),
                ('billing_mode', models.CharField(choices=[('free_initial', 'Free initial'), ('regeneration', 'Regeneration')], max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('expected_workspace_version', models.PositiveBigIntegerField()),
                ('input_subject_values', models.JSONField(default=dict)),
                ('input_keywords', models.JSONField(default=list)),
                ('provider_key', models.CharField(max_length=32)),
                ('model_key', models.CharField(max_length=64)),
                ('adapter_version', models.CharField(max_length=32)),
                ('prompt_version', models.CharField(max_length=32)),
                ('input_digest', models.CharField(max_length=64)),
                ('idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('generation', models.UUIDField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_keyword_set_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_jobs', to='keywords.keywordsetversion')),
                ('quota_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distillation_jobs', to='quotas.quotaholdgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_jobs', to='subjects.subject')),
                ('subject_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_jobs', to='subjects.subjectversion')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_jobs', to='plans.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distillation_jobs',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DistillationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('retry_scheduled', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('conflict', 'Conflict'), ('superseded', 'Superseded')], max_length=24)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('safe_summary', models.JSONField(default=dict)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='keywords.distillationjob')),
            ],
            options={
                'db_table': 'distillation_events',
                'ordering': ('job_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DistillationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_snapshot', models.JSONField()),
                ('output_digest', models.CharField(max_length=64)),
                ('item_count', models.PositiveIntegerField()),
                ('applied_workspace_version', models.PositiveBigIntegerField()),
                ('provider_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='keywords.distillationjob')),
            ],
            options={
                'db_table': 'distillation_results',
            },
        ),
        migrations.CreateModel(
            name='DistillationSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveBigIntegerField()),
                ('content_digest', models.CharField(max_length=64)),
                ('item_count', models.PositiveIntegerField()),
                ('confirmed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_distillation_sets', to=settings.AUTH_USER_MODEL)),
                ('input_keyword_set_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_sets', to='keywords.keywordsetversion')),
                ('source_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_sets', to='keywords.distillationresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_sets', to='subjects.subject')),
                ('subject_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_sets', to='subjects.subjectversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distillation_sets',
                'ordering': ('workspace_id', 'version_no', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DistillationItem',
            fields=[
                ('action', models.CharField(choices=[('keep', 'Keep'), ('merge', 'Merge'), ('delete', 'Delete'), ('low_value', 'Low value')], max_length=16)),
                ('merge_group_key', models.UUIDField(blank=True, null=True)),
                ('ai_action', models.CharField(choices=[('keep', 'Keep'), ('merge', 'Merge'), ('delete', 'Delete'), ('low_value', 'Low value')], max_length=16)),
                ('ai_merge_group_key', models.UUIDField(blank=True, null=True)),
                ('ai_reason', models.CharField(max_length=1000)),
                ('user_reason', models.CharField(blank=True, max_length=1000)),
                ('user_overridden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_canonical_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='keywords.keyword')),
                ('canonical_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='keywords.keyword')),
                ('source_keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='keywords.keyword')),
                ('distillation_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='keywords.distillationset')),
            ],
            options={
                'db_table': 'distillation_items',
                'ordering': ('distillation_set_id', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DistillationWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_workspaces', to='keywords.distillationset')),
                ('draft_input_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_drafts', to='keywords.keywordsetversion')),
                ('draft_source_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_workspaces', to='keywords.distillationresult')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_workspace', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distillation_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distillation_workspaces',
            },
        ),
        migrations.AddField(
            model_name='distillationset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='keywords.distillationworkspace'),
        ),
        migrations.CreateModel(
            name='DistillationDraftItem',
            fields=[
                ('action', models.CharField(choices=[('keep', 'Keep'), ('merge', 'Merge'), ('delete', 'Delete'), ('low_value', 'Low value')], max_length=16)),
                ('merge_group_key', models.UUIDField(blank=True, null=True)),
                ('ai_action', models.CharField(choices=[('keep', 'Keep'), ('merge', 'Merge'), ('delete', 'Delete'), ('low_value', 'Low value')], max_length=16)),
                ('ai_merge_group_key', models.UUIDField(blank=True, null=True)),
                ('ai_reason', models.CharField(max_length=1000)),
                ('user_reason', models.CharField(blank=True, max_length=1000)),
                ('user_overridden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_canonical_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='keywords.keyword')),
                ('canonical_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='keywords.keyword')),
                ('source_keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='keywords.keyword')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_items', to='keywords.distillationworkspace')),
            ],
            options={
                'db_table': 'distillation_draft_items',
                'ordering': ('workspace_id', 'sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='distillationjob',
            index=models.Index(fields=['subject', 'status', 'created_at'], name='distill_status_idx'),
        ),
        migrations.AddIndex(
            model_name='distillationjob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='distill_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='distillationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running', 'retry_wait'))), fields=('subject',), name='distillation_one_open'),
        ),
        migrations.AddConstraint(
            model_name='distillationjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('queued', 'running', 'retry_wait', 'succeeded', 'failed', 'conflict', 'superseded'))), name='distillation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('billing_mode', 'free_initial'), ('quota_hold__isnull', True)), models.Q(('billing_mode', 'regeneration'), ('quota_hold__isnull', False)), _connector='OR'), name='distillation_billing_hold'),
        ),
        migrations.AddConstraint(
            model_name='distillationjob',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1), ('attempts__gte', 0), ('retry_count__gte', 0)), name='distillation_counts_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('generation__isnull', True), ('started_at__isnull', True), ('status', 'queued')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('started_at__isnull', False), ('status', 'running')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('next_attempt_at__isnull', False), ('status', 'retry_wait')), models.Q(('finished_at__isnull', False), ('generation__isnull', False), ('status__in', ('succeeded', 'failed', 'conflict', 'superseded'))), _connector='OR'), name='distillation_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='distillationevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('started', 'retry_scheduled', 'succeeded', 'failed', 'conflict', 'superseded'))), name='distillation_event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationresult',
            constraint=models.CheckConstraint(condition=models.Q(('item_count__gte', 1), ('applied_workspace_version__gte', 1), models.Q(('output_digest', ''), _negated=True)), name='distillation_result_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationitem',
            constraint=models.UniqueConstraint(fields=('distillation_set', 'source_keyword'), name='distillation_item_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='distillationitem',
            constraint=models.UniqueConstraint(fields=('distillation_set', 'sort_order'), name='distillation_item_sort_unique'),
        ),
        migrations.AddConstraint(
            model_name='distillationitem',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('keep', 'merge', 'delete', 'low_value'))), name='distillation_item_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_action__in', ('keep', 'merge', 'delete', 'low_value'))), name='distillation_item_ai_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'merge'), ('canonical_keyword__isnull', False), ('merge_group_key__isnull', False)), models.Q(models.Q(('action', 'merge'), _negated=True), ('canonical_keyword__isnull', True), ('merge_group_key__isnull', True)), _connector='OR'), name='distillation_item_action_shape'),
        ),
        migrations.AddConstraint(
            model_name='distillationitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ai_action', 'merge'), ('ai_canonical_keyword__isnull', False), ('ai_merge_group_key__isnull', False)), models.Q(models.Q(('ai_action', 'merge'), _negated=True), ('ai_canonical_keyword__isnull', True), ('ai_merge_group_key__isnull', True)), _connector='OR'), name='distillation_item_ai_action_shape'),
        ),
        migrations.AddConstraint(
            model_name='distillationitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_reason', ''), _negated=True), name='distillation_item_ai_reason_present'),
        ),
        migrations.AddConstraint(
            model_name='distillationworkspace',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='distillation_workspace_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='distillationset',
            constraint=models.UniqueConstraint(fields=('workspace', 'version_no'), name='distillation_set_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='distillationset',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1), ('item_count__gte', 1), models.Q(('content_digest', ''), _negated=True)), name='distillation_set_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationdraftitem',
            constraint=models.UniqueConstraint(fields=('workspace', 'source_keyword'), name='distillation_draft_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='distillationdraftitem',
            constraint=models.UniqueConstraint(fields=('workspace', 'sort_order'), name='distillation_draft_sort_unique'),
        ),
        migrations.AddConstraint(
            model_name='distillationdraftitem',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ('keep', 'merge', 'delete', 'low_value'))), name='distillation_draft_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationdraftitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_action__in', ('keep', 'merge', 'delete', 'low_value'))), name='distillation_draft_ai_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='distillationdraftitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action', 'merge'), ('canonical_keyword__isnull', False), ('merge_group_key__isnull', False)), models.Q(models.Q(('action', 'merge'), _negated=True), ('canonical_keyword__isnull', True), ('merge_group_key__isnull', True)), _connector='OR'), name='distillation_draft_action_shape'),
        ),
        migrations.AddConstraint(
            model_name='distillationdraftitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ai_action', 'merge'), ('ai_canonical_keyword__isnull', False), ('ai_merge_group_key__isnull', False)), models.Q(models.Q(('ai_action', 'merge'), _negated=True), ('ai_canonical_keyword__isnull', True), ('ai_merge_group_key__isnull', True)), _connector='OR'), name='distillation_draft_ai_action_shape'),
        ),
        migrations.AddConstraint(
            model_name='distillationdraftitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_reason', ''), _negated=True), name='distillation_draft_ai_reason_present'),
        ),
    ]
