from django.urls import path

from .views import (
    AdminAICapabilityRuntimeDetailView,
    AdminAICapabilityRuntimeListView,
    AdminAIModelDetailView,
    AdminAIModelDisableView,
    AdminAIModelEnableView,
    AdminAIModelListView,
    AdminAIModelPauseView,
    AdminAIModelRuntimeConfigDetailView,
    AdminAIModelRuntimeConfigListView,
    AdminAIModelUnpauseView,
    AdminAPICredentialListCreateView,
    AdminAPICredentialRotateView,
    AdminAPICredentialTestView,
    AdminCredentialCapabilityBindingView,
)

urlpatterns = [
    path(
        "admin/ai-capability-runtimes",
        AdminAICapabilityRuntimeListView.as_view(),
        name="admin-ai-capability-runtimes",
    ),
    path(
        "admin/ai-capability-runtimes/<uuid:config_id>",
        AdminAICapabilityRuntimeDetailView.as_view(),
        name="admin-ai-capability-runtime",
    ),
    path(
        "admin/api-credential-bindings/<str:provider_key>",
        AdminCredentialCapabilityBindingView.as_view(),
        name="admin-api-credential-bindings",
    ),
    path(
        "admin/api-credentials",
        AdminAPICredentialListCreateView.as_view(),
        name="admin-api-credentials",
    ),
    path(
        "admin/api-credentials/<uuid:credential_id>/rotate",
        AdminAPICredentialRotateView.as_view(),
        name="admin-api-credential-rotate",
    ),
    path(
        "admin/api-credentials/<uuid:credential_id>/test",
        AdminAPICredentialTestView.as_view(),
        name="admin-api-credential-test",
    ),
    path("admin/ai-models", AdminAIModelListView.as_view(), name="admin-ai-models"),
    path(
        "admin/ai-models/<uuid:model_id>",
        AdminAIModelDetailView.as_view(),
        name="admin-ai-model-detail",
    ),
    path(
        "admin/ai-models/<uuid:model_id>/enable",
        AdminAIModelEnableView.as_view(),
        name="admin-ai-model-enable",
    ),
    path(
        "admin/ai-models/<uuid:model_id>/disable",
        AdminAIModelDisableView.as_view(),
        name="admin-ai-model-disable",
    ),
    path(
        "admin/ai-models/<uuid:model_id>/pause",
        AdminAIModelPauseView.as_view(),
        name="admin-ai-model-pause",
    ),
    path(
        "admin/ai-models/<uuid:model_id>/unpause",
        AdminAIModelUnpauseView.as_view(),
        name="admin-ai-model-unpause",
    ),
    path(
        "admin/ai-model-runtime-configs",
        AdminAIModelRuntimeConfigListView.as_view(),
        name="admin-ai-model-runtime-configs",
    ),
    path(
        "admin/ai-model-runtime-configs/<uuid:model_id>",
        AdminAIModelRuntimeConfigDetailView.as_view(),
        name="admin-ai-model-runtime-config-detail",
    ),
]
