# Generated manually for negative-index v1.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subjects", "0017_promote_saved_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="NegativeIndexScan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("partial", "Partial"), ("limit_reached", "Limit reached"), ("failed", "Failed")], default="queued", max_length=20)),
                ("stage", models.CharField(choices=[("preparing", "Preparing"), ("searching", "Searching"), ("classifying", "Classifying"), ("verifying", "Verifying"), ("clustering", "Clustering"), ("scoring", "Scoring"), ("completed", "Completed")], default="preparing", max_length=20)),
                ("provider", models.CharField(default="baidu", max_length=32)),
                ("ai_provider", models.CharField(blank=True, max_length=32)),
                ("ai_model_key", models.CharField(blank=True, max_length=100)),
                ("ai_provider_model_id", models.CharField(blank=True, max_length=255)),
                ("query_count", models.PositiveIntegerField(default=0)),
                ("provider_request_count", models.PositiveIntegerField(default=0)),
                ("provider_error_count", models.PositiveIntegerField(default=0)),
                ("raw_result_count", models.PositiveIntegerField(default=0)),
                ("unique_result_count", models.PositiveIntegerField(default=0)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                ("negative_item_count", models.PositiveIntegerField(default=0)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("high_risk_event_count", models.PositiveIntegerField(default=0)),
                ("recent_30d_event_count", models.PositiveIntegerField(default=0)),
                ("verified_item_count", models.PositiveIntegerField(default=0)),
                ("index_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("factor_scores", models.JSONField(default=dict)),
                ("progress", models.JSONField(default=dict)),
                ("formula_version", models.CharField(default="negative-index-v1", max_length=64)),
                ("classifier_version", models.CharField(default="negative-classifier-v1", max_length=64)),
                ("stable_error_code", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="negative_index_scans", to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="negative_index_scans", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "negative_index_scans",
                "ordering": ("-created_at", "-id"),
                "indexes": [models.Index(fields=["user", "subject", "created_at"], name="neg_scan_user_subj_idx"), models.Index(fields=["status", "created_at"], name="neg_scan_status_idx")],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(status__in=("queued", "running", "succeeded", "partial", "limit_reached", "failed")), name="neg_scan_status_valid"),
                    models.CheckConstraint(condition=models.Q(stage__in=("preparing", "searching", "classifying", "verifying", "clustering", "scoring", "completed")), name="neg_scan_stage_valid"),
                    models.CheckConstraint(condition=models.Q(index_score__isnull=True) | models.Q(index_score__gte=0, index_score__lte=100), name="neg_scan_index_range"),
                    models.UniqueConstraint(condition=models.Q(status__in=("queued", "running")), fields=("user", "subject"), name="neg_scan_one_active_per_subject"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NegativeEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category", models.CharField(choices=[("regulatory", "监管处罚"), ("judicial", "司法风险"), ("consumer_complaint", "消费者投诉"), ("product_service_incident", "产品/服务事故"), ("business_operation", "经营风险"), ("media_negative", "媒体负面"), ("online_opinion", "网络舆情"), ("other", "其他")], max_length=32)),
                ("claim_type", models.CharField(choices=[("official_finding", "官方结论"), ("reported_fact", "媒体事实报道"), ("reported_claim", "媒体转述指控"), ("user_allegation", "用户指控"), ("opinion", "观点"), ("rumor", "传闻"), ("rebuttal", "回应/澄清")], max_length=32)),
                ("status", models.CharField(choices=[("suspected", "疑似"), ("reported", "已报道"), ("confirmed", "已确认"), ("disputed", "存在争议"), ("resolved", "已解决"), ("retracted", "已撤回"), ("false_positive", "误判")], max_length=24)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("severity_score", models.PositiveSmallIntegerField(default=0)),
                ("evidence_score", models.PositiveSmallIntegerField(default=0)),
                ("visibility_score", models.PositiveSmallIntegerField(default=0)),
                ("freshness_score", models.PositiveSmallIntegerField(default=0)),
                ("current_risk", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("source_count", models.PositiveIntegerField(default=0)),
                ("independent_domain_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("cluster_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="negative_index.negativeindexscan")),
            ],
            options={
                "db_table": "negative_events",
                "ordering": ("-current_risk", "-last_seen_at", "id"),
                "indexes": [models.Index(fields=["scan", "category", "current_risk"], name="neg_event_category_idx"), models.Index(fields=["scan", "status", "current_risk"], name="neg_event_status_idx"), models.Index(fields=["scan", "last_seen_at"], name="neg_event_date_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("scan", "cluster_key"), name="neg_event_cluster_unique"),
                    models.CheckConstraint(condition=models.Q(severity_score__lte=100), name="neg_event_severity_lte100"),
                    models.CheckConstraint(condition=models.Q(evidence_score__lte=100), name="neg_event_evidence_lte100"),
                    models.CheckConstraint(condition=models.Q(visibility_score__lte=100), name="neg_event_visibility_lte100"),
                    models.CheckConstraint(condition=models.Q(freshness_score__lte=100), name="neg_event_freshness_lte100"),
                    models.CheckConstraint(condition=models.Q(current_risk__gte=0, current_risk__lte=100), name="neg_event_risk_range"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NegativeIndexItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_url", models.URLField(max_length=4096)),
                ("normalized_url", models.CharField(max_length=4096)),
                ("domain", models.CharField(max_length=255)),
                ("root_domain", models.CharField(max_length=255)),
                ("website", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=1000)),
                ("snippet", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source_type", models.CharField(max_length=32)),
                ("authority_score", models.PositiveSmallIntegerField(default=0)),
                ("relevance_score", models.PositiveSmallIntegerField(default=0)),
                ("visibility_score", models.PositiveSmallIntegerField(default=0)),
                ("freshness_score", models.PositiveSmallIntegerField(default=0)),
                ("best_rank", models.PositiveIntegerField(default=51)),
                ("matched_query_count", models.PositiveIntegerField(default=1)),
                ("rule_signal_score", models.PositiveSmallIntegerField(default=0)),
                ("negative_confidence", models.PositiveSmallIntegerField(default=0)),
                ("severity_score", models.PositiveSmallIntegerField(default=0)),
                ("evidence_confidence", models.PositiveSmallIntegerField(default=0)),
                ("category", models.CharField(choices=[("regulatory", "监管处罚"), ("judicial", "司法风险"), ("consumer_complaint", "消费者投诉"), ("product_service_incident", "产品/服务事故"), ("business_operation", "经营风险"), ("media_negative", "媒体负面"), ("online_opinion", "网络舆情"), ("other", "其他")], max_length=32)),
                ("claim_type", models.CharField(choices=[("official_finding", "官方结论"), ("reported_fact", "媒体事实报道"), ("reported_claim", "媒体转述指控"), ("user_allegation", "用户指控"), ("opinion", "观点"), ("rumor", "传闻"), ("rebuttal", "回应/澄清")], max_length=32)),
                ("event_status", models.CharField(choices=[("suspected", "疑似"), ("reported", "已报道"), ("confirmed", "已确认"), ("disputed", "存在争议"), ("resolved", "已解决"), ("retracted", "已撤回"), ("false_positive", "误判")], max_length=24)),
                ("event_title", models.CharField(max_length=500)),
                ("ai_summary", models.TextField(blank=True)),
                ("classification_source", models.CharField(choices=[("ai", "AI摘要判定"), ("rule", "保守规则判定"), ("verified_ai", "正文核验后AI判定")], max_length=20)),
                ("verification_status", models.CharField(choices=[("not_requested", "未核验"), ("succeeded", "已核验"), ("failed", "核验失败")], default="not_requested", max_length=20)),
                ("verification_excerpt", models.TextField(blank=True)),
                ("verification_error_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="negative_index.negativeevent")),
                ("scan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="negative_index.negativeindexscan")),
            ],
            options={
                "db_table": "negative_index_items",
                "ordering": ("-severity_score", "-evidence_confidence", "best_rank", "id"),
                "indexes": [models.Index(fields=["scan", "category", "severity_score"], name="neg_item_category_idx"), models.Index(fields=["scan", "root_domain"], name="neg_item_domain_idx"), models.Index(fields=["event", "published_at"], name="neg_item_event_date_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("scan", "normalized_url"), name="neg_item_scan_url_unique"),
                    models.CheckConstraint(condition=models.Q(authority_score__lte=100), name="neg_item_authority_lte100"),
                    models.CheckConstraint(condition=models.Q(relevance_score__lte=100), name="neg_item_relevance_lte100"),
                    models.CheckConstraint(condition=models.Q(visibility_score__lte=100), name="neg_item_visibility_lte100"),
                    models.CheckConstraint(condition=models.Q(freshness_score__lte=100), name="neg_item_freshness_lte100"),
                    models.CheckConstraint(condition=models.Q(rule_signal_score__lte=100), name="neg_item_rule_lte100"),
                    models.CheckConstraint(condition=models.Q(negative_confidence__lte=100), name="neg_item_negative_lte100"),
                    models.CheckConstraint(condition=models.Q(severity_score__lte=100), name="neg_item_severity_lte100"),
                    models.CheckConstraint(condition=models.Q(evidence_confidence__lte=100), name="neg_item_evidence_lte100"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NegativeIndexHit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("query", models.CharField(max_length=200)),
                ("rank", models.PositiveIntegerField()),
                ("range_start", models.DateField(blank=True, null=True)),
                ("range_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hits", to="negative_index.negativeindexitem")),
                ("scan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hits", to="negative_index.negativeindexscan")),
            ],
            options={
                "db_table": "negative_index_hits",
                "ordering": ("scan_id", "query", "rank", "id"),
                "indexes": [models.Index(fields=["scan", "query", "rank"], name="neg_hit_query_rank_idx"), models.Index(fields=["item", "rank"], name="neg_hit_item_rank_idx")],
                "constraints": [models.UniqueConstraint(fields=("scan", "item", "query", "range_start", "range_end"), name="neg_hit_item_query_unique", nulls_distinct=False)],
            },
        ),
    ]
