# Generated by Django 5.x for the GEO website builder.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subjects", "0017_promote_saved_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "style_key",
                    models.CharField(
                        choices=[
                            ("professional", "专业商务"),
                            ("technology", "科技简约"),
                            ("premium", "高端品牌"),
                        ],
                        default="professional",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "待生成"),
                            ("generating", "正在生成"),
                            ("ready", "已生成"),
                            ("failed", "生成未完成"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("selected_asset_ids", models.JSONField(default=list)),
                ("selected_document_ids", models.JSONField(default=list)),
                ("source_snapshot", models.JSONField(default=dict)),
                ("site_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("site_json", models.JSONField(default=dict)),
                ("generation_count", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_project",
                        to="subjects.subject",
                    ),
                ),
                (
                    "subject_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_projects",
                        to="subjects.subjectversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "website_projects",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="WebsiteGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "等待生成"),
                            ("running", "正在生成"),
                            ("succeeded", "生成完成"),
                            ("failed", "生成未完成"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("input_snapshot", models.JSONField(default=dict)),
                ("input_digest", models.CharField(max_length=64)),
                ("provider_key", models.CharField(max_length=100)),
                ("provider_model_id", models.CharField(max_length=255)),
                ("adapter_version", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=100)),
                ("normalized_usage", models.JSONField(default=dict)),
                ("provider_request_id", models.CharField(blank=True, max_length=128)),
                ("safe_error_code", models.CharField(blank=True, max_length=100)),
                ("idempotency_key_digest", models.CharField(max_length=64, unique=True)),
                ("request_id", models.UUIDField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_jobs",
                        to="websites.websiteproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "website_generation_jobs",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="websiteproject",
            index=models.Index(
                fields=["user", "status", "updated_at"],
                name="website_project_user_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="websiteproject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("style_key__in", ("professional", "technology", "premium"))
                ),
                name="website_project_style_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="websiteproject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("draft", "generating", "ready", "failed"))
                ),
                name="website_project_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="websiteproject",
            constraint=models.CheckConstraint(
                condition=models.Q(("site_schema_version", 1)),
                name="website_project_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="websiteproject",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="website_project_version_gte_1",
            ),
        ),
        migrations.AddIndex(
            model_name="websitegenerationjob",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="website_job_user_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="websitegenerationjob",
            index=models.Index(
                fields=["project", "status", "created_at"],
                name="website_job_project_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="websitegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("queued", "running", "succeeded", "failed"))
                ),
                name="website_job_status_valid",
            ),
        ),
    ]
