# Generated by Django 5.2.17 on 2026-08-31 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0015_add_quota_refund_action'),
        ('websites', '0002_website_design_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitegenerationjob',
            name='quota_hold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='website_generation_job', to='quotas.quotaholdgroup'),
        ),
    ]
