from django.urls import path

from .views import (
    GeoDetectionCancelView,
    GeoDetectionCreateView,
    GeoDetectionDetailView,
    GeoDetectionEstimateView,
    GeoDetectionModelProgressView,
    GeoDetectionOptionsView,
    GeoDetectionReportView,
    GeoModelCallResponseView,
    GeoModelsView,
    GeoReportAdjustedRetestView,
    GeoReportAnswerView,
    GeoReportComparisonView,
    GeoReportDetailView,
    GeoReportExportDetailView,
    GeoReportExportView,
    GeoReportHistoryView,
    GeoReportQuestionsView,
    GeoReportQuestionView,
    GeoReportQuickRetestView,
    GeoReportRetestView,
    GeoReportTrendsView,
)

urlpatterns = [
    path("geo/models", GeoModelsView.as_view(), name="geo-models"),
    path(
        "subjects/<uuid:subject_id>/geo/detection-options",
        GeoDetectionOptionsView.as_view(),
        name="geo-detection-options",
    ),
    path(
        "subjects/<uuid:subject_id>/geo/estimate",
        GeoDetectionEstimateView.as_view(),
        name="geo-detection-estimate",
    ),
    path(
        "subjects/<uuid:subject_id>/geo/detections",
        GeoDetectionCreateView.as_view(),
        name="geo-detection-create",
    ),
    path(
        "geo/detections/<uuid:detection_id>",
        GeoDetectionDetailView.as_view(),
        name="geo-detection-detail",
    ),
    path(
        "geo/detections/<uuid:detection_id>/model-progress",
        GeoDetectionModelProgressView.as_view(),
        name="geo-detection-model-progress",
    ),
    path(
        "geo/detections/<uuid:detection_id>/cancel",
        GeoDetectionCancelView.as_view(),
        name="geo-detection-cancel",
    ),
    path(
        "geo/detections/<uuid:detection_id>/report",
        GeoDetectionReportView.as_view(),
        name="geo-detection-report",
    ),
    path("geo/reports/<uuid:report_id>", GeoReportDetailView.as_view(), name="geo-report"),
    path(
        "geo/reports/<uuid:report_id>/questions",
        GeoReportQuestionsView.as_view(),
        name="geo-report-questions",
    ),
    path(
        "geo/reports/<uuid:report_id>/questions/<uuid:question_id>",
        GeoReportQuestionView.as_view(),
        name="geo-report-question",
    ),
    path(
        "geo/reports/<uuid:report_id>/answers/<uuid:call_id>",
        GeoReportAnswerView.as_view(),
        name="geo-report-answer",
    ),
    path(
        "geo/model-calls/<uuid:call_id>/response",
        GeoModelCallResponseView.as_view(),
        name="geo-model-call-response",
    ),
    path(
        "subjects/<uuid:subject_id>/geo/reports",
        GeoReportHistoryView.as_view(),
        name="geo-report-history",
    ),
    path(
        "subjects/<uuid:subject_id>/geo/trends",
        GeoReportTrendsView.as_view(),
        name="geo-report-trends",
    ),
    path(
        "geo/reports/<uuid:report_id>/comparison/<uuid:other_id>",
        GeoReportComparisonView.as_view(),
        name="geo-report-comparison",
    ),
    path(
        "geo/reports/<uuid:report_id>/exports",
        GeoReportExportView.as_view(),
        name="geo-report-export",
    ),
    path(
        "geo/report-exports/<uuid:export_id>",
        GeoReportExportDetailView.as_view(),
        name="geo-report-export-detail",
    ),
    path(
        "report-exports/<uuid:export_id>",
        GeoReportExportDetailView.as_view(),
        name="report-export-detail",
    ),
    path(
        "geo/reports/<uuid:report_id>/quick-retest",
        GeoReportQuickRetestView.as_view(),
        name="geo-report-quick-retest",
    ),
    path(
        "geo/reports/<uuid:report_id>/adjusted-retest",
        GeoReportAdjustedRetestView.as_view(),
        name="geo-report-adjusted-retest",
    ),
    path(
        "geo/reports/<uuid:report_id>/retest",
        GeoReportRetestView.as_view(),
        name="geo-report-retest",
    ),
]
