# Generated by Django 5.2.16 on 2026-07-30 10:54

import apps.users.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('approval_status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核拒绝')], db_index=True, default='pending', max_length=16)),
                ('account_status', models.CharField(choices=[('active', '正常'), ('frozen', '冻结'), ('cancel_pending', '注销冷静期'), ('cancelled', '已注销')], db_index=True, default='active', max_length=16)),
                ('approval_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('login_method', models.CharField(choices=[('password', '密码')], max_length=16)),
                ('success', models.BooleanField(db_index=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', '凭证错误'), ('inactive_account', '账号不可登录'), ('rate_limited', '登录受限'), ('service_unavailable', '认证服务不可用')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_status__in', ['active', 'cancel_pending']), ('is_active', True)), models.Q(('account_status__in', ['frozen', 'cancelled']), ('is_active', False)), _connector='OR'), name='user_account_status_active_consistent'),
        ),
        migrations.AddIndex(
            model_name='loginevent',
            index=models.Index(fields=['phone_fingerprint', 'created_at'], name='login_phone_created_idx'),
        ),
    ]
