# Generated by Django 5.2.16 on 2026-07-31 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loginevent_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UserStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_domain', models.CharField(choices=[('approval', '审核状态'), ('account', '账号状态')], max_length=16)),
                ('event_type', models.CharField(choices=[('approved', '审核通过'), ('rejected', '审核拒绝'), ('resubmitted', '重新提交'), ('frozen', '账号冻结'), ('unfrozen', '账号解冻')], max_length=16)),
                ('from_value', models.CharField(max_length=16)),
                ('to_value', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_status_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_status_events',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('approval_approved', '审核通过'), ('approval_rejected', '审核拒绝'), ('account_frozen', '账号冻结'), ('account_unfrozen', '账号解冻')], max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('safe_summary', models.CharField(max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_status_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.userstatusevent')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='userstatusevent',
            index=models.Index(fields=['user', 'created_at'], name='status_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userstatusevent',
            index=models.Index(fields=['status_domain', 'created_at'], name='status_domain_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userstatusevent',
            index=models.Index(fields=['event_type', 'created_at'], name='status_event_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='userstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_value__in', ['pending', 'approved', 'rejected']), ('status_domain', 'approval'), ('to_value__in', ['pending', 'approved', 'rejected'])), models.Q(('from_value__in', ['active', 'frozen', 'cancel_pending', 'cancelled']), ('status_domain', 'account'), ('to_value__in', ['active', 'frozen', 'cancel_pending', 'cancelled'])), _connector='OR'), name='status_event_domain_values_valid'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notification_user_created_idx'),
        ),
    ]
