# Generated by Django 5.2.16 on 2026-08-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_user_approved_by_user_session_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('status_version__gte', 1)), name='user_status_version_gte_1'),
        ),
    ]
