# Generated by Django 5.2.16 on 2026-08-01 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_planapplication_planapplicationevent_and_more'),
        ('users', '0004_user_status_version_user_user_status_version_gte_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_plan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='plans.planapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_approved', '审核通过'), ('approval_rejected', '审核拒绝'), ('account_frozen', '账号冻结'), ('account_unfrozen', '账号解冻'), ('plan_application_submitted', '套餐申请已提交'), ('plan_application_contacted', '套餐申请已联系'), ('plan_application_closed', '套餐申请已关闭'), ('plan_application_cancelled', '套餐申请已取消')], max_length=32),
        ),
    ]
