# Generated by Django 5.2.16 on 2026-08-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_subscription_subscriptionevent_and_more'),
        ('users', '0005_notification_related_plan_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='plans.subscription'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_approved', '审核通过'), ('approval_rejected', '审核拒绝'), ('account_frozen', '账号冻结'), ('account_unfrozen', '账号解冻'), ('plan_application_submitted', '套餐申请已提交'), ('plan_application_contacted', '套餐申请已联系'), ('plan_application_closed', '套餐申请已关闭'), ('plan_application_cancelled', '套餐申请已取消'), ('plan_application_activated', '套餐申请已开通'), ('subscription_trial_granted', '试用套餐已发放'), ('subscription_expired', '套餐已到期'), ('subscription_terminated', '套餐已终止')], max_length=32),
        ),
    ]
