# Generated by Django 5.2.16 on 2026-08-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_approved', '审核通过'), ('approval_rejected', '审核拒绝'), ('account_frozen', '账号冻结'), ('account_unfrozen', '账号解冻'), ('plan_application_submitted', '套餐申请已提交'), ('plan_application_contacted', '套餐申请已联系'), ('plan_application_closed', '套餐申请已关闭'), ('plan_application_cancelled', '套餐申请已取消'), ('plan_application_activated', '套餐申请已开通'), ('subscription_trial_granted', '试用套餐已发放'), ('subscription_expired', '套餐已到期'), ('subscription_terminated', '套餐已终止'), ('subscription_renewed', 'Subscription renewed'), ('subject_review_approved', '\u4e3b\u4f53\u8d44\u6599\u5ba1\u6838\u901a\u8fc7'), ('subject_review_rejected', '\u4e3b\u4f53\u8d44\u6599\u5ba1\u6838\u62d2\u7edd')], max_length=32),
        ),
    ]
