# Generated by Django 5.2.17 on 2026-08-22 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_TENANT_ID = uuid.UUID("00000000-0000-4000-8000-000000000001")


def backfill_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("users", "Tenant")
    User = apps.get_model("users", "User")
    Tenant.objects.update_or_create(
        id=DEFAULT_TENANT_ID,
        defaults={
            "key": "legacy-default",
            "display_name": "默认租户",
            "brand_name": "显问 GEO",
            "logo_reference": "",
            "status": "active",
        },
    )
    User.objects.filter(is_superuser=False, tenant__isnull=True).update(
        tenant_id=DEFAULT_TENANT_ID
    )


def clear_backfilled_tenant(apps, schema_editor):
    User = apps.get_model("users", "User")
    Tenant = apps.get_model("users", "Tenant")
    User.objects.filter(tenant_id=DEFAULT_TENANT_ID).update(tenant_id=None)
    Tenant.objects.filter(id=DEFAULT_TENANT_ID).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('logo_reference', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ('display_name', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='tenant_valid_status')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.tenant'),
        ),
        migrations.RunPython(backfill_default_tenant, clear_backfilled_tenant),
    ]
