# Generated by Django 5.2.17 on 2026-08-21 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_rbac', '0020_seed_api_credential_permission'),
        ('subjects', '0013_subject_enrichment_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=100)),
                ('location_reference', models.CharField(max_length=500)),
                ('encrypted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('verified', 'Verified'), ('failed', 'Failed')], default='planned', max_length=16)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('restore_verified_at', models.DateTimeField(blank=True, null=True)),
                ('safe_error_code', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RetentionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('safe_summary', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'retention_jobs',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerContactLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contacted_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('wechat', 'WeChat'), ('email', 'Email'), ('other', 'Other')], max_length=16)),
                ('content', models.CharField(max_length=4000)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_contact_logs', to='admin_rbac.adminprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_contact_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_contact_logs',
                'ordering': ('-contacted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('is_builtin', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_statuses',
                'ordering': ('sort_order', 'name', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='customer_status_ver_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_tags',
                'ordering': ('name', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='customer_tag_ver_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='SupportViewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=1000)),
                ('forced', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_view_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_view_requests', to='admin_rbac.adminprofile')),
            ],
            options={
                'db_table': 'support_view_requests',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportViewAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_key', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=32)),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='operations.supportviewrequest')),
            ],
            options={
                'db_table': 'support_view_audit_logs',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('important', 'Important'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('occurrences', models.PositiveBigIntegerField(default=1)),
                ('safe_summary', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_alerts',
                'ordering': ('status', '-last_seen_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('closed', 'Closed')], default='open', max_length=16)),
                ('admin_reply', models.TextField(blank=True, max_length=10000)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replied_feedback_entries', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feedback',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=20000)),
                ('audience', models.CharField(choices=[('all', 'All'), ('plan', 'Plan'), ('user', 'User')], default='all', max_length=16)),
                ('audience_keys', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ('-pinned', '-published_at', '-created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='announcement_ver_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='CustomerFollowup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField()),
                ('note', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_followups', to='admin_rbac.adminprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_followups', to=settings.AUTH_USER_MODEL)),
                ('source_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.customercontactlog')),
            ],
            options={
                'db_table': 'customer_followups',
                'ordering': ('status', 'due_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='customer_followup_ver_gte_1'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('completed_at__isnull', True), ('status__in', ('open', 'cancelled'))), _connector='OR'), name='customer_followup_completion_shape')],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('internal_note', models.CharField(blank=True, max_length=2000)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='operations.customerstatus')),
            ],
            options={
                'db_table': 'customer_profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='customer_profile_ver_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='CustomerTagLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_tags', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_tag_links', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_links', to='operations.customertag')),
            ],
            options={
                'db_table': 'customer_tag_links',
                'constraints': [models.UniqueConstraint(fields=('customer', 'tag'), name='customer_tag_link_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='supportviewrequest',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='support_view_ver_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='userfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='user_feedback_ver_gte_1'),
        ),
    ]
