# Generated by Django 5.2.17 on 2026-08-21 09:47

import uuid
from django.db import migrations, models


def create_postgresql_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE TRIGGER release_evidence_append_only
        BEFORE UPDATE OR DELETE ON release_evidence
        FOR EACH ROW EXECUTE FUNCTION operations_append_only_guard();
        """
    )


def drop_postgresql_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS release_evidence_append_only ON release_evidence;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_seed_statuses_and_postgresql_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=32)),
                ('evidence_key', models.CharField(max_length=100)),
                ('deploy_sha', models.CharField(max_length=40)),
                ('safe_summary', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'release_evidence',
                'ordering': ('-observed_at', '-id'),
                'indexes': [models.Index(fields=['environment', 'evidence_key', 'deploy_sha', 'expires_at'], name='release_evidence_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('observed_at'))), name='release_evidence_expiry_after_observed')],
            },
        ),
        migrations.RunPython(create_postgresql_guard, drop_postgresql_guard),
    ]
