from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_CREDENTIALS_INVALID = "AUTH_CREDENTIALS_INVALID"
    ACCOUNT_UNAVAILABLE = "ACCOUNT_UNAVAILABLE"
    ADMIN_LOGIN_REQUIRED = "ADMIN_LOGIN_REQUIRED"
    ADMIN_AUTH_CHALLENGE_INVALID = "ADMIN_AUTH_CHALLENGE_INVALID"
    ADMIN_AUTH_CHALLENGE_EXPIRED = "ADMIN_AUTH_CHALLENGE_EXPIRED"
    ADMIN_IP_NOT_ALLOWED = "ADMIN_IP_NOT_ALLOWED"
    ADMIN_REAUTH_FAILED = "ADMIN_REAUTH_FAILED"
    SECURITY_POLICY_VERSION_CONFLICT = "SECURITY_POLICY_VERSION_CONFLICT"
    IP_ALLOWLIST_LOCKOUT_CONFIRMATION_REQUIRED = "IP_ALLOWLIST_LOCKOUT_CONFIRMATION_REQUIRED"
    ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS"
    RISK_CONFIRMATION_REQUIRED = "RISK_CONFIRMATION_REQUIRED"
    RISK_POLICY_VERSION_CONFLICT = "RISK_POLICY_VERSION_CONFLICT"
    RISK_SECURITY_MODE_NOT_SUPPORTED = "RISK_SECURITY_MODE_NOT_SUPPORTED"
    RISK_SECURITY_MODE_BELOW_MINIMUM = "RISK_SECURITY_MODE_BELOW_MINIMUM"
    APPROVAL_SELF_NOT_ALLOWED = "APPROVAL_SELF_NOT_ALLOWED"
    APPROVAL_APPROVER_UNAVAILABLE = "APPROVAL_APPROVER_UNAVAILABLE"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_STALE = "APPROVAL_STALE"
    APPROVAL_PAYLOAD_INVALID = "APPROVAL_PAYLOAD_INVALID"
    APPROVAL_EXECUTION_FAILED = "APPROVAL_EXECUTION_FAILED"
    APPROVAL_STATE_CONFLICT = "APPROVAL_STATE_CONFLICT"
    ACCOUNT_STATE_CONFLICT = "ACCOUNT_STATE_CONFLICT"
    ADMIN_STATE_CONFLICT = "ADMIN_STATE_CONFLICT"
    ADMIN_VERSION_CONFLICT = "ADMIN_VERSION_CONFLICT"
    ADMIN_HAS_ASSIGNED_CUSTOMERS = "ADMIN_HAS_ASSIGNED_CUSTOMERS"
    LAST_SUPERUSER_PROTECTED = "LAST_SUPERUSER_PROTECTED"
    ROLE_VERSION_CONFLICT = "ROLE_VERSION_CONFLICT"
    ROLE_IN_USE = "ROLE_IN_USE"
    ASSIGNMENT_VERSION_CONFLICT = "ASSIGNMENT_VERSION_CONFLICT"
    APPROVAL_REASON_REQUIRED = "APPROVAL_REASON_REQUIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    CSRF_FAILED = "CSRF_FAILED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    INVALID_JSON = "INVALID_JSON"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    VERIFICATION_CODE_INVALID = "VERIFICATION_CODE_INVALID"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_TEMPORARILY_UNAVAILABLE = "SERVICE_TEMPORARILY_UNAVAILABLE"
    PLAN_STATE_CONFLICT = "PLAN_STATE_CONFLICT"
    PLAN_VERSION_STATE_CONFLICT = "PLAN_VERSION_STATE_CONFLICT"
    PLAN_VERSION_CONFLICT = "PLAN_VERSION_CONFLICT"
    PLAN_DRAFT_ALREADY_EXISTS = "PLAN_DRAFT_ALREADY_EXISTS"
    PLAN_LIMIT_INVALID = "PLAN_LIMIT_INVALID"
    PLAN_MODEL_PERMISSION_INVALID = "PLAN_MODEL_PERMISSION_INVALID"
    PLAN_PUBLISH_VALIDATION_FAILED = "PLAN_PUBLISH_VALIDATION_FAILED"
    PLAN_IMMUTABLE = "PLAN_IMMUTABLE"
    PLAN_APPLICATION_NOT_ELIGIBLE = "PLAN_APPLICATION_NOT_ELIGIBLE"
    PLAN_APPLICATION_PLAN_UNAVAILABLE = "PLAN_APPLICATION_PLAN_UNAVAILABLE"
    PLAN_APPLICATION_ALREADY_OPEN = "PLAN_APPLICATION_ALREADY_OPEN"
    PLAN_APPLICATION_STATE_CONFLICT = "PLAN_APPLICATION_STATE_CONFLICT"
    PLAN_APPLICATION_VERSION_CONFLICT = "PLAN_APPLICATION_VERSION_CONFLICT"
    PLAN_APPLICATION_VERSION_MISMATCH = "PLAN_APPLICATION_VERSION_MISMATCH"
    PLAN_APPLICATION_NOTE_INVALID = "PLAN_APPLICATION_NOTE_INVALID"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    SUBSCRIPTION_NOT_ELIGIBLE = "SUBSCRIPTION_NOT_ELIGIBLE"
    SUBSCRIPTION_ALREADY_ACTIVE = "SUBSCRIPTION_ALREADY_ACTIVE"
    SUBSCRIPTION_STATE_CONFLICT = "SUBSCRIPTION_STATE_CONFLICT"
    SUBSCRIPTION_VERSION_CONFLICT = "SUBSCRIPTION_VERSION_CONFLICT"
    SUBSCRIPTION_PLAN_UNAVAILABLE = "SUBSCRIPTION_PLAN_UNAVAILABLE"
    SUBSCRIPTION_PLAN_VERSION_MISMATCH = "SUBSCRIPTION_PLAN_VERSION_MISMATCH"
    SUBSCRIPTION_TRIAL_ALREADY_GRANTED = "SUBSCRIPTION_TRIAL_ALREADY_GRANTED"
    SUBSCRIPTION_CONFIRMATION_REQUIRED = "SUBSCRIPTION_CONFIRMATION_REQUIRED"
    SUBSCRIPTION_OVERRIDE_FORBIDDEN = "SUBSCRIPTION_OVERRIDE_FORBIDDEN"
    SUBSCRIPTION_NOTE_INVALID = "SUBSCRIPTION_NOTE_INVALID"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PLAN_APPLICATION_IMMUTABLE = "PLAN_APPLICATION_IMMUTABLE"
    QUOTA_STATE_CONFLICT = "QUOTA_STATE_CONFLICT"
    QUOTA_SNAPSHOT_INVALID = "QUOTA_SNAPSHOT_INVALID"
    QUOTA_INSUFFICIENT = "QUOTA_INSUFFICIENT"
    QUOTA_VERSION_CONFLICT = "QUOTA_VERSION_CONFLICT"
    QUOTA_HOLD_STATE_CONFLICT = "QUOTA_HOLD_STATE_CONFLICT"
    QUOTA_BUSINESS_ALREADY_HELD = "QUOTA_BUSINESS_ALREADY_HELD"
    SUBSCRIPTION_UNAVAILABLE = "SUBSCRIPTION_UNAVAILABLE"


ERROR_MESSAGES = {
    ErrorCode.AUTH_REQUIRED: "需要登录后访问",
    ErrorCode.AUTH_CREDENTIALS_INVALID: "认证凭证不正确",
    ErrorCode.ACCOUNT_UNAVAILABLE: "账号当前不可用",
    ErrorCode.ADMIN_LOGIN_REQUIRED: "请使用管理员登录入口",
    ErrorCode.ADMIN_AUTH_CHALLENGE_INVALID: "管理员登录验证已失效，请重新开始",
    ErrorCode.ADMIN_AUTH_CHALLENGE_EXPIRED: "管理员登录验证已过期，请重新开始",
    ErrorCode.ADMIN_IP_NOT_ALLOWED: "当前网络不允许访问后台",
    ErrorCode.ADMIN_REAUTH_FAILED: "当前密码验证失败",
    ErrorCode.SECURITY_POLICY_VERSION_CONFLICT: "安全策略已发生变化，请刷新后重试",
    ErrorCode.IP_ALLOWLIST_LOCKOUT_CONFIRMATION_REQUIRED: "新白名单将排除当前网络，请确认锁出风险",
    ErrorCode.ACCOUNT_ALREADY_EXISTS: "该手机号已注册，请登录或找回密码",
    ErrorCode.RISK_CONFIRMATION_REQUIRED: "请确认后再执行此高风险操作",
    ErrorCode.RISK_POLICY_VERSION_CONFLICT: "风险策略已发生变化，请刷新后重试",
    ErrorCode.RISK_SECURITY_MODE_NOT_SUPPORTED: "该动作不支持所选安全模式",
    ErrorCode.RISK_SECURITY_MODE_BELOW_MINIMUM: "安全模式不能低于目录最低要求",
    ErrorCode.APPROVAL_SELF_NOT_ALLOWED: "发起人不能审批自己的申请",
    ErrorCode.APPROVAL_APPROVER_UNAVAILABLE: "当前没有其他有效超级管理员可以审批",
    ErrorCode.APPROVAL_EXPIRED: "审批请求已过期，请重新发起",
    ErrorCode.APPROVAL_STALE: "审批目标或权限已变化，请重新发起",
    ErrorCode.APPROVAL_PAYLOAD_INVALID: "高风险操作参数不安全或已被修改",
    ErrorCode.APPROVAL_EXECUTION_FAILED: "高风险操作执行失败",
    ErrorCode.APPROVAL_STATE_CONFLICT: "当前审核状态不允许此操作",
    ErrorCode.ACCOUNT_STATE_CONFLICT: "当前账号状态不允许此操作",
    ErrorCode.ADMIN_STATE_CONFLICT: "当前管理员状态不允许此操作",
    ErrorCode.ADMIN_VERSION_CONFLICT: "管理员资料已发生变化，请刷新后重试",
    ErrorCode.ADMIN_HAS_ASSIGNED_CUSTOMERS: "管理员仍有负责客户，请先完成转交",
    ErrorCode.LAST_SUPERUSER_PROTECTED: "不能使最后一个有效超级管理员失效",
    ErrorCode.ROLE_VERSION_CONFLICT: "角色已发生变化，请刷新后重试",
    ErrorCode.ROLE_IN_USE: "角色仍在使用，不能停用",
    ErrorCode.ASSIGNMENT_VERSION_CONFLICT: "客户归属已发生变化，请刷新后重试",
    ErrorCode.APPROVAL_REASON_REQUIRED: "拒绝审核时必须填写原因",
    ErrorCode.PERMISSION_DENIED: "没有权限执行此操作",
    ErrorCode.CSRF_FAILED: "CSRF 验证失败",
    ErrorCode.RESOURCE_NOT_FOUND: "请求的资源不存在",
    ErrorCode.METHOD_NOT_ALLOWED: "请求方法不允许",
    ErrorCode.INVALID_JSON: "请求 JSON 格式不正确",
    ErrorCode.VALIDATION_ERROR: "请求参数不正确",
    ErrorCode.VERIFICATION_CODE_INVALID: "短信验证码不正确或已失效",
    ErrorCode.RATE_LIMITED: "请求过于频繁，请稍后再试",
    ErrorCode.INTERNAL_ERROR: "服务器内部错误",
    ErrorCode.SERVICE_TEMPORARILY_UNAVAILABLE: "服务暂时不可用",
    ErrorCode.PLAN_STATE_CONFLICT: "当前套餐状态不允许此操作",
    ErrorCode.PLAN_VERSION_STATE_CONFLICT: "当前套餐版本状态不允许此操作",
    ErrorCode.PLAN_VERSION_CONFLICT: "套餐版本已发生变化，请刷新后重试",
    ErrorCode.PLAN_DRAFT_ALREADY_EXISTS: "该套餐已存在草稿版本",
    ErrorCode.PLAN_LIMIT_INVALID: "套餐限制值不符合目录规则",
    ErrorCode.PLAN_MODEL_PERMISSION_INVALID: "套餐模型权限配置不正确",
    ErrorCode.PLAN_PUBLISH_VALIDATION_FAILED: "套餐版本未通过发布校验",
    ErrorCode.PLAN_IMMUTABLE: "已发布或已退役的套餐版本不可修改",
    ErrorCode.PLAN_APPLICATION_NOT_ELIGIBLE: "当前账号或套餐不能提交申请",
    ErrorCode.PLAN_APPLICATION_PLAN_UNAVAILABLE: "当前套餐暂不可申请",
    ErrorCode.PLAN_APPLICATION_ALREADY_OPEN: "该套餐已有待处理申请",
    ErrorCode.PLAN_APPLICATION_STATE_CONFLICT: "当前申请状态不允许此操作",
    ErrorCode.PLAN_APPLICATION_VERSION_CONFLICT: "套餐申请已发生变化，请刷新后重试",
    ErrorCode.PLAN_APPLICATION_VERSION_MISMATCH: "套餐公开版本已变化，请刷新后重试",
    ErrorCode.PLAN_APPLICATION_NOTE_INVALID: "申请备注不符合要求",
    ErrorCode.IDEMPOTENCY_KEY_REQUIRED: "必须提供有效的幂等键",
    ErrorCode.IDEMPOTENCY_CONFLICT: "幂等键对应的请求内容不一致",
    ErrorCode.SUBSCRIPTION_NOT_ELIGIBLE: "当前用户不符合开通订阅条件",
    ErrorCode.SUBSCRIPTION_ALREADY_ACTIVE: "当前用户已有生效中的订阅",
    ErrorCode.SUBSCRIPTION_STATE_CONFLICT: "当前订阅状态不允许此操作",
    ErrorCode.SUBSCRIPTION_VERSION_CONFLICT: "订阅或目标记录已发生变化，请刷新后重试",
    ErrorCode.SUBSCRIPTION_PLAN_UNAVAILABLE: "当前套餐不能用于开通订阅",
    ErrorCode.SUBSCRIPTION_PLAN_VERSION_MISMATCH: "套餐版本不符合开通要求",
    ErrorCode.SUBSCRIPTION_TRIAL_ALREADY_GRANTED: "该用户已经领取过试用套餐",
    ErrorCode.SUBSCRIPTION_CONFIRMATION_REQUIRED: "当前套餐状态需要额外确认并填写原因",
    ErrorCode.SUBSCRIPTION_OVERRIDE_FORBIDDEN: "没有权限替换申请绑定的套餐版本",
    ErrorCode.SUBSCRIPTION_NOTE_INVALID: "订阅备注或原因不符合要求",
    ErrorCode.PLAN_APPLICATION_IMMUTABLE: "套餐申请绑定信息不可修改",
    ErrorCode.QUOTA_STATE_CONFLICT: (
        "\u5f53\u524d\u989d\u5ea6\u72b6\u6001\u4e0d\u5141\u8bb8\u6b64\u64cd\u4f5c"
    ),
    ErrorCode.QUOTA_SNAPSHOT_INVALID: "\u8ba2\u9605\u989d\u5ea6\u5feb\u7167\u4e0d\u6b63\u786e",
    ErrorCode.QUOTA_INSUFFICIENT: "\u53ef\u7528\u989d\u5ea6\u4e0d\u8db3",
    ErrorCode.QUOTA_VERSION_CONFLICT: (
        "\u989d\u5ea6\u8d26\u6237\u5df2\u53d8\u5316\uff0c\u8bf7\u5237\u65b0\u540e\u91cd\u8bd5"
    ),
    ErrorCode.QUOTA_HOLD_STATE_CONFLICT: (
        "\u989d\u5ea6\u51bb\u7ed3\u72b6\u6001\u4e0d\u5141\u8bb8\u6b64\u64cd\u4f5c"
    ),
    ErrorCode.QUOTA_BUSINESS_ALREADY_HELD: (
        "\u8be5\u4e1a\u52a1\u76ee\u6807\u5df2\u7ecf\u51bb\u7ed3\u989d\u5ea6"
    ),
    ErrorCode.SUBSCRIPTION_UNAVAILABLE: (
        "\u5f53\u524d\u8ba2\u9605\u4e0d\u80fd\u4f7f\u7528\u989d\u5ea6"
    ),
}
