from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_CREDENTIALS_INVALID = "AUTH_CREDENTIALS_INVALID"
    ACCOUNT_UNAVAILABLE = "ACCOUNT_UNAVAILABLE"
    ADMIN_LOGIN_REQUIRED = "ADMIN_LOGIN_REQUIRED"
    ADMIN_AUTH_CHALLENGE_INVALID = "ADMIN_AUTH_CHALLENGE_INVALID"
    ADMIN_AUTH_CHALLENGE_EXPIRED = "ADMIN_AUTH_CHALLENGE_EXPIRED"
    ADMIN_IP_NOT_ALLOWED = "ADMIN_IP_NOT_ALLOWED"
    ADMIN_REAUTH_FAILED = "ADMIN_REAUTH_FAILED"
    SECURITY_POLICY_VERSION_CONFLICT = "SECURITY_POLICY_VERSION_CONFLICT"
    IP_ALLOWLIST_LOCKOUT_CONFIRMATION_REQUIRED = "IP_ALLOWLIST_LOCKOUT_CONFIRMATION_REQUIRED"
    ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS"
    RISK_CONFIRMATION_REQUIRED = "RISK_CONFIRMATION_REQUIRED"
    RISK_POLICY_VERSION_CONFLICT = "RISK_POLICY_VERSION_CONFLICT"
    RISK_SECURITY_MODE_NOT_SUPPORTED = "RISK_SECURITY_MODE_NOT_SUPPORTED"
    RISK_SECURITY_MODE_BELOW_MINIMUM = "RISK_SECURITY_MODE_BELOW_MINIMUM"
    APPROVAL_SELF_NOT_ALLOWED = "APPROVAL_SELF_NOT_ALLOWED"
    APPROVAL_APPROVER_UNAVAILABLE = "APPROVAL_APPROVER_UNAVAILABLE"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_STALE = "APPROVAL_STALE"
    APPROVAL_PAYLOAD_INVALID = "APPROVAL_PAYLOAD_INVALID"
    APPROVAL_EXECUTION_FAILED = "APPROVAL_EXECUTION_FAILED"
    APPROVAL_STATE_CONFLICT = "APPROVAL_STATE_CONFLICT"
    ACCOUNT_STATE_CONFLICT = "ACCOUNT_STATE_CONFLICT"
    ADMIN_STATE_CONFLICT = "ADMIN_STATE_CONFLICT"
    ADMIN_VERSION_CONFLICT = "ADMIN_VERSION_CONFLICT"
    ADMIN_HAS_ASSIGNED_CUSTOMERS = "ADMIN_HAS_ASSIGNED_CUSTOMERS"
    LAST_SUPERUSER_PROTECTED = "LAST_SUPERUSER_PROTECTED"
    ROLE_VERSION_CONFLICT = "ROLE_VERSION_CONFLICT"
    ROLE_IN_USE = "ROLE_IN_USE"
    ASSIGNMENT_VERSION_CONFLICT = "ASSIGNMENT_VERSION_CONFLICT"
    APPROVAL_REASON_REQUIRED = "APPROVAL_REASON_REQUIRED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    CSRF_FAILED = "CSRF_FAILED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    INVALID_JSON = "INVALID_JSON"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    VERIFICATION_CODE_INVALID = "VERIFICATION_CODE_INVALID"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_TEMPORARILY_UNAVAILABLE = "SERVICE_TEMPORARILY_UNAVAILABLE"


ERROR_MESSAGES = {
    ErrorCode.AUTH_REQUIRED: "需要登录后访问",
    ErrorCode.AUTH_CREDENTIALS_INVALID: "认证凭证不正确",
    ErrorCode.ACCOUNT_UNAVAILABLE: "账号当前不可用",
    ErrorCode.ADMIN_LOGIN_REQUIRED: "请使用管理员登录入口",
    ErrorCode.ADMIN_AUTH_CHALLENGE_INVALID: "管理员登录验证已失效，请重新开始",
    ErrorCode.ADMIN_AUTH_CHALLENGE_EXPIRED: "管理员登录验证已过期，请重新开始",
    ErrorCode.ADMIN_IP_NOT_ALLOWED: "当前网络不允许访问后台",
    ErrorCode.ADMIN_REAUTH_FAILED: "当前密码验证失败",
    ErrorCode.SECURITY_POLICY_VERSION_CONFLICT: "安全策略已发生变化，请刷新后重试",
    ErrorCode.IP_ALLOWLIST_LOCKOUT_CONFIRMATION_REQUIRED: "新白名单将排除当前网络，请确认锁出风险",
    ErrorCode.ACCOUNT_ALREADY_EXISTS: "该手机号已注册，请登录或找回密码",
    ErrorCode.RISK_CONFIRMATION_REQUIRED: "请确认后再执行此高风险操作",
    ErrorCode.RISK_POLICY_VERSION_CONFLICT: "风险策略已发生变化，请刷新后重试",
    ErrorCode.RISK_SECURITY_MODE_NOT_SUPPORTED: "该动作不支持所选安全模式",
    ErrorCode.RISK_SECURITY_MODE_BELOW_MINIMUM: "安全模式不能低于目录最低要求",
    ErrorCode.APPROVAL_SELF_NOT_ALLOWED: "发起人不能审批自己的申请",
    ErrorCode.APPROVAL_APPROVER_UNAVAILABLE: "当前没有其他有效超级管理员可以审批",
    ErrorCode.APPROVAL_EXPIRED: "审批请求已过期，请重新发起",
    ErrorCode.APPROVAL_STALE: "审批目标或权限已变化，请重新发起",
    ErrorCode.APPROVAL_PAYLOAD_INVALID: "高风险操作参数不安全或已被修改",
    ErrorCode.APPROVAL_EXECUTION_FAILED: "高风险操作执行失败",
    ErrorCode.APPROVAL_STATE_CONFLICT: "当前审核状态不允许此操作",
    ErrorCode.ACCOUNT_STATE_CONFLICT: "当前账号状态不允许此操作",
    ErrorCode.ADMIN_STATE_CONFLICT: "当前管理员状态不允许此操作",
    ErrorCode.ADMIN_VERSION_CONFLICT: "管理员资料已发生变化，请刷新后重试",
    ErrorCode.ADMIN_HAS_ASSIGNED_CUSTOMERS: "管理员仍有负责客户，请先完成转交",
    ErrorCode.LAST_SUPERUSER_PROTECTED: "不能使最后一个有效超级管理员失效",
    ErrorCode.ROLE_VERSION_CONFLICT: "角色已发生变化，请刷新后重试",
    ErrorCode.ROLE_IN_USE: "角色仍在使用，不能停用",
    ErrorCode.ASSIGNMENT_VERSION_CONFLICT: "客户归属已发生变化，请刷新后重试",
    ErrorCode.APPROVAL_REASON_REQUIRED: "拒绝审核时必须填写原因",
    ErrorCode.PERMISSION_DENIED: "没有权限执行此操作",
    ErrorCode.CSRF_FAILED: "CSRF 验证失败",
    ErrorCode.RESOURCE_NOT_FOUND: "请求的资源不存在",
    ErrorCode.METHOD_NOT_ALLOWED: "请求方法不允许",
    ErrorCode.INVALID_JSON: "请求 JSON 格式不正确",
    ErrorCode.VALIDATION_ERROR: "请求参数不正确",
    ErrorCode.VERIFICATION_CODE_INVALID: "短信验证码不正确或已失效",
    ErrorCode.RATE_LIMITED: "请求过于频繁，请稍后再试",
    ErrorCode.INTERNAL_ERROR: "服务器内部错误",
    ErrorCode.SERVICE_TEMPORARILY_UNAVAILABLE: "服务暂时不可用",
}
