# Generated by Django 5.2.16 on 2026-08-01 05:57

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_display_mode', models.CharField(choices=[('fixed', '固定展示价格'), ('contact', '联系开通')], default='contact', max_length=16)),
                ('display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('display_currency', models.CharField(default='CNY', editable=False, max_length=3)),
                ('is_trial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已上架'), ('offline', '已下架'), ('archived', '已归档')], default='draft', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ('sort_order', 'code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanLimitDefinition',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('value_type', models.CharField(choices=[('integer', '整数'), ('boolean', '布尔'), ('text', '文本'), ('enum', '枚举'), ('json', 'JSON')], max_length=16)),
                ('storage_kind', models.CharField(choices=[('plan_limit', '限制值表'), ('plan_version_field', '版本字段'), ('model_permissions', '模型权限表')], max_length=32)),
                ('scope', models.CharField(max_length=32)),
                ('quota_type', models.CharField(blank=True, max_length=100)),
                ('minimum', models.BigIntegerField(blank=True, null=True)),
                ('maximum', models.BigIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('enum_values', models.JSONField(default=list)),
                ('json_schema', models.JSONField(default=dict)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('catalog_version', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('semantic_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plan_limit_definitions',
                'ordering': ('sort_order', 'key'),
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='plan_limit_definition_status'), models.CheckConstraint(condition=models.Q(('catalog_version__gte', 1)), name='plan_limit_catalog_version_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('retired', '已退役')], default='draft', max_length=16)),
                ('valid_days', models.PositiveBigIntegerField()),
                ('queue_priority', models.PositiveIntegerField()),
                ('effective_config', models.JSONField(blank=True, null=True)),
                ('config_digest', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('snapshot_generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='plans.plan')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_plan_versions', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_plan_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plan_versions',
                'ordering': ('plan_id', '-version_no', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PlanModelPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_key', models.CharField(max_length=32)),
                ('sort_order', models.PositiveIntegerField()),
                ('selected_by_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_permissions', to='plans.planversion')),
            ],
            options={
                'db_table': 'plan_model_permissions',
                'ordering': ('sort_order', 'model_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit_key', models.CharField(max_length=100)),
                ('value_type', models.CharField(max_length=16)),
                ('integer_value', models.BigIntegerField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_limits', to='plans.planlimitdefinition')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='plans.planversion')),
            ],
            options={
                'db_table': 'plan_limits',
                'ordering': ('limit_key', 'id'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='current_published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plans.planversion'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_no'), name='plan_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('plan',), name='plan_single_draft'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('plan',), name='plan_single_published'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'published', 'retired'))), name='plan_version_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='plan_version_no_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_days__gte', 1)), name='plan_valid_days_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('queue_priority__gte', 0), ('queue_priority__lte', 1000)), name='plan_queue_priority_range'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='plan_draft_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('config_digest', ''), ('effective_config__isnull', True), ('snapshot_generated_at__isnull', True), ('status', 'draft')), models.Q(models.Q(('effective_config__isnull', False), ('snapshot_generated_at__isnull', False), ('status__in', ('published', 'retired'))), models.Q(('config_digest', ''), _negated=True)), _connector='OR'), name='plan_version_snapshot_by_status'),
        ),
        migrations.AddConstraint(
            model_name='planmodelpermission',
            constraint=models.UniqueConstraint(fields=('plan_version', 'model_key'), name='plan_model_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='planmodelpermission',
            constraint=models.UniqueConstraint(fields=('plan_version', 'sort_order'), name='plan_model_sort_unique'),
        ),
        migrations.AddConstraint(
            model_name='planmodelpermission',
            constraint=models.CheckConstraint(condition=models.Q(('model_key__in', ('deepseek', 'doubao', 'qwen', 'hunyuan', 'wenxin', 'kimi', 'glm', 'spark'))), name='plan_model_key_valid'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(fields=('plan_version', 'limit_definition'), name='plan_limit_definition_unique'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(fields=('plan_version', 'limit_key'), name='plan_limit_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('boolean_value__isnull', True), ('integer_value__isnull', False), ('json_value__isnull', True), ('text_value__isnull', True), ('value_type', 'integer')), models.Q(('boolean_value__isnull', False), ('integer_value__isnull', True), ('json_value__isnull', True), ('text_value__isnull', True), ('value_type', 'boolean')), models.Q(('boolean_value__isnull', True), ('integer_value__isnull', True), ('json_value__isnull', True), ('text_value__isnull', False), ('value_type__in', ('text', 'enum'))), models.Q(('boolean_value__isnull', True), ('integer_value__isnull', True), ('json_value__isnull', False), ('text_value__isnull', True), ('value_type', 'json')), _connector='OR'), name='plan_limit_exact_typed_value'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status', 'sort_order', 'id'], name='plan_public_list_idx'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='plan_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'published', 'offline', 'archived'))), name='plan_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('price_display_mode__in', ('fixed', 'contact'))), name='plan_valid_price_mode'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('display_currency', 'CNY')), name='plan_currency_cny'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('display_price__gte', 0), ('display_price__isnull', False), ('price_display_mode', 'fixed')), models.Q(('display_price__isnull', True), ('price_display_mode', 'contact')), _connector='OR'), name='plan_price_mode_value'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='plan_version_gte_1'),
        ),
    ]
