# Generated by Django 5.2.16 on 2026-08-01 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_postgresql_immutability_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_version_no', models.PositiveBigIntegerField()),
                ('requested_config_digest', models.CharField(max_length=64)),
                ('public_plan_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('closed', '已关闭'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('source', models.CharField(choices=[('user_web', '用户网页')], default='user_web', max_length=16)),
                ('user_note', models.CharField(blank=True, max_length=500)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_applications', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_plan_applications', to=settings.AUTH_USER_MODEL)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_plan_applications', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='plans.plan')),
                ('requested_plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='plans.planversion')),
            ],
            options={
                'db_table': 'plan_applications',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PlanApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('submitted', '已提交'), ('contacted', '已联系'), ('closed', '已关闭'), ('cancelled', '已取消')], max_length=16)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('closed', '已关闭'), ('cancelled', '已取消')], max_length=16)),
                ('safe_summary', models.CharField(max_length=200)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_application_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='plans.planapplication')),
            ],
            options={
                'db_table': 'plan_application_events',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='planapplication',
            index=models.Index(fields=['applicant', 'status', 'created_at'], name='plan_app_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='planapplication',
            index=models.Index(fields=['plan', 'status', 'created_at'], name='plan_app_plan_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'idempotency_key_digest'), name='plan_app_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'contacted'))), fields=('applicant', 'plan'), name='plan_app_single_open'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'contacted', 'closed', 'cancelled'))), name='plan_app_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'user_web')), name='plan_app_valid_source'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='plan_app_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requested_config_digest', ''), _negated=True), models.Q(('idempotency_key_digest', ''), _negated=True), models.Q(('request_digest', ''), _negated=True)), name='plan_app_digests_present'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('closed_at__isnull', True), ('contacted_at__isnull', True), ('status', 'pending')), models.Q(('cancelled_at__isnull', True), ('closed_at__isnull', True), ('contacted_at__isnull', False), ('status', 'contacted')), models.Q(('cancelled_at__isnull', True), ('closed_at__isnull', False), ('status', 'closed')), models.Q(('cancelled_at__isnull', False), ('closed_at__isnull', True), ('status', 'cancelled')), _connector='OR'), name='plan_app_status_times'),
        ),
        migrations.AddIndex(
            model_name='planapplicationevent',
            index=models.Index(fields=['application', 'created_at'], name='plan_app_event_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='planapplicationevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('submitted', 'contacted', 'closed', 'cancelled'))), name='plan_app_event_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='planapplicationevent',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ('pending', 'contacted', 'closed', 'cancelled'))), name='plan_app_event_valid_status'),
        ),
    ]
