# Generated by Django 5.2.16 on 2026-08-01 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_plan_application_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_version_no', models.PositiveBigIntegerField()),
                ('entitlement_snapshot', models.JSONField()),
                ('entitlement_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', '生效中'), ('expired', '已到期'), ('terminated', '已终止')], default='active', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('cycle_anchor_day', models.PositiveSmallIntegerField()),
                ('is_trial', models.BooleanField()),
                ('opening_note', models.CharField(blank=True, max_length=500)),
                ('activated_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('activated', '已生效'), ('expired', '已到期'), ('terminated', '已终止')], max_length=16)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('active', '生效中'), ('expired', '已到期'), ('terminated', '已终止')], max_length=16)),
                ('safe_summary', models.CharField(max_length=200)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_events',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='planapplication',
            name='plan_app_valid_status',
        ),
        migrations.RemoveConstraint(
            model_name='planapplication',
            name='plan_app_status_times',
        ),
        migrations.RemoveConstraint(
            model_name='planapplicationevent',
            name='plan_app_event_valid_type',
        ),
        migrations.RemoveConstraint(
            model_name='planapplicationevent',
            name='plan_app_event_valid_status',
        ),
        migrations.AddField(
            model_name='planapplication',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planapplication',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_plan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('closed', '已关闭'), ('cancelled', '已取消'), ('activated', '已开通')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='planapplicationevent',
            name='event_type',
            field=models.CharField(choices=[('submitted', '已提交'), ('contacted', '已联系'), ('closed', '已关闭'), ('cancelled', '已取消'), ('activated', '已开通')], max_length=16),
        ),
        migrations.AlterField(
            model_name='planapplicationevent',
            name='to_status',
            field=models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('closed', '已关闭'), ('cancelled', '已取消'), ('activated', '已开通')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'contacted', 'closed', 'cancelled', 'activated'))), name='plan_app_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='planapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', True), ('cancelled_at__isnull', True), ('closed_at__isnull', True), ('contacted_at__isnull', True), ('status', 'pending')), models.Q(('activated_at__isnull', True), ('cancelled_at__isnull', True), ('closed_at__isnull', True), ('contacted_at__isnull', False), ('status', 'contacted')), models.Q(('activated_at__isnull', True), ('cancelled_at__isnull', True), ('closed_at__isnull', False), ('status', 'closed')), models.Q(('activated_at__isnull', True), ('cancelled_at__isnull', False), ('closed_at__isnull', True), ('status', 'cancelled')), models.Q(('activated_at__isnull', False), ('cancelled_at__isnull', True), ('closed_at__isnull', True), ('status', 'activated')), _connector='OR'), name='plan_app_status_times'),
        ),
        migrations.AddConstraint(
            model_name='planapplicationevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('submitted', 'contacted', 'closed', 'cancelled', 'activated'))), name='plan_app_event_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='planapplicationevent',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ('pending', 'contacted', 'closed', 'cancelled', 'activated'))), name='plan_app_event_valid_status'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.planversion'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='source_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='plans.planapplication'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='plans.subscription'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'created_at'], name='subscription_user_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'ends_at'], name='subscription_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status', 'created_at'], name='subscription_plan_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='subscription_single_active'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_trial', True)), fields=('user',), name='subscription_single_trial_history'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'expired', 'terminated'))), name='subscription_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='subscription_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_anchor_day__gte', 1), ('cycle_anchor_day__lte', 31)), name='subscription_anchor_range'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subscription_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('entitlement_digest', ''), _negated=True), name='subscription_digest_present'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_trial', True), ('source_application__isnull', True)), models.Q(('is_trial', False), ('source_application__isnull', False)), _connector='OR'), name='subscription_source_by_trial'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expired_at__isnull', True), ('status', 'active'), ('terminated_at__isnull', True), ('termination_reason', '')), models.Q(('expired_at__isnull', False), ('status', 'expired'), ('terminated_at__isnull', True), ('termination_reason', '')), models.Q(('expired_at__isnull', True), ('status', 'terminated'), ('terminated_at__isnull', False), ('terminated_by__isnull', False), ('termination_reason__gt', '')), _connector='OR'), name='subscription_status_times'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['subscription', 'created_at'], name='subscription_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('activated', 'expired', 'terminated'))), name='subscription_event_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionevent',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ('active', 'expired', 'terminated'))), name='subscription_event_valid_status'),
        ),
    ]
