# Generated by Django 5.2.16 on 2026-08-02 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

def backfill_subscription_sources(apps, schema_editor):
    Subscription = apps.get_model("plans", "Subscription")
    Subscription.objects.filter(is_trial=True).update(source_type="trial_grant")
    Subscription.objects.filter(is_trial=False).update(source_type="application")




class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_subscription_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_plan_version_no', models.PositiveBigIntegerField()),
                ('target_entitlement_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('scheduled', '已排期'), ('executed', '已执行'), ('cancelled', '已取消')], max_length=16)),
                ('change_type', models.CharField(choices=[('renewal', '续费'), ('upgrade', '升级'), ('downgrade', '降级'), ('replacement', '替换'), ('trial_conversion', '试用转正式')], max_length=24)),
                ('quota_policy', models.CharField(choices=[('overwrite', '覆盖'), ('accumulate', '累加'), ('retain', '保留')], max_length=16)),
                ('effective_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=500)),
                ('unavailable_reason', models.CharField(blank=True, max_length=500)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('idempotency_scope_digest', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_changes',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('scheduled', '已排期'), ('executed', '已执行'), ('cancelled', '已取消')], max_length=16)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('scheduled', '已排期'), ('executed', '已执行'), ('cancelled', '已取消')], max_length=16)),
                ('safe_summary', models.CharField(max_length=200)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_change_events',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscription_source_by_trial',
        ),
        migrations.AddField(
            model_name='subscription',
            name='source_type',
            field=models.CharField(choices=[('application', '套餐申请'), ('trial_grant', '试用发放'), ('plan_change', '套餐变更')], default='application', max_length=16),
        ),
        migrations.RunPython(backfill_subscription_sources, migrations.RunPython.noop),
        migrations.AddField(
            model_name='subscriptionchange',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_subscription_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='from_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_changes', to='plans.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_subscription_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='target_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_changes', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='target_plan_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_changes', to='plans.planversion'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='source_change',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_subscription', to='plans.subscriptionchange'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ('application', 'trial_grant', 'plan_change'))), name='subscription_source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_trial', False), ('source_application__isnull', False), ('source_change__isnull', True), ('source_type', 'application')), models.Q(('is_trial', True), ('source_application__isnull', True), ('source_change__isnull', True), ('source_type', 'trial_grant')), models.Q(('is_trial', False), ('source_application__isnull', True), ('source_change__isnull', False), ('source_type', 'plan_change')), _connector='OR'), name='subscription_source_consistent'),
        ),
        migrations.AddField(
            model_name='subscriptionchangeevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_change_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionchangeevent',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='plans.subscriptionchange'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchange',
            index=models.Index(fields=['user', 'created_at'], name='sub_change_user_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchange',
            index=models.Index(fields=['status', 'effective_at'], name='sub_change_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('scheduled', 'executed'))), fields=('from_subscription',), name='sub_change_single_successor'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('scheduled', 'executed', 'cancelled'))), name='sub_change_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(('change_type__in', ('renewal', 'upgrade', 'downgrade', 'replacement', 'trial_conversion'))), name='sub_change_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(('quota_policy__in', ('overwrite', 'accumulate', 'retain'))), name='sub_change_quota_policy_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('change_type', 'renewal'), ('executed_at__isnull', True), ('status', 'scheduled')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('executed_at__isnull', False), ('status', 'executed')), models.Q(('cancellation_reason__gt', ''), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('change_type', 'renewal'), ('executed_at__isnull', True), ('status', 'cancelled')), _connector='OR'), name='sub_change_status_times'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_entitlement_digest', ''), _negated=True), models.Q(('idempotency_key_digest', ''), _negated=True), models.Q(('idempotency_scope_digest', ''), _negated=True), models.Q(('request_digest', ''), _negated=True), ('version__gte', 1)), name='sub_change_digests_version'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('scheduled', 'executed', 'cancelled'))), name='sub_change_event_type_valid'),
        ),
    ]
