# Generated by Django 5.2.16 on 2026-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_subscriptionchange_subscriptionchangeevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionchange',
            name='cancellation_idempotency_key_digest',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='cancellation_idempotency_key_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='cancellation_idempotency_scope_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='cancellation_request_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
