# Generated by Django 5.2.16 on 2026-08-02 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_subscription_change_cancel_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('scheduled', 'executed')), ('cancellation_idempotency_key_version__isnull', True), ('cancellation_idempotency_key_digest__isnull', True), ('cancellation_idempotency_scope_digest', ''), ('cancellation_request_digest', '')), models.Q(('status', 'cancelled'), ('cancellation_idempotency_key_version__isnull', False), ('cancellation_idempotency_key_digest__isnull', False), models.Q(('cancellation_idempotency_scope_digest', ''), _negated=True), models.Q(('cancellation_request_digest', ''), _negated=True)), _connector='OR'), name='sub_change_cancel_idem_state'),
        ),
    ]
