# Generated by Django 5.2.16 on 2026-08-03 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_lifecycle_fields(apps, schema_editor):
    from zoneinfo import ZoneInfo

    Subscription = apps.get_model("plans", "Subscription")
    SubscriptionChange = apps.get_model("plans", "SubscriptionChange")
    ApprovalRequest = apps.get_model("admin_rbac", "ApprovalRequest")
    shanghai = ZoneInfo("Asia/Shanghai")
    for subscription in Subscription.objects.only("pk", "starts_at").iterator():
        local_time = subscription.starts_at.astimezone(shanghai).timetz().replace(tzinfo=None)
        Subscription.objects.filter(pk=subscription.pk).update(cycle_anchor_time=local_time)
    SubscriptionChange.objects.filter(status="scheduled", next_attempt_at__isnull=True).update(
        next_attempt_at=models.F("effective_at")
    )
    for approval in ApprovalRequest.objects.filter(
        action_key="subscription.change", status="executed"
    ).only("pk", "execution_result").iterator():
        change_id = (approval.execution_result or {}).get("change_id")
        if change_id:
            SubscriptionChange.objects.filter(pk=change_id, source_approval__isnull=True).update(
                source_approval_id=approval.pk
            )


def reverse_backfill(apps, schema_editor):
    # Lifecycle facts and approval links are evidence and are intentionally retained.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rbac', '0015_approvalrequest_approval_single_pending_subscription_cancel'),
        ('plans', '0011_plan_change_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionchange',
            name='sub_change_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionchange',
            name='sub_change_status_times',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionchange',
            name='sub_change_cancel_idem_state',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionchangeevent',
            name='sub_change_event_type_valid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cycle_anchor_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='source_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscription_change', to='admin_rbac.approvalrequest'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='stable_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_lifecycle_fields, reverse_backfill),
        migrations.AlterField(
            model_name='subscription',
            name='cycle_anchor_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptionchange',
            name='status',
            field=models.CharField(choices=[('scheduled', '已排期'), ('executed', '已执行'), ('cancelled', '已取消'), ('failed', 'Failed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriptionchangeevent',
            name='event_type',
            field=models.CharField(choices=[('scheduled', '已排期'), ('executed', '已执行'), ('cancelled', '已取消'), ('failed', 'Failed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriptionchangeevent',
            name='to_status',
            field=models.CharField(choices=[('scheduled', '已排期'), ('executed', '已执行'), ('cancelled', '已取消'), ('failed', 'Failed')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('scheduled', 'executed', 'cancelled', 'failed'))), name='sub_change_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('change_type', 'renewal'), ('executed_at__isnull', True), ('failed_at__isnull', True), ('status', 'scheduled')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('executed_at__isnull', False), ('failed_at__isnull', True), ('stable_error_code', ''), ('status', 'executed')), models.Q(('cancellation_reason__gt', ''), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('change_type', 'renewal'), ('executed_at__isnull', True), ('failed_at__isnull', True), ('stable_error_code', ''), ('status', 'cancelled')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('change_type', 'renewal'), ('executed_at__isnull', True), ('failed_at__isnull', False), ('stable_error_code__gt', ''), ('status', 'failed')), _connector='OR'), name='sub_change_status_times'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('scheduled', 'executed', 'failed')), ('cancellation_idempotency_key_version__isnull', True), ('cancellation_idempotency_key_digest__isnull', True), ('cancellation_idempotency_scope_digest', ''), ('cancellation_request_digest', '')), models.Q(('status', 'cancelled'), ('cancellation_idempotency_key_version__isnull', False), ('cancellation_idempotency_key_digest__isnull', False), models.Q(('cancellation_idempotency_scope_digest', ''), _negated=True), models.Q(('cancellation_request_digest', ''), _negated=True)), _connector='OR'), name='sub_change_cancel_idem_state'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchange',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('next_attempt_at__isnull', False), ('status', 'scheduled')), models.Q(('status', 'scheduled'), _negated=True), _connector='OR'), name='sub_change_retry_schedule'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('scheduled', 'executed', 'cancelled', 'failed'))), name='sub_change_event_type_valid'),
        ),
    ]
