# Generated by Django 5.2.17 on 2026-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_add_video_credit_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
