# Generated by Django 5.2.16 on 2026-08-13 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0011_catalog_publish_binding_and_review_boundaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSourceImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_url', models.TextField()),
                ('display_url', models.CharField(max_length=4096)),
                ('has_query', models.BooleanField(default=False)),
                ('hostname_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetching', 'Fetching'), ('retry_wait', 'Retry wait'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('version', models.BigIntegerField(default=1)),
                ('idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('generation', models.UUIDField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_source_imports', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_source_imports',
            },
        ),
        migrations.CreateModel(
            name='WebSourceParsedVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('machine', 'Machine'), ('user_confirmation', 'User confirmation')], max_length=24)),
                ('canonical_text', models.TextField()),
                ('content_digest', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_web_source_versions', to=settings.AUTH_USER_MODEL)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parsed_versions', to='web_sources.websourceimport')),
                ('machine_base_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='web_sources.websourceparsedversion')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='web_sources.websourceparsedversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_source_parsed_versions',
            },
        ),
        migrations.AddField(
            model_name='websourceimport',
            name='current_confirmed_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_for_import', to='web_sources.websourceparsedversion'),
        ),
        migrations.AddField(
            model_name='websourceimport',
            name='latest_parsed_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_import', to='web_sources.websourceparsedversion'),
        ),
        migrations.CreateModel(
            name='WebSourceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_url', models.TextField()),
                ('final_url', models.TextField()),
                ('http_status', models.PositiveSmallIntegerField()),
                ('content_type', models.CharField(max_length=64)),
                ('charset', models.CharField(max_length=16)),
                ('actual_bytes', models.PositiveIntegerField()),
                ('response_sha256', models.CharField(max_length=64)),
                ('redirect_count', models.PositiveSmallIntegerField()),
                ('provenance', models.JSONField(default=dict)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('canonical_text', models.TextField()),
                ('parser_version', models.CharField(max_length=32)),
                ('content_digest', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='web_sources.websourceimport')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_source_snapshots',
            },
        ),
        migrations.AddField(
            model_name='websourceparsedversion',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parsed_versions', to='web_sources.websourcesnapshot'),
        ),
        migrations.CreateModel(
            name='WebSourceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('retry_scheduled', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], max_length=24)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('safe_summary', models.JSONField(default=dict)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='web_source_events', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='web_sources.websourceimport')),
                ('parsed_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='web_sources.websourceparsedversion')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='web_sources.websourcesnapshot')),
            ],
            options={
                'db_table': 'web_source_events',
            },
        ),
        migrations.AddIndex(
            model_name='websourceimport',
            index=models.Index(fields=['status', 'next_attempt_at'], name='web_import_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='websourceimport',
            index=models.Index(fields=['user', 'subject', 'created_at'], name='web_import_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='websourceimport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'fetching', 'retry_wait'))), fields=('user', 'subject', 'canonical_url'), name='web_source_one_open_url'),
        ),
        migrations.AddConstraint(
            model_name='websourceimport',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='web_import_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='websourceimport',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='web_import_attempts_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='websourceimport',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0)), name='web_import_retry_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='websourceimport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('generation__isnull', True), ('started_at__isnull', True), ('status', 'queued')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('started_at__isnull', False), ('status', 'fetching')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('next_attempt_at__isnull', False), ('status', 'retry_wait')), models.Q(('finished_at__isnull', False), ('generation__isnull', False), ('status__in', ('succeeded', 'failed'))), _connector='OR'), name='web_import_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='websourcesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('http_status', 200)), name='web_snapshot_http_status_200'),
        ),
        migrations.AddConstraint(
            model_name='websourcesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('actual_bytes__gt', 0)), name='web_snapshot_actual_bytes_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='websourcesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('redirect_count__gte', 0)), name='web_snapshot_redirects_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='websourceparsedversion',
            constraint=models.UniqueConstraint(fields=('import_record', 'version_no'), name='web_parsed_version_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='websourceparsedversion',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'user_confirmation')), fields=('parent_version', 'content_digest'), name='web_confirmation_replay_unique'),
        ),
        migrations.AddConstraint(
            model_name='websourceparsedversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='web_parsed_version_no_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='websourceparsedversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('machine_base_version__isnull', True), ('parent_version__isnull', True), ('source', 'machine'), ('version_no', 1)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('machine_base_version__isnull', False), ('parent_version__isnull', False), ('source', 'user_confirmation')), _connector='OR'), name='web_parsed_version_source_fields'),
        ),
        migrations.AddIndex(
            model_name='websourceevent',
            index=models.Index(fields=['import_record', 'created_at'], name='web_event_import_idx'),
        ),
    ]
