from dataclasses import dataclass

CONFIRM = "confirm"
PASSWORD = "password"
MODE_STRENGTH = {CONFIRM: 1, PASSWORD: 2}
CATALOG_VERSION = 8


@dataclass(frozen=True)
class RiskActionDefinition:
    key: str
    name: str
    module: str
    target_type: str
    supported_modes: tuple[str, ...]
    default_mode: str
    minimum_mode: str
    handler_key: str


RISK_ACTION_CATALOG = (
    RiskActionDefinition(
        "admin.disable",
        "停用管理员",
        "admins",
        "admin_profile",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "admin.disable",
    ),
    RiskActionDefinition(
        "admin.lock",
        "锁定管理员",
        "admins",
        "admin_profile",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "admin.lock",
    ),
    RiskActionDefinition(
        "admin.role.change",
        "变更管理员角色",
        "admins",
        "admin_profile",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "admin.role.change",
    ),
    RiskActionDefinition(
        "admin.force_logout",
        "强制管理员退出",
        "admins",
        "admin_profile",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "admin.force_logout",
    ),
    RiskActionDefinition(
        "role.permissions.replace",
        "替换角色权限",
        "roles",
        "admin_role",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "role.permissions.replace",
    ),
    RiskActionDefinition(
        "role.disable",
        "停用角色",
        "roles",
        "admin_role",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "role.disable",
    ),
    RiskActionDefinition(
        "role.security.update",
        "更新角色登录安全策略",
        "roles",
        "admin_role",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "role.security.update",
    ),
    RiskActionDefinition(
        "role.ip_allowlist.update",
        "更新角色 IP 白名单",
        "roles",
        "admin_role",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "role.ip_allowlist.update",
    ),
    RiskActionDefinition(
        "superuser.ip_allowlist.update",
        "更新超级管理员 IP 白名单",
        "security",
        "superuser_policy",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "superuser.ip_allowlist.update",
    ),
    RiskActionDefinition(
        "customer.assignment.change",
        "变更客户负责人",
        "users",
        "customer_assignment",
        (CONFIRM, PASSWORD),
        PASSWORD,
        CONFIRM,
        "customer.assignment.change",
    ),
    RiskActionDefinition(
        "user.freeze",
        "禁用用户",
        "users",
        "user",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "user.freeze",
    ),
    RiskActionDefinition(
        "plan.create",
        "创建套餐",
        "plans",
        "plan",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "plan.create",
    ),
    RiskActionDefinition(
        "plan.update",
        "修改套餐",
        "plans",
        "plan",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "plan.update",
    ),
    RiskActionDefinition(
        "plan.version.create",
        "创建套餐版本",
        "plans",
        "plan_version",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "plan.version.create",
    ),
    RiskActionDefinition(
        "plan.version.update",
        "修改套餐版本",
        "plans",
        "plan_version",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "plan.version.update",
    ),
    RiskActionDefinition(
        "plan.version.publish",
        "发布套餐版本",
        "plans",
        "plan_version",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "plan.version.publish",
    ),
    RiskActionDefinition(
        "plan.online",
        "上架套餐",
        "plans",
        "plan",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "plan.online",
    ),
    RiskActionDefinition(
        "plan.offline",
        "下架套餐",
        "plans",
        "plan",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "plan.offline",
    ),
    RiskActionDefinition(
        "plan.version.retire",
        "退役套餐版本",
        "plans",
        "plan_version",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "plan.version.retire",
    ),
    RiskActionDefinition(
        "plan.archive",
        "归档套餐",
        "plans",
        "plan",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "plan.archive",
    ),
    RiskActionDefinition(
        "plan.copy",
        "复制套餐",
        "plans",
        "plan",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "plan.copy",
    ),
    RiskActionDefinition(
        "plan_application.contact",
        "联系套餐申请",
        "plan_applications",
        "plan_application",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "plan_application.contact",
    ),
    RiskActionDefinition(
        "plan_application.close",
        "关闭套餐申请",
        "plan_applications",
        "plan_application",
        (CONFIRM, PASSWORD),
        CONFIRM,
        CONFIRM,
        "plan_application.close",
    ),
    RiskActionDefinition(
        "subscription.open",
        "开通正式订阅",
        "subscriptions",
        "plan_application",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "subscription.open",
    ),
    RiskActionDefinition(
        "subscription.grant_trial",
        "发放试用订阅",
        "subscriptions",
        "user",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "subscription.grant_trial",
    ),
    RiskActionDefinition(
        "subscription.terminate",
        "终止订阅",
        "subscriptions",
        "subscription",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "subscription.terminate",
    ),
    RiskActionDefinition(
        "subscription.change",
        "变更订阅套餐",
        "subscriptions",
        "subscription",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "subscription.change",
    ),
    RiskActionDefinition(
        "subscription.change.cancel",
        "取消订阅续费排期",
        "subscriptions",
        "subscription_change",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "subscription.change.cancel",
    ),
    RiskActionDefinition(
        "quota.grant",
        "\u989d\u5ea6\u8d60\u9001",
        "quotas",
        "quota_account",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "quota.grant",
    ),
    RiskActionDefinition(
        "quota.compensate",
        "\u989d\u5ea6\u8865\u507f",
        "quotas",
        "quota_account",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "quota.compensate",
    ),
    RiskActionDefinition(
        "quota.manual_deduct",
        "\u989d\u5ea6\u4eba\u5de5\u6263\u51cf",
        "quotas",
        "quota_account",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "quota.manual_deduct",
    ),
    RiskActionDefinition(
        "subject_risk.catalog.publish",
        "\u53d1\u5e03\u4e3b\u4f53\u98ce\u9669\u76ee\u5f55",
        "subject_risk",
        "subject_risk_catalog",
        (CONFIRM,),
        CONFIRM,
        CONFIRM,
        "subject_risk.catalog.publish",
    ),
)
RISK_ACTION_BY_KEY = {item.key: item for item in RISK_ACTION_CATALOG}

SMS_STEP_UP_REQUIRED_ACTIONS = frozenset(
    {
        "admin.disable",
        "admin.lock",
        "admin.role.change",
        "admin.force_logout",
        "role.permissions.replace",
        "role.disable",
        "role.security.update",
        "role.ip_allowlist.update",
        "superuser.ip_allowlist.update",
        "user.freeze",
        "quota.grant",
        "quota.compensate",
        "quota.manual_deduct",
        "subject_risk.catalog.publish",
    }
)

if not SMS_STEP_UP_REQUIRED_ACTIONS <= RISK_ACTION_BY_KEY.keys():
    raise RuntimeError("SMS Step-Up action policy contains an unknown risk action")


def requires_sms_step_up(action_key: str) -> bool:
    return action_key in SMS_STEP_UP_REQUIRED_ACTIONS


def mode_is_valid(definition: RiskActionDefinition, mode: str) -> bool:
    return (
        mode in definition.supported_modes
        and MODE_STRENGTH[mode] >= MODE_STRENGTH[definition.minimum_mode]
    )
