from dataclasses import dataclass

CONFIRM = "confirm"
PASSWORD = "password"
TWO_PERSON = "two_person"
MODE_STRENGTH = {CONFIRM: 1, PASSWORD: 2, TWO_PERSON: 3}
CATALOG_VERSION = 6


@dataclass(frozen=True)
class RiskActionDefinition:
    key: str
    name: str
    module: str
    target_type: str
    supported_modes: tuple[str, ...]
    default_mode: str
    minimum_mode: str
    handler_key: str


RISK_ACTION_CATALOG = (
    RiskActionDefinition(
        "admin.disable",
        "停用管理员",
        "admins",
        "admin_profile",
        (PASSWORD, TWO_PERSON),
        TWO_PERSON,
        PASSWORD,
        "admin.disable",
    ),
    RiskActionDefinition(
        "admin.lock",
        "锁定管理员",
        "admins",
        "admin_profile",
        (PASSWORD, TWO_PERSON),
        PASSWORD,
        PASSWORD,
        "admin.lock",
    ),
    RiskActionDefinition(
        "admin.role.change",
        "变更管理员角色",
        "admins",
        "admin_profile",
        (PASSWORD, TWO_PERSON),
        TWO_PERSON,
        PASSWORD,
        "admin.role.change",
    ),
    RiskActionDefinition(
        "admin.force_logout",
        "强制管理员退出",
        "admins",
        "admin_profile",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "admin.force_logout",
    ),
    RiskActionDefinition(
        "role.permissions.replace",
        "替换角色权限",
        "roles",
        "admin_role",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "role.permissions.replace",
    ),
    RiskActionDefinition(
        "role.disable",
        "停用角色",
        "roles",
        "admin_role",
        (PASSWORD, TWO_PERSON),
        PASSWORD,
        PASSWORD,
        "role.disable",
    ),
    RiskActionDefinition(
        "role.security.update",
        "更新角色登录安全策略",
        "roles",
        "admin_role",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "role.security.update",
    ),
    RiskActionDefinition(
        "role.ip_allowlist.update",
        "更新角色 IP 白名单",
        "roles",
        "admin_role",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "role.ip_allowlist.update",
    ),
    RiskActionDefinition(
        "superuser.ip_allowlist.update",
        "更新超级管理员 IP 白名单",
        "security",
        "superuser_policy",
        (PASSWORD,),
        PASSWORD,
        PASSWORD,
        "superuser.ip_allowlist.update",
    ),
    RiskActionDefinition(
        "customer.assignment.change",
        "变更客户负责人",
        "users",
        "customer_assignment",
        (CONFIRM, PASSWORD, TWO_PERSON),
        PASSWORD,
        CONFIRM,
        "customer.assignment.change",
    ),
    RiskActionDefinition(
        "user.freeze",
        "冻结用户",
        "users",
        "user",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "user.freeze",
    ),
    RiskActionDefinition(
        "user.review.reject",
        "拒绝用户审核",
        "users",
        "user",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "user.review.reject",
    ),
    RiskActionDefinition(
        "plan.create",
        "创建套餐",
        "plans",
        "plan",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "plan.create",
    ),
    RiskActionDefinition(
        "plan.update",
        "修改套餐",
        "plans",
        "plan",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "plan.update",
    ),
    RiskActionDefinition(
        "plan.version.create",
        "创建套餐版本",
        "plans",
        "plan_version",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "plan.version.create",
    ),
    RiskActionDefinition(
        "plan.version.update",
        "修改套餐版本",
        "plans",
        "plan_version",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "plan.version.update",
    ),
    RiskActionDefinition(
        "plan.version.publish",
        "发布套餐版本",
        "plans",
        "plan_version",
        (PASSWORD, TWO_PERSON),
        PASSWORD,
        PASSWORD,
        "plan.version.publish",
    ),
    RiskActionDefinition(
        "plan.online",
        "上架套餐",
        "plans",
        "plan",
        (PASSWORD, TWO_PERSON),
        PASSWORD,
        PASSWORD,
        "plan.online",
    ),
    RiskActionDefinition(
        "plan.offline",
        "下架套餐",
        "plans",
        "plan",
        (PASSWORD, TWO_PERSON),
        PASSWORD,
        PASSWORD,
        "plan.offline",
    ),
    RiskActionDefinition(
        "plan.version.retire",
        "退役套餐版本",
        "plans",
        "plan_version",
        (PASSWORD, TWO_PERSON),
        PASSWORD,
        PASSWORD,
        "plan.version.retire",
    ),
    RiskActionDefinition(
        "plan.archive",
        "归档套餐",
        "plans",
        "plan",
        (PASSWORD, TWO_PERSON),
        TWO_PERSON,
        PASSWORD,
        "plan.archive",
    ),
    RiskActionDefinition(
        "plan.copy",
        "复制套餐",
        "plans",
        "plan",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "plan.copy",
    ),
    RiskActionDefinition(
        "plan_application.contact",
        "联系套餐申请",
        "plan_applications",
        "plan_application",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "plan_application.contact",
    ),
    RiskActionDefinition(
        "plan_application.close",
        "关闭套餐申请",
        "plan_applications",
        "plan_application",
        (CONFIRM, PASSWORD, TWO_PERSON),
        CONFIRM,
        CONFIRM,
        "plan_application.close",
    ),
    RiskActionDefinition(
        "subscription.open",
        "开通正式订阅",
        "subscriptions",
        "plan_application",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "subscription.open",
    ),
    RiskActionDefinition(
        "subscription.grant_trial",
        "发放试用订阅",
        "subscriptions",
        "user",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "subscription.grant_trial",
    ),
    RiskActionDefinition(
        "subscription.terminate",
        "终止订阅",
        "subscriptions",
        "subscription",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "subscription.terminate",
    ),
    RiskActionDefinition(
        "subscription.change",
        "变更订阅套餐",
        "subscriptions",
        "subscription",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "subscription.change",
    ),
    RiskActionDefinition(
        "subscription.change.cancel",
        "取消订阅续费排期",
        "subscriptions",
        "subscription_change",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "subscription.change.cancel",
    ),
    RiskActionDefinition(
        "quota.grant",
        "\u989d\u5ea6\u8d60\u9001",
        "quotas",
        "quota_account",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "quota.grant",
    ),
    RiskActionDefinition(
        "quota.compensate",
        "\u989d\u5ea6\u8865\u507f",
        "quotas",
        "quota_account",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "quota.compensate",
    ),
    RiskActionDefinition(
        "quota.manual_deduct",
        "\u989d\u5ea6\u4eba\u5de5\u6263\u51cf",
        "quotas",
        "quota_account",
        (TWO_PERSON,),
        TWO_PERSON,
        TWO_PERSON,
        "quota.manual_deduct",
    ),
)
RISK_ACTION_BY_KEY = {item.key: item for item in RISK_ACTION_CATALOG}


def mode_is_valid(definition: RiskActionDefinition, mode: str) -> bool:
    return (
        mode in definition.supported_modes
        and MODE_STRENGTH[mode] >= MODE_STRENGTH[definition.minimum_mode]
    )
