# Generated by Django 5.2.16 on 2026-08-17 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=100, unique=True)),
                ('canonical_name', models.CharField(max_length=150)),
                ('is_builtin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_providers',
                'ordering': ('provider_key', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('provider_key__in', ('deepseek', 'doubao', 'qwen', 'hunyuan', 'wenxin', 'kimi', 'glm', 'spark'))), name='ai_provider_fixed_key'), models.CheckConstraint(condition=models.Q(('is_builtin', True)), name='ai_provider_builtin')],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_key', models.CharField(max_length=100, unique=True)),
                ('canonical_display_name', models.CharField(max_length=150)),
                ('canonical_order', models.PositiveSmallIntegerField(unique=True)),
                ('purpose', models.CharField(choices=[('geo_detection', 'GEO 检测')], default='geo_detection', max_length=32)),
                ('is_builtin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ai.aiprovider')),
            ],
            options={
                'db_table': 'ai_models',
                'ordering': ('canonical_order', 'model_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AIModelRuntimeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name_override', models.CharField(blank=True, max_length=150)),
                ('provider_model_id', models.CharField(blank=True, max_length=255)),
                ('api_version', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('network_access_enabled', models.BooleanField(default=False)),
                ('web_search_failure_policy', models.CharField(choices=[('degrade_formal', '降级普通回答并参与正式评分'), ('degrade_reference', '降级普通回答仅作参考'), ('fail', '直接失败')], default='fail', max_length=32)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('max_retries', models.PositiveSmallIntegerField(default=2)),
                ('retry_base_seconds', models.PositiveIntegerField(default=30)),
                ('retry_backoff', models.CharField(choices=[('fixed', '固定间隔'), ('exponential', '指数退避')], default='exponential', max_length=16)),
                ('max_concurrency', models.PositiveSmallIntegerField(default=1)),
                ('cost_unit', models.CharField(blank=True, choices=[('per_million_tokens', '每百万 Token'), ('per_request', '每次请求')], max_length=32)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('input_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('output_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('request_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('paused', models.BooleanField(default=False)),
                ('pause_reason', models.CharField(blank=True, max_length=200)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_config', to='ai.aimodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_model_runtime_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model_runtime_configs',
                'ordering': ('sort_order', 'model__model_key', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1), ('timeout_seconds__lte', 300)), name='ai_runtime_timeout_range'), models.CheckConstraint(condition=models.Q(('max_retries__gte', 0), ('max_retries__lte', 10)), name='ai_runtime_retries_range'), models.CheckConstraint(condition=models.Q(('retry_base_seconds__gte', 1), ('retry_base_seconds__lte', 3600)), name='ai_runtime_retry_base_range'), models.CheckConstraint(condition=models.Q(('max_concurrency__gte', 1), ('max_concurrency__lte', 1000)), name='ai_runtime_concurrency_range'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ai_runtime_version_gte_1'), models.CheckConstraint(condition=models.Q(('currency', 'CNY')), name='ai_runtime_currency_cny'), models.CheckConstraint(condition=models.Q(models.Q(('cost_unit', ''), ('input_cost__isnull', True), ('output_cost__isnull', True), ('request_cost__isnull', True)), models.Q(('cost_unit', 'per_million_tokens'), ('input_cost__gte', 0), ('input_cost__isnull', False), ('output_cost__gte', 0), ('output_cost__isnull', False), ('request_cost__isnull', True)), models.Q(('cost_unit', 'per_request'), ('input_cost__isnull', True), ('output_cost__isnull', True), ('request_cost__gte', 0), ('request_cost__isnull', False)), _connector='OR'), name='ai_runtime_cost_shape'), models.CheckConstraint(condition=models.Q(models.Q(('pause_reason', ''), ('paused', False)), models.Q(('paused', True), models.Q(('pause_reason', ''), _negated=True)), _connector='OR'), name='ai_runtime_pause_reason')],
            },
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.CheckConstraint(condition=models.Q(('model_key__in', ('deepseek', 'doubao', 'qwen', 'hunyuan', 'wenxin', 'kimi', 'glm', 'spark'))), name='ai_model_fixed_key'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.CheckConstraint(condition=models.Q(('is_builtin', True)), name='ai_model_builtin'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.CheckConstraint(condition=models.Q(('purpose', 'geo_detection')), name='ai_model_detection_only'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_key'), name='ai_model_provider_identity_unique'),
        ),
    ]
