# Generated by Django 5.2.17 on 2026-08-21 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_image_runtime(apps, schema_editor):
    Model = apps.get_model("ai", "AIModel")
    Runtime = apps.get_model("ai", "AICapabilityRuntimeConfig")
    model = Model.objects.get(model_key="doubao", provider__provider_key="doubao")
    Runtime.objects.get_or_create(
        model=model,
        capability="image_generation",
        defaults={
            "provider_model_id": "",
            "api_version": "2024-01-01",
            "enabled": False,
            "timeout_seconds": 120,
            "max_retries": 2,
            "retry_base_seconds": 30,
        },
    )


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        r"""
        CREATE OR REPLACE FUNCTION xw_ai_capability_runtime_guard() RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'AI capability runtime cannot be deleted'; END IF;
          IF NEW.model_id IS DISTINCT FROM OLD.model_id OR
             NEW.capability IS DISTINCT FROM OLD.capability
          THEN RAISE EXCEPTION 'AI capability runtime identity is immutable'; END IF;
          IF NEW.version <> OLD.version + 1
          THEN RAISE EXCEPTION 'AI capability runtime version must increment by one'; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER ai_capability_runtime_guard
          BEFORE UPDATE OR DELETE ON ai_capability_runtime_configs
          FOR EACH ROW EXECUTE FUNCTION xw_ai_capability_runtime_guard();

        CREATE OR REPLACE FUNCTION xw_ai_credential_binding_guard() RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'credential capability binding cannot be deleted'; END IF;
          IF NEW.provider_id IS DISTINCT FROM OLD.provider_id OR
             NEW.capability IS DISTINCT FROM OLD.capability OR
             NEW.environment IS DISTINCT FROM OLD.environment
          THEN RAISE EXCEPTION 'credential capability binding identity is immutable'; END IF;
          IF NEW.version <> OLD.version + 1
          THEN RAISE EXCEPTION 'credential capability binding version must increment by one'; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
        CREATE TRIGGER ai_credential_binding_guard
          BEFORE UPDATE OR DELETE ON api_credential_capability_bindings
          FOR EACH ROW EXECUTE FUNCTION xw_ai_credential_binding_guard();
        """
    )


def reverse_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS ai_credential_binding_guard ON api_credential_capability_bindings;
        DROP FUNCTION IF EXISTS xw_ai_credential_binding_guard();
        DROP TRIGGER IF EXISTS ai_capability_runtime_guard ON ai_capability_runtime_configs;
        DROP FUNCTION IF EXISTS xw_ai_capability_runtime_guard();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_api_credential_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICapabilityRuntimeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('subject_enrichment', 'subject_enrichment'), ('keyword_generation', 'keyword_generation'), ('keyword_distillation', 'keyword_distillation'), ('question_generation', 'question_generation'), ('geo_detection', 'geo_detection'), ('text_generation', 'text_generation'), ('image_generation', 'image_generation'), ('semantic_scoring', 'semantic_scoring'), ('improvement_strategy', 'improvement_strategy'), ('subject_assistant', 'subject_assistant')], max_length=64)),
                ('provider_model_id', models.CharField(blank=True, max_length=255)),
                ('api_version', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('pause_reason', models.CharField(blank=True, max_length=200)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=120)),
                ('max_retries', models.PositiveSmallIntegerField(default=2)),
                ('retry_base_seconds', models.PositiveIntegerField(default=30)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_runtime_configs', to='ai.aimodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_capability_runtime_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_capability_runtime_configs',
                'ordering': ('model__canonical_order', 'capability', 'id'),
                'constraints': [models.UniqueConstraint(fields=('model', 'capability'), name='ai_cap_runtime_model_capability_unique'), models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1), ('timeout_seconds__lte', 600)), name='ai_cap_runtime_timeout_range'), models.CheckConstraint(condition=models.Q(('max_retries__gte', 0), ('max_retries__lte', 10)), name='ai_cap_runtime_retries_range'), models.CheckConstraint(condition=models.Q(('retry_base_seconds__gte', 1), ('retry_base_seconds__lte', 3600)), name='ai_cap_runtime_retry_base_range'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ai_cap_runtime_version_gte_1'), models.CheckConstraint(condition=models.Q(models.Q(('pause_reason', ''), ('paused', False)), models.Q(('paused', True), models.Q(('pause_reason', ''), _negated=True)), _connector='OR'), name='ai_cap_runtime_pause_reason')],
            },
        ),
        migrations.CreateModel(
            name='APICredentialCapabilityBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('subject_enrichment', 'subject_enrichment'), ('keyword_generation', 'keyword_generation'), ('keyword_distillation', 'keyword_distillation'), ('question_generation', 'question_generation'), ('geo_detection', 'geo_detection'), ('text_generation', 'text_generation'), ('image_generation', 'image_generation'), ('semantic_scoring', 'semantic_scoring'), ('improvement_strategy', 'improvement_strategy'), ('subject_assistant', 'subject_assistant')], max_length=64)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_capability_bindings', to='ai.aiprovider')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_credential_capability_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_credential_capability_bindings',
                'ordering': ('provider__provider_key', 'capability', 'environment', 'id'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'capability', 'environment'), name='ai_credential_capability_binding_unique'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ai_credential_binding_version_gte_1')],
            },
        ),
        migrations.RunPython(seed_image_runtime, migrations.RunPython.noop),
        migrations.RunPython(install_guards, reverse_guards),
    ]
