# Generated by Django 5.2.16 on 2026-08-16 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0013_subject_enrichment_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_builtin', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_guidance', models.CharField(blank=True, max_length=2000)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_categories',
                'ordering': ('sort_order', 'key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionCategorySubjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_type_links', to='questions.questioncategory')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_category_links', to='subjects.subjecttype')),
            ],
            options={
                'db_table': 'question_category_subject_types',
            },
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='applicable_subject_types',
            field=models.ManyToManyField(related_name='question_categories', through='questions.QuestionCategorySubjectType', to='subjects.subjecttype'),
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(editable=False, max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_builtin', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_tags',
                'ordering': ('sort_order', 'key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionTagSubjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_tag_links', to='subjects.subjecttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_type_links', to='questions.questiontag')),
            ],
            options={
                'db_table': 'question_tag_subject_types',
            },
        ),
        migrations.AddField(
            model_name='questiontag',
            name='applicable_subject_types',
            field=models.ManyToManyField(related_name='question_tags', through='questions.QuestionTagSubjectType', to='subjects.subjecttype'),
        ),
        migrations.AddConstraint(
            model_name='questioncategorysubjecttype',
            constraint=models.UniqueConstraint(fields=('category', 'subject_type'), name='question_category_subject_type_unique'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['status', 'sort_order', 'id'], name='question_category_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='questioncategory',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='question_category_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='questioncategory',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='question_category_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='questiontagsubjecttype',
            constraint=models.UniqueConstraint(fields=('tag', 'subject_type'), name='question_tag_subject_type_unique'),
        ),
        migrations.AddIndex(
            model_name='questiontag',
            index=models.Index(fields=['status', 'sort_order', 'id'], name='question_tag_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='question_tag_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='question_tag_version_gte_1'),
        ),
    ]
