# Generated by Django 5.2.16 on 2026-08-16 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keywords", "0007_distillation_postgresql_guards"),
        ("plans", "0013_lifecycle_postgresql_guards"),
        ("questions", "0003_postgresql_catalog_guards"),
        ("quotas", "0012_subject_cycle_postgresql_guards"),
        ("subjects", "0013_subject_enrichment_postgresql_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBankVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_no", models.PositiveBigIntegerField()),
                ("content_digest", models.CharField(max_length=64)),
                ("item_count", models.PositiveIntegerField()),
                ("confirmed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_question_bank_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distillation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_versions",
                        to="keywords.distillationset",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_versions",
                        to="subjects.subject",
                    ),
                ),
                (
                    "subject_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_versions",
                        to="subjects.subjectversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_bank_versions",
                "ordering": ("workspace_id", "version_no", "id"),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                ("matching_text", models.CharField(editable=False, max_length=1000)),
                ("primary_category_key", models.CharField(max_length=100)),
                ("primary_category_name", models.CharField(max_length=150)),
                ("primary_category_version", models.PositiveBigIntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        max_length=16,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("natural", "Natural exploration"),
                            ("brand_directed", "Brand directed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("participates_in_scoring", models.BooleanField(default=True)),
                ("ai_reason", models.CharField(blank=True, max_length=1000)),
                ("sort_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "primary_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="questions.questioncategory",
                    ),
                ),
                (
                    "question_bank_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="questions.questionbankversion",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ("question_bank_version_id", "sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="QuestionBankWorkspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_for_workspaces",
                        to="questions.questionbankversion",
                    ),
                ),
                (
                    "draft_distillation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_drafts",
                        to="keywords.distillationset",
                    ),
                ),
                (
                    "draft_subject_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_drafts",
                        to="subjects.subjectversion",
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_workspace",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_bank_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_bank_workspaces",
            },
        ),
        migrations.AddField(
            model_name="questionbankversion",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="questions.questionbankworkspace",
            ),
        ),
        migrations.CreateModel(
            name="QuestionDraftItem",
            fields=[
                ("text", models.CharField(max_length=1000)),
                ("matching_text", models.CharField(editable=False, max_length=1000)),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        max_length=16,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("natural", "Natural exploration"),
                            ("brand_directed", "Brand directed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("participates_in_scoring", models.BooleanField(default=True)),
                ("ai_reason", models.CharField(blank=True, max_length=1000)),
                ("tag_ids", models.JSONField(default=list)),
                ("keyword_ids", models.JSONField(default=list)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="questions.questioncategory",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_items",
                        to="questions.questionbankworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "question_draft_items",
                "ordering": ("workspace_id", "sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="QuestionGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retry_wait", "Retry wait"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                            ("superseded", "Superseded"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("free_initial", "Free initial"),
                            ("regeneration", "Regeneration"),
                        ],
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("expected_workspace_version", models.PositiveBigIntegerField()),
                ("question_limit", models.PositiveIntegerField()),
                ("input_subject_values", models.JSONField(default=dict)),
                ("input_keywords", models.JSONField(default=list)),
                ("input_categories", models.JSONField(default=list)),
                ("input_tags", models.JSONField(default=list)),
                ("provider_key", models.CharField(max_length=32)),
                ("model_key", models.CharField(max_length=64)),
                ("adapter_version", models.CharField(max_length=32)),
                ("prompt_version", models.CharField(max_length=32)),
                ("input_digest", models.CharField(max_length=64)),
                ("idempotency_key_version", models.PositiveSmallIntegerField(default=1)),
                ("idempotency_key_digest", models.CharField(max_length=64, unique=True)),
                ("request_digest", models.CharField(max_length=64)),
                ("generation", models.UUIDField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("stable_error_code", models.CharField(blank=True, max_length=64)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_distillation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_generation_jobs",
                        to="keywords.distillationset",
                    ),
                ),
                (
                    "quota_hold",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_generation_jobs",
                        to="quotas.quotaholdgroup",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_generation_jobs",
                        to="subjects.subject",
                    ),
                ),
                (
                    "subject_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_generation_jobs",
                        to="subjects.subjectversion",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_generation_jobs",
                        to="plans.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_generation_jobs",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="QuestionGenerationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("retry_scheduled", "Retry scheduled"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=24,
                    ),
                ),
                ("stable_error_code", models.CharField(blank=True, max_length=64)),
                ("safe_summary", models.JSONField(default=dict)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="questions.questiongenerationjob",
                    ),
                ),
            ],
            options={
                "db_table": "question_generation_events",
                "ordering": ("job_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="QuestionGenerationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("output_snapshot", models.JSONField()),
                ("output_digest", models.CharField(max_length=64)),
                ("item_count", models.PositiveIntegerField()),
                ("applied_workspace_version", models.PositiveBigIntegerField()),
                ("provider_metrics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="questions.questiongenerationjob",
                    ),
                ),
            ],
            options={
                "db_table": "question_generation_results",
            },
        ),
        migrations.AddField(
            model_name="questionbankworkspace",
            name="draft_source_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applied_workspaces",
                to="questions.questiongenerationresult",
            ),
        ),
        migrations.AddField(
            model_name="questionbankversion",
            name="source_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="confirmed_versions",
                to="questions.questiongenerationresult",
            ),
        ),
        migrations.CreateModel(
            name="QuestionKeywordLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("keyword_text", models.CharField(max_length=500)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_links",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="keyword_links",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_keyword_links",
            },
        ),
        migrations.CreateModel(
            name="QuestionTagLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tag_key", models.CharField(max_length=100)),
                ("tag_name", models.CharField(max_length=150)),
                ("tag_version", models.PositiveBigIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tag_links",
                        to="questions.question",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_links",
                        to="questions.questiontag",
                    ),
                ),
            ],
            options={
                "db_table": "question_tag_links",
            },
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("question_bank_version", "matching_text"), name="question_text_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("question_bank_version", "sort_order"), name="question_sort_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", ("high", "medium", "low"))),
                name="question_priority_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_type__in", ("natural", "brand_directed"))),
                name="question_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("text", ""), _negated=True),
                    models.Q(("matching_text", ""), _negated=True),
                ),
                name="question_text_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondraftitem",
            constraint=models.UniqueConstraint(
                fields=("workspace", "matching_text"), name="question_draft_text_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondraftitem",
            constraint=models.UniqueConstraint(
                fields=("workspace", "sort_order"), name="question_draft_sort_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondraftitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", ("high", "medium", "low"))),
                name="question_draft_priority_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondraftitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_type__in", ("natural", "brand_directed"))),
                name="question_draft_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondraftitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("text", ""), _negated=True),
                    models.Q(("matching_text", ""), _negated=True),
                ),
                name="question_draft_text_present",
            ),
        ),
        migrations.AddIndex(
            model_name="questiongenerationjob",
            index=models.Index(
                fields=["subject", "status", "created_at"], name="question_gen_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questiongenerationjob",
            index=models.Index(fields=["status", "next_attempt_at"], name="question_gen_retry_idx"),
        ),
        migrations.AddConstraint(
            model_name="questiongenerationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("queued", "running", "retry_wait"))),
                fields=("subject",),
                name="question_generation_one_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiongenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "running",
                            "retry_wait",
                            "succeeded",
                            "failed",
                            "conflict",
                            "superseded",
                        ),
                    )
                ),
                name="question_generation_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiongenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("billing_mode", "free_initial"), ("quota_hold__isnull", True)),
                    models.Q(("billing_mode", "regeneration"), ("quota_hold__isnull", False)),
                    _connector="OR",
                ),
                name="question_generation_billing_hold",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiongenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1), ("question_limit__gte", 1)),
                name="question_generation_counts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiongenerationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        (
                            "started",
                            "retry_scheduled",
                            "succeeded",
                            "failed",
                            "conflict",
                            "superseded",
                        ),
                    )
                ),
                name="question_generation_event_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiongenerationresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("item_count__gte", 1),
                    ("applied_workspace_version__gte", 1),
                    models.Q(("output_digest", ""), _negated=True),
                ),
                name="question_generation_result_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionbankworkspace",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="question_bank_workspace_version_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionbankversion",
            constraint=models.UniqueConstraint(
                fields=("workspace", "version_no"), name="question_bank_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionbankversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version_no__gte", 1),
                    ("item_count__gte", 1),
                    models.Q(("content_digest", ""), _negated=True),
                ),
                name="question_bank_version_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionkeywordlink",
            constraint=models.UniqueConstraint(
                fields=("question", "keyword"), name="question_keyword_link_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiontaglink",
            constraint=models.UniqueConstraint(
                fields=("question", "tag"), name="question_tag_link_unique"
            ),
        ),
    ]
