# Generated by Django 5.2.16 on 2026-07-31 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('permission_type', models.CharField(choices=[('menu', '菜单'), ('action', '动作')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('superuser_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin_permissions',
                'ordering': ('sort_order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('data_scope', models.CharField(choices=[('own', '仅本人负责'), ('role', '当前角色'), ('all', '全部客户')], max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_roles',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_status', models.CharField(choices=[('active', '启用'), ('disabled', '停用'), ('locked', '锁定')], db_index=True, default='active', max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_profiles', to='admin_rbac.adminrole')),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignment', to=settings.AUTH_USER_MODEL)),
                ('owner_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_assignments', to='admin_rbac.adminprofile')),
            ],
            options={
                'db_table': 'customer_assignments',
            },
        ),
        migrations.CreateModel(
            name='AdminRbacEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('safe_before', models.JSONField(default=dict)),
                ('safe_after', models.JSONField(default=dict)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_rbac_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_rbac_events',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['target_type', 'target_id', 'created_at'], name='rbac_target_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminRolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_links', to='admin_rbac.adminpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='admin_rbac.adminrole')),
            ],
            options={
                'db_table': 'admin_role_permissions',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='admin_role_permission_unique')],
            },
        ),
    ]
