# Generated by Django 5.2.16 on 2026-07-31 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rbac', '0002_seed_catalog_and_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adminpermission',
            constraint=models.CheckConstraint(condition=models.Q(('permission_type__in', ('menu', 'action'))), name='admin_permission_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='adminpermission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='admin_permission_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('admin_status__in', ('active', 'disabled', 'locked'))), name='admin_profile_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='admin_profile_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='adminrole',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='admin_role_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='adminrole',
            constraint=models.CheckConstraint(condition=models.Q(('data_scope__in', ('own', 'role', 'all'))), name='admin_role_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='adminrole',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='admin_role_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='customerassignment',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='customer_assignment_version_gte_1'),
        ),
    ]
