# Generated by Django 5.2.16 on 2026-07-31 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rbac', '0003_adminpermission_admin_permission_valid_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('request_id', models.UUIDField(db_index=True)),
                ('ip_fingerprint', models.CharField(blank=True, max_length=64)),
                ('user_agent_digest', models.CharField(blank=True, max_length=64)),
                ('admin_profile_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('role_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('role_security_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('policy_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('stable_failure_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_security_events',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RoleIpAllowlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network_cidr', models.CharField(max_length=64)),
                ('ip_version', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_role_ip_allowlist_entries',
                'ordering': ('network_cidr', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SuperuserIpAllowlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network_cidr', models.CharField(max_length=64)),
                ('ip_version', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'superuser_ip_allowlist_entries',
                'ordering': ('network_cidr', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SuperuserSecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_allowlist_enabled', models.BooleanField(default=False)),
                ('security_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'superuser_security_policies',
            },
        ),
        migrations.AddField(
            model_name='adminrole',
            name='ip_allowlist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='require_sms_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='security_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='adminrole',
            constraint=models.CheckConstraint(condition=models.Q(('security_version__gte', 1)), name='admin_role_security_version_gte_1'),
        ),
        migrations.AddField(
            model_name='adminsecurityevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_security_events_as_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminsecurityevent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_security_events_as_subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleipallowlistentry',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_allowlist_entries', to='admin_rbac.adminrole'),
        ),
        migrations.AddField(
            model_name='superusersecuritypolicy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superuser_security_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superuseripallowlistentry',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_allowlist_entries', to='admin_rbac.superusersecuritypolicy'),
        ),
        migrations.AddIndex(
            model_name='adminsecurityevent',
            index=models.Index(fields=['subject', 'created_at'], name='admin_sec_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsecurityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='admin_sec_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleipallowlistentry',
            constraint=models.UniqueConstraint(fields=('role', 'network_cidr'), name='admin_role_ip_cidr_unique'),
        ),
        migrations.AddConstraint(
            model_name='roleipallowlistentry',
            constraint=models.CheckConstraint(condition=models.Q(('ip_version__in', (4, 6))), name='admin_role_ip_version_valid'),
        ),
        migrations.AddConstraint(
            model_name='roleipallowlistentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='admin_role_ip_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='superusersecuritypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('security_version__gte', 1)), name='superuser_security_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='superuseripallowlistentry',
            constraint=models.UniqueConstraint(fields=('policy', 'network_cidr'), name='superuser_ip_cidr_unique'),
        ),
        migrations.AddConstraint(
            model_name='superuseripallowlistentry',
            constraint=models.CheckConstraint(condition=models.Q(('ip_version__in', (4, 6))), name='superuser_ip_version_valid'),
        ),
        migrations.AddConstraint(
            model_name='superuseripallowlistentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='superuser_ip_status_valid'),
        ),
    ]
