# Generated by Django 5.2.16 on 2026-08-01 02:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rbac', '0005_initialize_superuser_security_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAction',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('supported_modes', models.JSONField(default=list)),
                ('default_mode', models.CharField(max_length=16)),
                ('minimum_mode', models.CharField(max_length=16)),
                ('handler_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('catalog_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_actions',
                'ordering': ('module', 'key'),
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='risk_action_valid_status'), models.CheckConstraint(condition=models.Q(('catalog_version__gte', 1)), name='risk_action_catalog_version_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_key', models.CharField(max_length=100)),
                ('policy_version', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('target_version', models.PositiveBigIntegerField(default=0)),
                ('sanitized_payload', models.JSONField(default=dict)),
                ('payload_digest', models.CharField(max_length=64)),
                ('safe_summary', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('expired', '已过期'), ('stale', '已失效'), ('executed', '已执行'), ('execution_failed', '执行失败')], default='pending', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_result', models.JSONField(default=dict)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('request_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risk_requests', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_risk_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='admin_rbac.riskaction')),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_mode', models.CharField(max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='admin_rbac.riskaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_risk_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_policies',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('action_key', models.CharField(db_index=True, max_length=100)),
                ('outcome', models.CharField(db_index=True, max_length=32)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('request_id', models.UUIDField(db_index=True)),
                ('safe_before', models.JSONField(default=dict)),
                ('safe_after', models.JSONField(default=dict)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('ip_fingerprint', models.CharField(blank=True, max_length=64)),
                ('user_agent_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='admin_rbac.approvalrequest')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_approver', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_requester', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['target_type', 'target_id', 'created_at'], name='audit_target_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'expires_at'], name='approval_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester', 'created_at'], name='approval_requester_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['target_type', 'target_id'], name='approval_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('target_version__gte', 0)), name='approval_target_version_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by', models.F('requester')), _negated=True), name='approval_requester_not_approver'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='approval_expiry_after_created'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'action', 'target_type', 'target_id', 'payload_digest'), name='approval_unique_pending_payload'),
        ),
        migrations.AddConstraint(
            model_name='riskpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='risk_policy_version_gte_1'),
        ),
    ]
