# Generated by Django 5.2.16 on 2026-08-01 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rbac', '0007_seed_risk_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_by', models.F('requester')), _negated=True), name='approval_requester_not_rejecter'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('executed_at__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'pending')), models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('executed_at__isnull', True), ('rejected_at__isnull', False), ('rejected_by__isnull', False), ('status', 'rejected')), models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', False), ('executed_at__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'cancelled')), models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('executed_at__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status__in', ('expired', 'stale'))), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('cancelled_at__isnull', True), ('executed_at__isnull', False), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status__in', ('executed', 'execution_failed'))), _connector='OR'), name='approval_status_times_consistent'),
        ),
        migrations.AddConstraint(
            model_name='riskpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('current_mode__in', ('confirm', 'password', 'two_person'))), name='risk_policy_valid_mode'),
        ),
    ]
