# Generated by Django 5.2.16 on 2026-08-02 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rbac', '0014_single_pending_subscription_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('action_key', 'subscription.change.cancel'), ('status', 'pending')), fields=('action_key', 'target_id'), name='approval_single_pending_subscription_cancel'),
        ),
    ]
