# Generated by Django 5.2.17 on 2026-08-31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_rbac", "0028_seed_quota_refund_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesContactConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "平台全局"), ("agent", "代理")],
                        max_length=16,
                    ),
                ),
                ("object_key", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_admin",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_contact_configuration",
                        to="admin_rbac.adminprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_sales_contact_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_contact_configurations",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(owner_admin__isnull=True, scope="global"),
                            models.Q(owner_admin__isnull=False, scope="agent"),
                            _connector="OR",
                        ),
                        name="sales_contact_scope_owner_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="sales_contact_version_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("enabled", False),
                                ("mime_type", ""),
                                ("object_key", ""),
                                ("sha256", ""),
                                ("size_bytes__isnull", True),
                            ),
                            models.Q(
                                models.Q(("object_key", ""), _negated=True),
                                models.Q(("mime_type", ""), _negated=True),
                                ("size_bytes__gt", 0),
                                models.Q(("sha256", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="sales_contact_media_state_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(scope="global"),
                        fields=("scope",),
                        name="sales_contact_single_global",
                    ),
                ],
            },
        ),
    ]
