import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


PLATFORMS = (
    {
        "key": "wechat",
        "name": "微信公众号",
        "official_url": "https://mp.weixin.qq.com/",
        "channel_type": "social_content",
        "auth_mode": "official_credentials",
        "publish_mode": "official_api",
        "validation_status": "available",
        "login_url": "https://mp.weixin.qq.com/",
        "publish_url": "https://mp.weixin.qq.com/",
        "interval": 30,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": False, "qr_login": False},
        "rules": {"title": "简洁有信息量", "structure": "导语、分节、总结", "tone": "专业易读", "tags": False, "external_links": "按平台规则"},
    },
    {
        "key": "toutiao",
        "name": "今日头条",
        "official_url": "https://mp.toutiao.com/",
        "channel_type": "news_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "available",
        "login_url": "https://mp.toutiao.com/",
        "publish_url": "https://mp.toutiao.com/profile_v4/graphic/publish",
        "interval": 30,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "资讯型、具体", "structure": "结论先行、分节、总结", "tone": "清晰易读", "tags": True, "external_links": "按平台规则"},
    },
    {
        "key": "baijiahao",
        "name": "百家号",
        "official_url": "https://baijiahao.baidu.com/",
        "channel_type": "news_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://baijiahao.baidu.com/",
        "publish_url": "https://baijiahao.baidu.com/",
        "interval": 30,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "搜索友好、信息明确", "structure": "摘要、正文、结论", "tone": "客观专业", "tags": True, "external_links": "克制使用"},
    },
    {
        "key": "zhihu",
        "name": "知乎",
        "official_url": "https://www.zhihu.com/",
        "channel_type": "knowledge_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://www.zhihu.com/signin",
        "publish_url": "https://zhuanlan.zhihu.com/write",
        "interval": 30,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "问题导向", "structure": "结论先行、论据、总结", "tone": "理性解释", "tags": True, "external_links": "克制使用"},
    },
    {
        "key": "xiaohongshu",
        "name": "小红书",
        "official_url": "https://creator.xiaohongshu.com/",
        "channel_type": "social_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://creator.xiaohongshu.com/",
        "publish_url": "https://creator.xiaohongshu.com/",
        "interval": 30,
        "capabilities": {"article": False, "cover": True, "images": True, "tags": True, "qr_login": True, "image_post": True},
        "rules": {"title": "短而具体", "structure": "短段落、要点、标签", "tone": "自然清楚", "tags": True, "external_links": "不主动添加"},
    },
    {
        "key": "weibo",
        "name": "微博",
        "official_url": "https://weibo.com/",
        "channel_type": "social_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://weibo.com/",
        "publish_url": "https://weibo.com/",
        "interval": 20,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "核心观点", "structure": "摘要、话题、延伸阅读", "tone": "凝练", "tags": True, "external_links": "按平台规则"},
    },
    {
        "key": "bilibili",
        "name": "B站专栏",
        "official_url": "https://member.bilibili.com/",
        "channel_type": "community_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://passport.bilibili.com/login",
        "publish_url": "https://member.bilibili.com/platform/upload/text/edit",
        "interval": 20,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "清晰具体", "structure": "导语、正文、总结", "tone": "专业易懂", "tags": True, "external_links": "按平台规则"},
    },
    {
        "key": "douyin",
        "name": "抖音图文",
        "official_url": "https://creator.douyin.com/",
        "channel_type": "social_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://creator.douyin.com/",
        "publish_url": "https://creator.douyin.com/",
        "interval": 30,
        "capabilities": {"article": False, "cover": True, "images": True, "tags": True, "qr_login": True, "image_post": True},
        "rules": {"title": "短标题", "structure": "图文卡片、核心要点", "tone": "直接清楚", "tags": True, "external_links": "不主动添加"},
    },
    {
        "key": "qq",
        "name": "企鹅号",
        "official_url": "https://om.qq.com/",
        "channel_type": "news_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://om.qq.com/",
        "publish_url": "https://om.qq.com/",
        "interval": 30,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "资讯型", "structure": "摘要、正文、结论", "tone": "客观清晰", "tags": True, "external_links": "按平台规则"},
    },
    {
        "key": "sohu",
        "name": "搜狐号",
        "official_url": "https://mp.sohu.com/",
        "channel_type": "news_content",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "paused",
        "login_url": "https://mp.sohu.com/",
        "publish_url": "https://mp.sohu.com/",
        "interval": 30,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "资讯型", "structure": "摘要、正文、结论", "tone": "客观专业", "tags": True, "external_links": "按平台规则"},
    },
    {
        "key": "csdn",
        "name": "CSDN",
        "official_url": "https://mp.csdn.net/",
        "channel_type": "tech_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://passport.csdn.net/login",
        "publish_url": "https://editor.csdn.net/md/",
        "interval": 20,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "技术问题明确", "structure": "背景、方法、步骤、结论", "tone": "技术专业", "tags": True, "external_links": "允许可核验来源"},
    },
    {
        "key": "juejin",
        "name": "掘金",
        "official_url": "https://juejin.cn/",
        "channel_type": "tech_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://juejin.cn/",
        "publish_url": "https://juejin.cn/editor/drafts/new?v=2",
        "interval": 20,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": True},
        "rules": {"title": "技术主题明确", "structure": "背景、实现、结果", "tone": "专业直接", "tags": True, "external_links": "允许可核验来源"},
    },
    {
        "key": "cnblogs",
        "name": "博客园",
        "official_url": "https://www.cnblogs.com/",
        "channel_type": "tech_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://account.cnblogs.com/signin",
        "publish_url": "https://i.cnblogs.com/posts/edit",
        "interval": 20,
        "capabilities": {"article": True, "cover": False, "images": True, "tags": True, "qr_login": False},
        "rules": {"title": "技术主题明确", "structure": "问题、方法、实现、总结", "tone": "技术专业", "tags": True, "external_links": "允许可核验来源"},
    },
    {
        "key": "oschina",
        "name": "开源中国",
        "official_url": "https://www.oschina.net/",
        "channel_type": "tech_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://www.oschina.net/home/login",
        "publish_url": "https://my.oschina.net/",
        "interval": 20,
        "capabilities": {"article": True, "cover": True, "images": True, "tags": True, "qr_login": False},
        "rules": {"title": "技术主题明确", "structure": "背景、实践、结论", "tone": "专业", "tags": True, "external_links": "允许可核验来源"},
    },
    {
        "key": "segmentfault",
        "name": "思否",
        "official_url": "https://segmentfault.com/",
        "channel_type": "tech_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://segmentfault.com/user/login",
        "publish_url": "https://segmentfault.com/write",
        "interval": 20,
        "capabilities": {"article": True, "cover": False, "images": True, "tags": True, "qr_login": False},
        "rules": {"title": "问题或技术主题", "structure": "问题、分析、方案、结论", "tone": "理性专业", "tags": True, "external_links": "允许可核验来源"},
    },
    {
        "key": "jianshu",
        "name": "简书",
        "official_url": "https://www.jianshu.com/",
        "channel_type": "content_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://www.jianshu.com/sign_in",
        "publish_url": "https://www.jianshu.com/writer",
        "interval": 20,
        "capabilities": {"article": True, "cover": False, "images": True, "tags": False, "qr_login": False},
        "rules": {"title": "清晰自然", "structure": "导语、正文、总结", "tone": "自然易读", "tags": False, "external_links": "克制使用"},
    },
    {
        "key": "douban",
        "name": "豆瓣",
        "official_url": "https://www.douban.com/",
        "channel_type": "content_community",
        "auth_mode": "browser_qr",
        "publish_mode": "browser",
        "validation_status": "testing",
        "login_url": "https://accounts.douban.com/passport/login",
        "publish_url": "https://www.douban.com/",
        "interval": 30,
        "capabilities": {"article": True, "cover": False, "images": True, "tags": False, "qr_login": True},
        "rules": {"title": "自然具体", "structure": "正文、观点、总结", "tone": "克制自然", "tags": False, "external_links": "克制使用"},
    },
)


def seed_platforms(apps, schema_editor):
    Channel = apps.get_model("articles", "PublishingChannel")
    Template = apps.get_model("articles", "ChannelTemplateVersion")
    Platform = apps.get_model("publications", "PublicationPlatform")

    existing_max = Channel.objects.order_by("-sort_order").values_list("sort_order", flat=True).first() or 0
    for offset, item in enumerate(PLATFORMS, start=1):
        channel, created = Channel.objects.get_or_create(
            key=item["key"],
            defaults={
                "name": item["name"],
                "official_url": item["official_url"],
                "channel_type": item["channel_type"],
                "description": "支持平台内容适配；自动发布能力以显问平台状态为准。",
                "applicable_article_types": [],
                "image_ratios": ["1:1", "16:9", "3:4"],
                "enabled": True,
                "sort_order": existing_max + offset,
            },
        )
        if created:
            Template.objects.create(
                channel=channel,
                version_no=1,
                rules=item["rules"],
                prompt_version=f"channel-{item['key']}-v1",
                is_current=True,
            )
        Platform.objects.get_or_create(
            channel=channel,
            defaults={
                "auth_mode": item["auth_mode"],
                "publish_mode": item["publish_mode"],
                "validation_status": item["validation_status"],
                "health_status": "healthy",
                "login_url": item["login_url"],
                "publish_url": item["publish_url"],
                "capabilities": item["capabilities"],
                "minimum_interval_minutes": item["interval"],
            },
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_seed_catalogs_and_postgresql_guards"),
        ("images", "0002_seed_presets_and_postgresql_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationPlatform",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("auth_mode", models.CharField(choices=[("browser_qr", "浏览器扫码"), ("official_credentials", "官方凭据"), ("hybrid", "混合授权")], max_length=32)),
                ("publish_mode", models.CharField(choices=[("browser", "浏览器发布"), ("official_api", "官方接口"), ("hybrid", "混合发布")], max_length=32)),
                ("validation_status", models.CharField(choices=[("available", "可用"), ("testing", "正在验证"), ("paused", "已暂停")], default="testing", max_length=16)),
                ("health_status", models.CharField(choices=[("healthy", "正常"), ("degraded", "部分异常"), ("unavailable", "暂不可用")], default="healthy", max_length=16)),
                ("login_url", models.TextField()),
                ("publish_url", models.TextField(blank=True)),
                ("capabilities", models.JSONField(default=dict)),
                ("minimum_interval_minutes", models.PositiveIntegerField(default=30)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="publication_platform", to="articles.publishingchannel")),
            ],
            options={"db_table": "publication_platforms", "ordering": ("channel__sort_order", "channel__key")},
        ),
        migrations.CreateModel(
            name="PlatformAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("external_account_id", models.CharField(blank=True, max_length=200)),
                ("auth_method", models.CharField(max_length=32)),
                ("auth_status", models.CharField(choices=[("authorizing", "授权中"), ("authorized", "已授权"), ("expired", "授权已失效"), ("needs_verification", "需要重新验证"), ("revoked", "已解除授权"), ("failed", "授权失败")], default="authorizing", max_length=32)),
                ("encrypted_auth_state", models.TextField(blank=True)),
                ("auth_metadata", models.JSONField(default=dict)),
                ("enabled_for_auto_publish", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=True)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_auth_check_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="accounts", to="publications.publicationplatform")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_accounts", to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_accounts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "publication_accounts", "ordering": ("platform__channel__sort_order", "created_at")},
        ),
        migrations.CreateModel(
            name="AuthorizationSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("auth_method", models.CharField(max_length=32)),
                ("status", models.CharField(choices=[("queued", "准备授权"), ("waiting", "等待扫码"), ("authorized", "授权成功"), ("needs_interaction", "需要额外验证"), ("expired", "授权已过期"), ("failed", "授权失败"), ("cancelled", "已取消")], default="queued", max_length=32)),
                ("login_snapshot_data_url", models.TextField(blank=True)),
                ("safe_error_code", models.CharField(blank=True, max_length=100)),
                ("expires_at", models.DateTimeField()),
                ("last_snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="authorization_sessions", to="publications.platformaccount")),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="authorization_sessions", to="publications.publicationplatform")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="authorization_sessions", to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="authorization_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "publication_authorization_sessions", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="AutoPublishPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("enabled", models.BooleanField(default=False)),
                ("operating_mode", models.CharField(choices=[("managed", "全自动托管"), ("review", "审核后发布"), ("selected", "仅发布指定内容")], default="managed", max_length=16)),
                ("distribution_strategy", models.CharField(choices=[("smart", "智能分发"), ("all_authorized", "所有已授权平台"), ("custom", "自定义平台")], default="smart", max_length=24)),
                ("custom_platform_keys", models.JSONField(default=list)),
                ("frequency_mode", models.CharField(choices=[("smart", "智能安排"), ("daily_1", "每天 1 篇"), ("daily_2", "每天 2 篇"), ("daily_3", "每天 3 篇"), ("custom", "自定义")], default="smart", max_length=16)),
                ("custom_daily_limit", models.PositiveSmallIntegerField(default=1)),
                ("image_strategy", models.CharField(choices=[("customer_only", "仅使用企业素材"), ("prefer_customer", "企业素材优先，不足自动补图"), ("auto", "全自动配图")], default="prefer_customer", max_length=24)),
                ("image_richness", models.CharField(choices=[("simple", "简洁"), ("standard", "标准"), ("rich", "丰富")], default="standard", max_length=16)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="auto_publish_policies", to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="auto_publish_policies", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "auto_publish_policies"},
        ),
        migrations.CreateModel(
            name="PublicationJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("planning", "正在规划"), ("preparing", "正在准备"), ("scheduled", "等待发布"), ("publishing", "发布中"), ("succeeded", "已完成"), ("partial", "部分完成"), ("failed", "发布失败"), ("cancelled", "已取消")], default="planning", max_length=24)),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("distribution_plan", models.JSONField(default=dict)),
                ("visual_plan", models.JSONField(default=dict)),
                ("idempotency_key_digest", models.CharField(max_length=64, unique=True)),
                ("safe_error_code", models.CharField(blank=True, max_length=100)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_jobs", to="articles.article")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_jobs", to="publications.autopublishpolicy")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_jobs", to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "publication_jobs", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="PublicationTarget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("waiting", "等待准备"), ("adapting", "正在适配"), ("ready", "准备完成"), ("scheduled", "等待发布"), ("publishing", "发布中"), ("published", "已发布"), ("failed", "发布失败"), ("requires_auth", "需要重新授权"), ("skipped", "已跳过")], default="waiting", max_length=24)),
                ("payload_snapshot", models.JSONField(default=dict)),
                ("image_plan", models.JSONField(default=dict)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("external_post_id", models.CharField(blank=True, max_length=300)),
                ("public_url", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("safe_error_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_targets", to="publications.platformaccount")),
                ("adaptation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="publication_targets", to="articles.channeladaptation")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="targets", to="publications.publicationjob")),
                ("platform", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_targets", to="publications.publicationplatform")),
            ],
            options={"db_table": "publication_targets", "ordering": ("scheduled_at", "created_at")},
        ),
        migrations.CreateModel(
            name="PublicationVisual",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("cover", "封面"), ("illustration", "正文插图"), ("thumbnail", "平台缩略图"), ("card", "信息卡图")], max_length=24)),
                ("ordinal", models.PositiveSmallIntegerField(default=0)),
                ("section_hint", models.CharField(blank=True, max_length=200)),
                ("source_strategy", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publication_visuals", to="images.imageasset")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="visuals", to="publications.publicationjob")),
                ("target", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="visuals", to="publications.publicationtarget")),
            ],
            options={"db_table": "publication_visuals", "ordering": ("role", "ordinal", "created_at")},
        ),
        migrations.AddIndex(model_name="platformaccount", index=models.Index(fields=["user", "subject", "auth_status"], name="pub_account_owner_status_idx")),
        migrations.AddConstraint(model_name="platformaccount", constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="pub_account_version_gte_1")),
        migrations.AddConstraint(model_name="platformaccount", constraint=models.UniqueConstraint(condition=models.Q(("is_default", True)), fields=("user", "subject", "platform"), name="pub_account_one_default")),
        migrations.AddIndex(model_name="authorizationsession", index=models.Index(fields=["status", "expires_at"], name="pub_auth_status_expiry_idx")),
        migrations.AddConstraint(model_name="autopublishpolicy", constraint=models.UniqueConstraint(fields=("user", "subject"), name="auto_publish_policy_unique")),
        migrations.AddConstraint(model_name="autopublishpolicy", constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="auto_publish_policy_version_gte_1")),
        migrations.AddConstraint(model_name="autopublishpolicy", constraint=models.CheckConstraint(condition=models.Q(("custom_daily_limit__gte", 1), ("custom_daily_limit__lte", 20)), name="auto_publish_daily_limit_range")),
        migrations.AddIndex(model_name="publicationjob", index=models.Index(fields=["user", "status", "created_at"], name="pub_job_owner_status_idx")),
        migrations.AddConstraint(model_name="publicationtarget", constraint=models.UniqueConstraint(fields=("job", "platform"), name="publication_target_unique")),
        migrations.AddIndex(model_name="publicationtarget", index=models.Index(fields=["status", "scheduled_at"], name="pub_target_schedule_idx")),
        migrations.AddConstraint(model_name="publicationvisual", constraint=models.UniqueConstraint(fields=("job", "target", "image", "role", "ordinal"), name="publication_visual_unique")),
        migrations.RunPython(seed_platforms, migrations.RunPython.noop),
    ]
