# Generated by Django 5.2.16 on 2026-08-10 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('icon_key', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_builtin', models.BooleanField(default=False)),
                ('schema_version', models.PositiveBigIntegerField(default=1)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_types', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subject_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_types',
                'ordering': ('sort_order', 'key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=64)),
                ('field_type', models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('date', '日期'), ('single', '单选'), ('multi', '多选'), ('select', '下拉选择'), ('url', '网址'), ('image', '图片上传（尚未启用）'), ('file', '文件上传（尚未启用）')], max_length=16)),
                ('scope', models.CharField(choices=[('common', '公共字段'), ('custom', '自定义字段')], max_length=16)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_field_definitions', to=settings.AUTH_USER_MODEL)),
                ('owner_subject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_field_definitions', to='subjects.subjecttype')),
            ],
            options={
                'db_table': 'subject_field_definitions',
                'ordering': ('scope', 'field_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectTypeFieldConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('used_for_ai', models.BooleanField(default=False)),
                ('name_role', models.CharField(choices=[('none', '无'), ('official_name', '正式名称'), ('alias', '别名'), ('english_name', '英文名'), ('product', '产品名称')], default='none', max_length=32)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_field_configs', to=settings.AUTH_USER_MODEL)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_configs', to='subjects.subjectfielddefinition')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_configs', to='subjects.subjecttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subject_field_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_type_field_configs',
                'ordering': ('subject_type_id', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectFieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_field_options', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subject_field_options', to=settings.AUTH_USER_MODEL)),
                ('field_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='subjects.subjecttypefieldconfig')),
            ],
            options={
                'db_table': 'subject_field_options',
                'ordering': ('field_config_id', 'sort_order', 'option_key', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='subjecttype',
            index=models.Index(fields=['status', 'sort_order', 'id'], name='subject_type_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjecttype',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='subject_type_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='subjecttype',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='subject_type_schema_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjecttype',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_type_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectfielddefinition',
            constraint=models.UniqueConstraint(fields=('scope', 'owner_subject_type', 'field_key'), name='subject_field_definition_key_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='subjectfielddefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_subject_type__isnull', True), ('scope', 'common')), models.Q(('owner_subject_type__isnull', False), ('scope', 'custom')), _connector='OR'), name='subject_field_definition_scope_owner'),
        ),
        migrations.AddConstraint(
            model_name='subjectfielddefinition',
            constraint=models.CheckConstraint(condition=models.Q(('field_type__in', ('text', 'textarea', 'number', 'date', 'single', 'multi', 'select', 'url', 'image', 'file'))), name='subject_field_definition_valid_type'),
        ),
        migrations.AddIndex(
            model_name='subjecttypefieldconfig',
            index=models.Index(fields=['subject_type', 'enabled', 'sort_order', 'id'], name='subject_field_schema_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjecttypefieldconfig',
            constraint=models.UniqueConstraint(fields=('subject_type', 'field_definition'), name='subject_type_field_config_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjecttypefieldconfig',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_field_config_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjecttypefieldconfig',
            constraint=models.CheckConstraint(condition=models.Q(('name_role__in', ('none', 'official_name', 'alias', 'english_name', 'product'))), name='subject_field_config_valid_name_role'),
        ),
        migrations.AddConstraint(
            model_name='subjecttypefieldconfig',
            constraint=models.CheckConstraint(condition=models.Q(('enabled', True), ('required', False), _connector='OR'), name='subject_field_disabled_not_required'),
        ),
        migrations.AddConstraint(
            model_name='subjectfieldoption',
            constraint=models.UniqueConstraint(fields=('field_config', 'option_key'), name='subject_field_option_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjectfieldoption',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_field_option_version_gte_1'),
        ),
    ]
