# Generated by Django 5.2.16 on 2026-08-10 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_postgresql_schema_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '已归档')], default='draft', max_length=16)),
                ('draft_values', models.JSONField(default=dict)),
                ('schema_version', models.PositiveBigIntegerField()),
                ('schema_snapshot_format_version', models.PositiveSmallIntegerField(default=1)),
                ('schema_snapshot', models.JSONField()),
                ('schema_digest', models.CharField(max_length=64)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='subjects.subjecttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ('-updated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_by_contexts', to='subjects.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subject_context', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_contexts',
            },
        ),
        migrations.CreateModel(
            name='SubjectEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', '已创建'), ('activated', '已启用'), ('archived', '已归档'), ('current_selected', '已设为当前主体'), ('current_cleared', '已清除当前主体')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '已归档')], max_length=16)),
                ('safe_summary', models.JSONField(default=dict)),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_subject_events', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='subjects.subject')),
            ],
            options={
                'db_table': 'subject_events',
                'ordering': ('subject_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveBigIntegerField()),
                ('field_values', models.JSONField()),
                ('schema_version', models.PositiveBigIntegerField()),
                ('schema_snapshot_format_version', models.PositiveSmallIntegerField(default=1)),
                ('schema_snapshot', models.JSONField()),
                ('schema_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_versions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='subjects.subject')),
            ],
            options={
                'db_table': 'subject_versions',
                'ordering': ('subject_id', 'version_no', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['user', 'status', 'created_at'], name='subject_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_type', 'status', 'created_at'], name='subject_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'active', 'archived'))), name='subject_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='subject_schema_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('schema_snapshot_format_version', 1)), name='subject_schema_format_v1'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectcontext',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_context_version_gte_1'),
        ),
        migrations.AddIndex(
            model_name='subjectevent',
            index=models.Index(fields=['subject', 'created_at'], name='subject_event_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectversion',
            constraint=models.UniqueConstraint(fields=('subject', 'version_no'), name='subject_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjectversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='subject_version_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectversion',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='subject_version_schema_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectversion',
            constraint=models.CheckConstraint(condition=models.Q(('schema_snapshot_format_version', 1)), name='subject_version_schema_format_v1'),
        ),
    ]
