# Generated by Django 5.2.16 on 2026-08-11 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_rbac', '0016_seed_subject_catalog_permissions'),
        ('subjects', '0007_subject_version_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('superseded', '已被新版本替代')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='subjects.subject')),
                ('subject_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='subjects.subjectversion')),
            ],
            options={
                'db_table': 'subject_reviews',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('requested', '已进入审核'), ('approved', '审核通过'), ('rejected', '审核拒绝'), ('superseded', '已被新版本替代')], max_length=16)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('superseded', '已被新版本替代')], max_length=16)),
                ('safe_summary', models.JSONField(default=dict)),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_review_events', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='subjects.subjectreview')),
            ],
            options={
                'db_table': 'subject_review_events',
            },
        ),
        migrations.CreateModel(
            name='SubjectRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_digest', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('clear', '自动检查通过'), ('restricted', '自动限制'), ('review_required', '需要人工审核')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment', to='subjects.subjectversion')),
            ],
            options={
                'db_table': 'subject_risk_assessments',
                'ordering': ('subject_version_id', 'id'),
            },
        ),
        migrations.AddField(
            model_name='subjectreview',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='subjects.subjectriskassessment'),
        ),
        migrations.CreateModel(
            name='SubjectRiskCatalogRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveBigIntegerField(unique=True)),
                ('format_version', models.PositiveSmallIntegerField(default=1)),
                ('snapshot', models.JSONField()),
                ('snapshot_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_risk_catalog_revision', to='admin_rbac.approvalrequest')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_subject_risk_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_risk_catalog_revisions',
                'ordering': ('-revision_no', 'id'),
            },
        ),
        migrations.AddField(
            model_name='subjectriskassessment',
            name='catalog_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='subjects.subjectriskcatalogrevision'),
        ),
        migrations.CreateModel(
            name='SubjectRiskCatalogState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for_state', to='subjects.subjectriskcatalogrevision')),
            ],
            options={
                'db_table': 'subject_risk_catalog_state',
            },
        ),
        migrations.CreateModel(
            name='SubjectRiskHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_type_key', models.CharField(max_length=64)),
                ('rule_key', models.CharField(max_length=64)),
                ('reason_type', models.CharField(choices=[('suspected_violation', '疑似违规'), ('suspected_impersonation', '疑似冒用'), ('data_conflict', '资料冲突'), ('high_risk_industry', '高风险行业')], max_length=32)),
                ('field_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='subjects.subjectriskassessment')),
            ],
            options={
                'db_table': 'subject_risk_hits',
                'ordering': ('assessment_id', 'rule_key', 'field_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectRiskType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('enabled', models.BooleanField(default=False)),
                ('manual_review_required', models.BooleanField(default=True)),
                ('allow_geo_detection', models.BooleanField(default=False)),
                ('allow_article_generation', models.BooleanField(default=False)),
                ('allow_image_generation', models.BooleanField(default=False)),
                ('require_authoritative_citations', models.BooleanField(default=True)),
                ('require_disclaimer', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_risk_types', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subject_risk_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_risk_types',
                'ordering': ('sort_order', 'key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectRiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('field_key', models.CharField(blank=True, max_length=64)),
                ('operator', models.CharField(choices=[('equals_any', '等于任一值'), ('contains_any', '包含任一值')], max_length=16)),
                ('patterns', models.JSONField(default=list)),
                ('reason_type', models.CharField(choices=[('suspected_violation', '疑似违规'), ('suspected_impersonation', '疑似冒用'), ('data_conflict', '资料冲突'), ('high_risk_industry', '高风险行业')], max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subject_risk_rules', to=settings.AUTH_USER_MODEL)),
                ('subject_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_rules', to='subjects.subjecttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subject_risk_rules', to=settings.AUTH_USER_MODEL)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='subjects.subjectrisktype')),
            ],
            options={
                'db_table': 'subject_risk_rules',
                'ordering': ('priority', 'key', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='subjectreview',
            index=models.Index(fields=['status', 'created_at', 'id'], name='subject_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectreview',
            index=models.Index(fields=['subject', 'created_at', 'id'], name='subject_review_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectreview',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'approved', 'rejected', 'superseded'))), name='subject_review_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='subjectreview',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_review_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskcatalogrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_no__gte', 1)), name='subject_risk_revision_no_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskcatalogrevision',
            constraint=models.CheckConstraint(condition=models.Q(('format_version', 1)), name='subject_risk_revision_format_v1'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ('clear', 'restricted', 'review_required'))), name='subject_risk_assessment_valid_outcome'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskcatalogstate',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='subject_risk_state_singleton'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskcatalogstate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_risk_state_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskhit',
            constraint=models.UniqueConstraint(fields=('assessment', 'rule_key', 'field_key'), name='subject_risk_hit_rule_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjectrisktype',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_risk_type_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskrule',
            constraint=models.CheckConstraint(condition=models.Q(('operator__in', ('equals_any', 'contains_any'))), name='subject_risk_rule_valid_operator'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskrule',
            constraint=models.CheckConstraint(condition=models.Q(('reason_type__in', ('suspected_violation', 'suspected_impersonation', 'data_conflict', 'high_risk_industry'))), name='subject_risk_rule_valid_reason'),
        ),
        migrations.AddConstraint(
            model_name='subjectriskrule',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='subject_risk_rule_version_gte_1'),
        ),
    ]
