import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subjects", "0011_catalog_publish_binding_and_review_boundaries"),
        ("documents", "0005_parse_state_pointer_consistency"),
        ("web_sources", "0002_postgresql_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectEnrichmentJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("retry_wait", "Retry wait"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="queued", max_length=16)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("subject_object_version_at_create", models.PositiveBigIntegerField()),
                ("current_formal_subject_version_id_at_create", models.UUIDField(blank=True, null=True)),
                ("schema_digest", models.CharField(max_length=64)),
                ("schema_snapshot_format_version", models.PositiveSmallIntegerField(default=1)),
                ("target_manifest", models.JSONField(default=list)),
                ("input_subject_values", models.JSONField(default=dict)),
                ("provider_key", models.CharField(max_length=32)),
                ("model_key", models.CharField(max_length=64)),
                ("adapter_version", models.CharField(max_length=32)),
                ("prompt_version", models.CharField(max_length=32)),
                ("input_digest", models.CharField(max_length=64)),
                ("output_digest", models.CharField(blank=True, max_length=64)),
                ("idempotency_key_version", models.PositiveSmallIntegerField(default=1)),
                ("idempotency_key_digest", models.CharField(max_length=64, unique=True)),
                ("request_digest", models.CharField(max_length=64)),
                ("generation", models.UUIDField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("stable_error_code", models.CharField(blank=True, max_length=64)),
                ("provider_metrics", models.JSONField(default=dict)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="enrichment_jobs", to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subject_enrichment_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "subject_enrichment_jobs", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="SubjectEnrichmentSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_type", models.CharField(choices=[("document", "Document"), ("web", "Web")], max_length=16)),
                ("content_digest", models.CharField(max_length=64)),
                ("input_characters", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document_parsed_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subject_enrichment_sources", to="documents.documentparsedversion")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sources", to="subjects.subjectenrichmentjob")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("web_parsed_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subject_enrichment_sources", to="web_sources.websourceparsedversion")),
            ],
            options={"db_table": "subject_enrichment_sources", "ordering": ("job_id", "source_type", "id")},
        ),
        migrations.CreateModel(
            name="SubjectEnrichmentSuggestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("field_key", models.CharField(max_length=64)),
                ("suggested_value", models.JSONField(blank=True, null=True)),
                ("value_digest", models.CharField(max_length=64)),
                ("confidence", models.CharField(choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")], max_length=16)),
                ("conflict", models.BooleanField(default=False)),
                ("conflict_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="suggestions", to="subjects.subjectenrichmentjob")),
            ],
            options={"db_table": "subject_enrichment_suggestions", "ordering": ("job_id", "field_key", "id")},
        ),
        migrations.CreateModel(
            name="SubjectEnrichmentSuggestionSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="suggestion_links", to="subjects.subjectenrichmentsource")),
                ("suggestion", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="source_links", to="subjects.subjectenrichmentsuggestion")),
            ],
            options={"db_table": "subject_enrichment_suggestion_sources"},
        ),
        migrations.CreateModel(
            name="SubjectEnrichmentConfirmation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_version_before", models.PositiveBigIntegerField()),
                ("subject_version_after", models.PositiveBigIntegerField()),
                ("request_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="confirmed_subject_enrichments", to=settings.AUTH_USER_MODEL)),
                ("job", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="confirmation", to="subjects.subjectenrichmentjob")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="subjects.subject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "subject_enrichment_confirmations"},
        ),
        migrations.CreateModel(
            name="SubjectEnrichmentDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("accepted", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="decisions", to="subjects.subjectenrichmentconfirmation")),
                ("suggestion", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="decision", to="subjects.subjectenrichmentsuggestion")),
            ],
            options={"db_table": "subject_enrichment_decisions"},
        ),
        migrations.CreateModel(
            name="SubjectEnrichmentEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(choices=[("started", "Started"), ("retry_scheduled", "Retry scheduled"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("applied", "Applied")], max_length=24)),
                ("stable_error_code", models.CharField(blank=True, max_length=64)),
                ("safe_summary", models.JSONField(default=dict)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subject_enrichment_events", to=settings.AUTH_USER_MODEL)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="subjects.subjectenrichmentjob")),
            ],
            options={"db_table": "subject_enrichment_events", "ordering": ("job_id", "created_at", "id")},
        ),
        migrations.AddIndex(model_name="subjectenrichmentjob", index=models.Index(fields=["subject", "status", "created_at"], name="subj_enrich_status_idx")),
        migrations.AddIndex(model_name="subjectenrichmentjob", index=models.Index(fields=["status", "next_attempt_at"], name="subj_enrich_retry_idx")),
        migrations.AddConstraint(model_name="subjectenrichmentjob", constraint=models.UniqueConstraint(condition=models.Q(("status__in", ("queued", "running", "retry_wait"))), fields=("subject",), name="subject_enrichment_one_open")),
        migrations.AddConstraint(model_name="subjectenrichmentjob", constraint=models.CheckConstraint(condition=models.Q(("status__in", ("queued", "running", "retry_wait", "succeeded", "failed"))), name="subject_enrichment_valid_status")),
        migrations.AddConstraint(model_name="subjectenrichmentjob", constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="subject_enrichment_version_gte_1")),
        migrations.AddConstraint(model_name="subjectenrichmentjob", constraint=models.CheckConstraint(condition=models.Q(("subject_object_version_at_create__gte", 1)), name="subject_enrichment_subject_ver_gte_1")),
        migrations.AddConstraint(model_name="subjectenrichmentjob", constraint=models.CheckConstraint(condition=models.Q(("attempts__gte", 0)) & models.Q(("retry_count__gte", 0)), name="subject_enrichment_retry_counts")),
        migrations.AddConstraint(model_name="subjectenrichmentjob", constraint=models.CheckConstraint(condition=(models.Q(status="queued", generation__isnull=True, started_at__isnull=True, finished_at__isnull=True) | models.Q(status="running", generation__isnull=False, started_at__isnull=False, finished_at__isnull=True) | models.Q(status="retry_wait", generation__isnull=False, next_attempt_at__isnull=False, finished_at__isnull=True) | models.Q(status__in=("succeeded", "failed"), generation__isnull=False, finished_at__isnull=False)), name="subject_enrichment_status_fields")),
        migrations.AddConstraint(model_name="subjectenrichmentsource", constraint=models.CheckConstraint(condition=(models.Q(source_type="document", document_parsed_version__isnull=False, web_parsed_version__isnull=True) | models.Q(source_type="web", document_parsed_version__isnull=True, web_parsed_version__isnull=False)), name="subject_enrichment_source_binding")),
        migrations.AddConstraint(model_name="subjectenrichmentsource", constraint=models.CheckConstraint(condition=models.Q(("input_characters__gte", 1)), name="subject_enrichment_source_chars")),
        migrations.AddConstraint(model_name="subjectenrichmentsource", constraint=models.UniqueConstraint(condition=models.Q(("source_type", "document")), fields=("job", "document_parsed_version"), name="subj_enrich_doc_source_unique")),
        migrations.AddConstraint(model_name="subjectenrichmentsource", constraint=models.UniqueConstraint(condition=models.Q(("source_type", "web")), fields=("job", "web_parsed_version"), name="subj_enrich_web_source_unique")),
        migrations.AddConstraint(model_name="subjectenrichmentsuggestion", constraint=models.UniqueConstraint(fields=("job", "field_key"), name="subject_enrichment_job_field_unique")),
        migrations.AddConstraint(model_name="subjectenrichmentsuggestion", constraint=models.CheckConstraint(condition=models.Q(("confidence__in", ("high", "medium", "low"))), name="subject_enrichment_confidence_valid")),
        migrations.AddConstraint(model_name="subjectenrichmentsuggestionsource", constraint=models.UniqueConstraint(fields=("suggestion", "source"), name="subject_enrichment_citation_unique")),
        migrations.AddConstraint(model_name="subjectenrichmentconfirmation", constraint=models.CheckConstraint(condition=models.Q(("subject_version_before__gte", 1)), name="subject_enrichment_confirm_before_gte_1")),
        migrations.AddConstraint(model_name="subjectenrichmentconfirmation", constraint=models.CheckConstraint(condition=(models.Q(subject_version_after=models.F("subject_version_before")) | models.Q(subject_version_after=models.F("subject_version_before") + 1)), name="subject_enrichment_confirm_version_step")),
        migrations.AddConstraint(model_name="subjectenrichmentevent", constraint=models.CheckConstraint(condition=models.Q(("event_type__in", ("started", "retry_scheduled", "succeeded", "failed", "applied"))), name="subject_enrichment_event_type_valid")),
    ]
