# Generated by Django 5.2.17 on 2026-08-31 04:35

import uuid
from importlib import import_module

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, F

_previous_guard_migration = import_module(
    "apps.subjects.migrations.0005_subject_data_postgresql_guards"
)
PREVIOUS_GUARDS = _previous_guard_migration.INSTALL_SQL
PREVIOUS_GUARDS_REMOVE = _previous_guard_migration.REMOVE_SQL


SINGLE_SUBJECT_GUARDS = r"""
CREATE OR REPLACE FUNCTION subjects_guard_subject() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'SUBJECT_DELETE_FORBIDDEN';
    END IF;
    IF ROW(
        NEW.user_id, NEW.tenant_id, NEW.subject_type_id, NEW.schema_version,
        NEW.schema_snapshot_format_version, NEW.schema_snapshot, NEW.schema_digest,
        NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.user_id, OLD.tenant_id, OLD.subject_type_id, OLD.schema_version,
        OLD.schema_snapshot_format_version, OLD.schema_snapshot, OLD.schema_digest,
        OLD.created_at
    ) THEN
        RAISE EXCEPTION 'SUBJECT_IMMUTABLE_BINDING';
    END IF;
    IF OLD.status = 'archived' AND NEW.draft_values IS DISTINCT FROM OLD.draft_values THEN
        RAISE EXCEPTION 'SUBJECT_ARCHIVED_READ_ONLY';
    END IF;
    IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
        (OLD.status = 'draft' AND NEW.status IN ('active', 'archived')) OR
        (OLD.status = 'active' AND NEW.status = 'archived') OR
        (OLD.status = 'archived' AND NEW.status = 'active')
    ) THEN
        RAISE EXCEPTION 'SUBJECT_STATE_CONFLICT';
    END IF;
    IF (
        NEW.status IS DISTINCT FROM OLD.status OR
        NEW.draft_values IS DISTINCT FROM OLD.draft_values
    ) AND NEW.version <> OLD.version + 1 THEN
        RAISE EXCEPTION 'SUBJECT_VERSION_CONFLICT';
    END IF;
    IF NEW.version < OLD.version THEN
        RAISE EXCEPTION 'SUBJECT_VERSION_CONFLICT';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION subjects_assert_context(p_user_id uuid) RETURNS void AS $$
DECLARE
    v_current_subject_id uuid;
BEGIN
    SELECT current_subject_id INTO v_current_subject_id
    FROM subject_contexts
    WHERE user_id = p_user_id;
    IF NOT FOUND OR v_current_subject_id IS NULL THEN
        RETURN;
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM subjects s
        JOIN users_user u ON u.id = p_user_id
        WHERE s.id = v_current_subject_id
          AND s.status = 'active'
          AND (
              (s.tenant_id IS NOT NULL AND s.tenant_id = u.tenant_id) OR
              (s.tenant_id IS NULL AND s.user_id = p_user_id)
          )
    ) THEN
        RAISE EXCEPTION 'SUBJECT_CONTEXT_INVALID'
            USING ERRCODE = 'check_violation';
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION subjects_validate_context_from_subject() RETURNS trigger AS $$
DECLARE
    v_user_id uuid;
BEGIN
    FOR v_user_id IN
        SELECT DISTINCT user_id
        FROM subject_contexts
        WHERE current_subject_id IN (NEW.id, OLD.id)
    LOOP
        PERFORM subjects_assert_context(v_user_id);
    END LOOP;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION subjects_guard_identity_audit() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'SUBJECT_IDENTITY_AUDIT_IMMUTABLE';
    END IF;
    RAISE EXCEPTION 'SUBJECT_IDENTITY_AUDIT_DELETE_FORBIDDEN';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS subjects_identity_audit_guard ON subject_identity_correction_events;
CREATE TRIGGER subjects_identity_audit_guard
BEFORE UPDATE OR DELETE ON subject_identity_correction_events
FOR EACH ROW EXECUTE FUNCTION subjects_guard_identity_audit();
"""


def backfill_workspace_and_identity(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    SubjectBusinessProfile = apps.get_model("subjects", "SubjectBusinessProfile")
    SubjectVersion = apps.get_model("subjects", "SubjectVersion")
    User = apps.get_model("users", "User")

    user_tenants = dict(User.objects.values_list("id", "tenant_id"))
    profiles = dict(
        SubjectBusinessProfile.objects.values_list("subject_id", "unified_social_credit_code")
    )
    version_ids = list(
        Subject.objects.exclude(current_version_id=None).values_list(
            "current_version_id", flat=True
        )
    )
    versions = {
        row[0]: row[1:]
        for row in SubjectVersion.objects.filter(pk__in=version_ids).values_list(
            "id", "official_name", "created_at"
        )
    }
    for subject in Subject.objects.all().iterator():
        updates = {"tenant_id": user_tenants.get(subject.user_id)}
        if subject.current_version_id in versions:
            official_name, created_at = versions[subject.current_version_id]
            updates.update(
                identity_bound_at=created_at,
                bound_official_name=(official_name or "").strip(),
                bound_unified_social_credit_code=(profiles.get(subject.pk) or "").strip().upper(),
            )
        Subject.objects.filter(pk=subject.pk).update(**updates)


def reconcile_existing_active_subjects(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    SubjectContext = apps.get_model("subjects", "SubjectContext")
    User = apps.get_model("users", "User")

    def reconcile(subject_filter, context_user_filter, label):
        active_ids = list(
            Subject.objects.filter(**subject_filter, status="active").values_list("id", flat=True)
        )
        if len(active_ids) <= 1:
            return
        current_ids = set(
            SubjectContext.objects.filter(
                **context_user_filter,
                current_subject_id__in=active_ids,
            ).values_list("current_subject_id", flat=True)
        )
        if len(current_ids) != 1:
            raise RuntimeError(
                f"Cannot safely choose the bound subject for {label}; manual confirmation required."
            )
        winner_id = current_ids.pop()
        loser_ids = [subject_id for subject_id in active_ids if subject_id != winner_id]
        Subject.objects.filter(pk__in=loser_ids).update(status="archived", version=F("version") + 1)
        SubjectContext.objects.filter(
            **context_user_filter, current_subject_id__in=loser_ids
        ).update(current_subject_id=winner_id, version=F("version") + 1)

    tenant_ids = (
        Subject.objects.filter(status="active", tenant_id__isnull=False)
        .values("tenant_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .values_list("tenant_id", flat=True)
    )
    for tenant_id in tenant_ids:
        reconcile(
            {"tenant_id": tenant_id},
            {"user_id__in": User.objects.filter(tenant_id=tenant_id).values("id")},
            f"tenant {tenant_id}",
        )

    user_ids = (
        Subject.objects.filter(status="active", tenant_id__isnull=True)
        .values("user_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .values_list("user_id", flat=True)
    )
    for user_id in user_ids:
        reconcile(
            {"tenant_id__isnull": True, "user_id": user_id},
            {"user_id": user_id},
            f"independent workspace {user_id}",
        )


def install_single_subject_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SINGLE_SUBJECT_GUARDS)


def flush_pending_constraint_events(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def restore_previous_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS subjects_identity_audit_guard "
            "ON subject_identity_correction_events;"
        )
        schema_editor.execute("DROP FUNCTION IF EXISTS subjects_guard_identity_audit();")
        schema_editor.execute(PREVIOUS_GUARDS_REMOVE)
        schema_editor.execute(PREVIOUS_GUARDS)


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0018_subject_management_profile"),
        ("users", "0014_user_appearance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectIdentityCorrectionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("old_identity", models.JSONField()),
                ("new_identity", models.JSONField()),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subject_identity_correction_events",
                "ordering": ("subject_id", "created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="bound_official_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="subject",
            name="bound_unified_social_credit_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="subject",
            name="identity_bound_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="users.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["tenant", "status", "created_at"], name="subject_tenant_status_idx"
            ),
        ),
        migrations.AddField(
            model_name="subjectidentitycorrectionevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_identity_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subjectidentitycorrectionevent",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identity_correction_events",
                to="subjects.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectidentitycorrectionevent",
            index=models.Index(fields=["subject", "created_at"], name="subject_identity_audit_idx"),
        ),
        migrations.RunPython(backfill_workspace_and_identity, migrations.RunPython.noop),
        migrations.RunPython(install_single_subject_guards, restore_previous_guards),
        migrations.RunPython(reconcile_existing_active_subjects, migrations.RunPython.noop),
        migrations.RunPython(flush_pending_constraint_events, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active"), ("tenant__isnull", False)),
                fields=("tenant",),
                name="subject_one_active_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active"), ("tenant__isnull", True)),
                fields=("user",),
                name="subject_one_active_per_user_workspace",
            ),
        ),
    ]
