# Generated by Django 5.2.16 on 2026-08-11 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotas', '0009_lifecycle_postgresql_guards'),
        ('subjects', '0011_catalog_publish_binding_and_review_boundaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('detected_file_kind', models.CharField(max_length=16)),
                ('detected_mime', models.CharField(max_length=127)),
                ('security_validation_version', models.PositiveSmallIntegerField(default=1)),
                ('scanner_engine_version', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_versions',
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('subject_library', 'Subject library')], max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_document', to='documents.documentversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_documents',
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.userdocument'),
        ),
        migrations.CreateModel(
            name='FileStorageAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consume_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotas.quotaledgerentry')),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='storage_allocation', to='documents.documentversion')),
                ('quota_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotas.quotaaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_storage_allocations',
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='file_allocation_size_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='FileUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('subject_library', 'Subject library')], max_length=32)),
                ('declared_filename', models.CharField(max_length=255)),
                ('declared_content_type', models.CharField(max_length=127)),
                ('declared_size', models.BigIntegerField()),
                ('declared_file_kind', models.CharField(max_length=16)),
                ('staging_key', models.CharField(max_length=255, unique=True)),
                ('final_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending_upload', 'Pending upload'), ('verifying', 'Verifying'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_upload', max_length=24)),
                ('version', models.BigIntegerField(default=1)),
                ('idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('verification_generation', models.UUIDField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('staging_cleanup_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_intent', to='documents.documentversion')),
                ('quota_hold_group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='file_upload_intent', to='quotas.quotaholdgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_upload_intents',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='file_intent_expiry_idx'), models.Index(fields=['status', 'next_attempt_at'], name='file_intent_retry_idx'), models.Index(fields=['user', 'subject', 'created_at'], name='file_intent_owner_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('declared_size__gt', 0)), name='file_intent_size_gt_0'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='file_intent_version_gte_1'), models.CheckConstraint(condition=models.Q(models.Q(('completed_version__isnull', False), ('status', 'completed')), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_version__isnull', True)), _connector='OR'), name='file_intent_completed_version_state')],
            },
        ),
        migrations.CreateModel(
            name='SubjectVersionDocumentReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_version_references', to='documents.documentversion')),
                ('subject_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_references', to='subjects.subjectversion')),
            ],
            options={
                'db_table': 'subject_version_document_references',
                'constraints': [models.UniqueConstraint(fields=('subject_version', 'field_key'), name='subject_version_document_field_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='userdocument',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='document_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_no'), name='document_version_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='document_version_no_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='document_size_gt_0'),
        ),
    ]
