# Generated by Django 5.2.16 on 2026-08-12 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_postgresql_guards'),
        ('subjects', '0011_catalog_publish_binding_and_review_boundaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentParsedVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('parser', 'Parser'), ('user_confirmation', 'User confirmation')], max_length=24)),
                ('extracted_text', models.TextField()),
                ('tables_json', models.JSONField(default=list)),
                ('warning_codes', models.JSONField(default=list)),
                ('parser_key', models.CharField(max_length=32)),
                ('parser_version', models.CharField(max_length=32)),
                ('ocr_provider_key', models.CharField(blank=True, max_length=32)),
                ('ocr_engine_version', models.CharField(blank=True, max_length=64)),
                ('content_digest', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_document_parse_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.userdocument')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parsed_versions', to='documents.documentversion')),
                ('machine_base_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='documents.documentparsedversion')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='documents.documentparsedversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_parsed_versions',
            },
        ),
        migrations.CreateModel(
            name='DocumentParseJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry_wait', 'Retry wait'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('parser_key', models.CharField(max_length=32)),
                ('parser_version', models.CharField(max_length=32)),
                ('ocr_provider_key', models.CharField(blank=True, max_length=32)),
                ('idempotency_key_version', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key_digest', models.CharField(max_length=64, unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('generation', models.UUIDField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.userdocument')),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parse_job', to='documents.documentversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_parse_jobs',
            },
        ),
        migrations.CreateModel(
            name='DocumentParseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('retry_scheduled', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], max_length=24)),
                ('stable_error_code', models.CharField(blank=True, max_length=64)),
                ('safe_summary', models.JSONField(default=dict)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_parse_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.userdocument')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documentversion')),
                ('parsed_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='documents.documentparsedversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='documents.documentparsejob')),
            ],
            options={
                'db_table': 'document_parse_events',
            },
        ),
        migrations.CreateModel(
            name='DocumentParseState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_confirmed_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_for_state', to='documents.documentparsedversion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.userdocument')),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parse_state', to='documents.documentversion')),
                ('latest_parsed_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_state', to='documents.documentparsedversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_parse_states',
            },
        ),
        migrations.AddConstraint(
            model_name='documentparsedversion',
            constraint=models.UniqueConstraint(fields=('document_version', 'version_no'), name='parsed_version_no_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentparsedversion',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'user_confirmation')), fields=('parent_version', 'content_digest'), name='parsed_confirmation_replay_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentparsedversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='parsed_version_no_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='documentparsedversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('machine_base_version__isnull', True), ('parent_version__isnull', True), ('source', 'parser'), ('version_no', 1)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('machine_base_version__isnull', False), ('parent_version__isnull', False), ('source', 'user_confirmation')), _connector='OR'), name='parsed_version_source_fields'),
        ),
        migrations.AddIndex(
            model_name='documentparsejob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='parse_job_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='documentparsejob',
            index=models.Index(fields=['user', 'subject', 'created_at'], name='parse_job_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentparsejob',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='parse_job_attempts_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='documentparsejob',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0)), name='parse_job_retry_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='documentparsejob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('generation__isnull', True), ('status', 'queued')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('started_at__isnull', False), ('status', 'running')), models.Q(('finished_at__isnull', True), ('generation__isnull', False), ('next_attempt_at__isnull', False), ('status', 'retry_wait')), models.Q(('finished_at__isnull', False), ('generation__isnull', False), ('status__in', ('succeeded', 'failed'))), _connector='OR'), name='parse_job_status_fields'),
        ),
        migrations.AddIndex(
            model_name='documentparseevent',
            index=models.Index(fields=['document_version', 'created_at'], name='parse_event_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentparsestate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='parse_state_version_gte_1'),
        ),
    ]
