# Generated by Django 5.2.17 on 2026-08-31 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0015_add_quota_refund_action'),
        ('source_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceindexscan',
            name='quota_hold',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_index_scan', to='quotas.quotaholdgroup'),
        ),
        migrations.AddField(
            model_name='sourceindexscan',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
