# Generated for XW-0412~XW-0414 Detection Execution Core.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0004_api_credential_postgresql_guards"),
        ("keywords", "0007_distillation_postgresql_guards"),
        ("plans", "0013_lifecycle_postgresql_guards"),
        ("questions", "0005_question_bank_postgresql_guards"),
        ("quotas", "0012_subject_cycle_postgresql_guards"),
        ("subjects", "0013_subject_enrichment_postgresql_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoDetectionJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("partial", "Partial"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=16)),
                ("mode", models.CharField(default="new", max_length=16)),
                ("planned_question_count", models.PositiveIntegerField()),
                ("planned_model_count", models.PositiveIntegerField()),
                ("planned_detection_points", models.PositiveBigIntegerField()),
                ("completed_calls", models.PositiveBigIntegerField(default=0)),
                ("successful_calls", models.PositiveBigIntegerField(default=0)),
                ("failed_calls", models.PositiveBigIntegerField(default=0)),
                ("cancelled_calls", models.PositiveBigIntegerField(default=0)),
                ("queue_priority", models.PositiveIntegerField()),
                ("idempotency_key_version", models.PositiveSmallIntegerField(default=1)),
                ("idempotency_key_digest", models.CharField(max_length=64, unique=True)),
                ("request_digest", models.CharField(max_length=64)),
                ("request_id", models.UUIDField()),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quota_hold", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_job", to="quotas.quotaholdgroup")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_jobs", to="subjects.subject")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_jobs", to="plans.subscription")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "geo_detection_jobs", "ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="GeoDetectionSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("entitlement_snapshot", models.JSONField()),
                ("model_snapshots", models.JSONField()),
                ("system_prompt", models.TextField()),
                ("prompt_version", models.CharField(max_length=64)),
                ("scoring_rule_version", models.CharField(max_length=64)),
                ("input_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("distillation_set", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_snapshots", to="keywords.distillationset")),
                ("job", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="snapshot", to="geo.geodetectionjob")),
                ("keyword_set_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_snapshots", to="keywords.keywordsetversion")),
                ("question_bank_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_snapshots", to="questions.questionbankversion")),
                ("subject_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_snapshots", to="subjects.subjectversion")),
            ],
            options={"db_table": "geo_detection_snapshots"},
        ),
        migrations.CreateModel(
            name="GeoDetectionQuestionSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=1000)),
                ("primary_category_key", models.CharField(max_length=100)),
                ("primary_category_name", models.CharField(max_length=150)),
                ("primary_category_version", models.PositiveBigIntegerField()),
                ("priority", models.CharField(max_length=16)),
                ("question_type", models.CharField(max_length=24)),
                ("participates_in_scoring", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField()),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="questions", to="geo.geodetectionsnapshot")),
                ("source_question", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_detection_snapshots", to="questions.question")),
            ],
            options={"db_table": "geo_detection_question_snapshots", "ordering": ("snapshot_id", "sort_order", "id")},
        ),
        migrations.CreateModel(
            name="GeoDetectionModelRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_key", models.CharField(max_length=100)),
                ("model_key", models.CharField(max_length=100)),
                ("provider_model_id", models.CharField(max_length=255)),
                ("runtime_snapshot", models.JSONField()),
                ("adapter_version", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("partial", "Partial"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=16)),
                ("planned_calls", models.PositiveIntegerField()),
                ("completed_calls", models.PositiveIntegerField(default=0)),
                ("successful_calls", models.PositiveIntegerField(default=0)),
                ("failed_calls", models.PositiveIntegerField(default=0)),
                ("cancelled_calls", models.PositiveIntegerField(default=0)),
                ("web_search_used_count", models.PositiveIntegerField(default=0)),
                ("degraded_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="model_runs", to="geo.geodetectionjob")),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_model_runs", to="ai.aimodel")),
            ],
            options={"db_table": "geo_detection_model_runs", "ordering": ("job_id", "model_id")},
        ),
        migrations.CreateModel(
            name="ModelCall",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_key", models.CharField(max_length=100)),
                ("model_key", models.CharField(max_length=100)),
                ("provider_model_id", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("retry_wait", "Retry wait"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=16)),
                ("settlement_status", models.CharField(choices=[("pending", "Pending"), ("consumed", "Consumed"), ("released", "Released")], default="pending", max_length=16)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("generation", models.UUIDField(blank=True, null=True)),
                ("web_search_requested", models.BooleanField(default=False)),
                ("web_search_used", models.BooleanField(default=False)),
                ("degraded", models.BooleanField(default=False)),
                ("finish_reason", models.CharField(blank=True, max_length=32)),
                ("provider_request_id", models.CharField(blank=True, max_length=128)),
                ("stable_error_code", models.CharField(blank=True, max_length=100)),
                ("safe_error_summary", models.JSONField(default=dict)),
                ("input_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                ("latency_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ("cost_currency", models.CharField(blank=True, max_length=3)),
                ("queued_at", models.DateTimeField()),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="model_calls", to="geo.geodetectionjob")),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="geo_model_calls", to="ai.aimodel")),
                ("model_run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="calls", to="geo.geodetectionmodelrun")),
                ("question_snapshot", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="model_calls", to="geo.geodetectionquestionsnapshot")),
            ],
            options={"db_table": "model_calls", "ordering": ("job_id", "queued_at", "id")},
        ),
        migrations.CreateModel(
            name="ModelCallAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("attempt_no", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], max_length=16)),
                ("provider_request_id", models.CharField(blank=True, max_length=128)),
                ("error_category", models.CharField(blank=True, max_length=64)),
                ("stable_error_code", models.CharField(blank=True, max_length=100)),
                ("retryable", models.BooleanField(default=False)),
                ("input_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveBigIntegerField(blank=True, null=True)),
                ("latency_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("finish_reason", models.CharField(blank=True, max_length=32)),
                ("provider_metadata", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_call", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attempts", to="geo.modelcall")),
            ],
            options={"db_table": "model_call_attempts", "ordering": ("model_call_id", "attempt_no", "id")},
        ),
        migrations.CreateModel(
            name="ModelResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_model_id", models.CharField(max_length=255)),
                ("raw_text", models.TextField()),
                ("raw_text_sha256", models.CharField(max_length=64)),
                ("provider_metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_call", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="response", to="geo.modelcall")),
            ],
            options={"db_table": "model_responses"},
        ),
        migrations.AddIndex(model_name="geodetectionjob", index=models.Index(fields=["user", "status", "created_at"], name="geo_job_user_status_idx")),
        migrations.AddIndex(model_name="geodetectionjob", index=models.Index(fields=["status", "queue_priority", "queued_at"], name="geo_job_queue_idx")),
        migrations.AddIndex(model_name="geodetectionjob", index=models.Index(fields=["subject", "created_at"], name="geo_job_subject_idx")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("status__in", ("queued", "running", "partial", "succeeded", "failed", "cancelled"))), name="geo_job_status_valid")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("mode", "new")), name="geo_job_mode_valid")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("planned_question_count__gte", 1)), name="geo_job_questions_gte_1")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("planned_model_count__gte", 1)), name="geo_job_models_gte_1")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("planned_detection_points__gte", 1)), name="geo_job_points_gte_1")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("planned_detection_points", models.F("planned_question_count") * models.F("planned_model_count"))), name="geo_job_points_match_matrix")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("queue_priority__gte", 0), ("queue_priority__lte", 1000)), name="geo_job_priority_range")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="geo_job_version_gte_1")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("completed_calls", models.F("successful_calls") + models.F("failed_calls") + models.F("cancelled_calls"))), name="geo_job_completed_sum")),
        migrations.AddConstraint(model_name="geodetectionjob", constraint=models.CheckConstraint(condition=models.Q(("completed_calls__lte", models.F("planned_detection_points"))), name="geo_job_completed_lte_planned")),
        migrations.AddConstraint(model_name="geodetectionsnapshot", constraint=models.CheckConstraint(condition=~models.Q(("input_digest", "")), name="geo_snapshot_digest_present")),
        migrations.AddConstraint(model_name="geodetectionsnapshot", constraint=models.CheckConstraint(condition=~models.Q(("prompt_version", "")), name="geo_snapshot_prompt_present")),
        migrations.AddConstraint(model_name="geodetectionsnapshot", constraint=models.CheckConstraint(condition=~models.Q(("scoring_rule_version", "")), name="geo_snapshot_scoring_present")),
        migrations.AddConstraint(model_name="geodetectionquestionsnapshot", constraint=models.UniqueConstraint(fields=("snapshot", "source_question"), name="geo_question_snapshot_unique")),
        migrations.AddConstraint(model_name="geodetectionquestionsnapshot", constraint=models.UniqueConstraint(fields=("snapshot", "sort_order"), name="geo_question_snapshot_sort_unique")),
        migrations.AddConstraint(model_name="geodetectionmodelrun", constraint=models.UniqueConstraint(fields=("job", "model"), name="geo_model_run_unique")),
        migrations.AddConstraint(model_name="geodetectionmodelrun", constraint=models.CheckConstraint(condition=models.Q(("status__in", ("queued", "running", "partial", "succeeded", "failed", "cancelled"))), name="geo_model_run_status_valid")),
        migrations.AddConstraint(model_name="geodetectionmodelrun", constraint=models.CheckConstraint(condition=models.Q(("planned_calls__gte", 1)), name="geo_model_run_planned_gte_1")),
        migrations.AddConstraint(model_name="geodetectionmodelrun", constraint=models.CheckConstraint(condition=models.Q(("completed_calls", models.F("successful_calls") + models.F("failed_calls") + models.F("cancelled_calls"))), name="geo_model_run_completed_sum")),
        migrations.AddConstraint(model_name="geodetectionmodelrun", constraint=models.CheckConstraint(condition=models.Q(("completed_calls__lte", models.F("planned_calls"))), name="geo_model_run_completed_lte_planned")),
        migrations.AddIndex(model_name="modelcall", index=models.Index(fields=["status", "next_attempt_at", "queued_at"], name="model_call_due_idx")),
        migrations.AddIndex(model_name="modelcall", index=models.Index(fields=["job", "status"], name="model_call_job_status_idx")),
        migrations.AddConstraint(model_name="modelcall", constraint=models.UniqueConstraint(fields=("job", "question_snapshot", "model"), name="model_call_unique")),
        migrations.AddConstraint(model_name="modelcall", constraint=models.CheckConstraint(condition=models.Q(("status__in", ("queued", "running", "retry_wait", "succeeded", "failed", "cancelled"))), name="model_call_status_valid")),
        migrations.AddConstraint(model_name="modelcall", constraint=models.CheckConstraint(condition=models.Q(("settlement_status__in", ("pending", "consumed", "released"))), name="model_call_settlement_valid")),
        migrations.AddConstraint(model_name="modelcall", constraint=models.CheckConstraint(condition=models.Q(models.Q(("settlement_status", "consumed"), ("status", "succeeded")), ~models.Q(("status", "succeeded")), _connector="OR"), name="model_call_success_consumed")),
        migrations.AddConstraint(model_name="modelcall", constraint=models.CheckConstraint(condition=models.Q(models.Q(("settlement_status", "released"), ("status__in", ("failed", "cancelled"))), ~models.Q(("status__in", ("failed", "cancelled"))), _connector="OR"), name="model_call_terminal_released")),
        migrations.AddConstraint(model_name="modelcallattempt", constraint=models.UniqueConstraint(fields=("model_call", "attempt_no"), name="model_call_attempt_unique")),
        migrations.AddConstraint(model_name="modelcallattempt", constraint=models.CheckConstraint(condition=models.Q(("attempt_no__gte", 1)), name="model_call_attempt_no_gte_1")),
        migrations.AddConstraint(model_name="modelcallattempt", constraint=models.CheckConstraint(condition=models.Q(("status__in", ("running", "succeeded", "failed"))), name="model_call_attempt_status_valid")),
        migrations.AddConstraint(model_name="modelresponse", constraint=models.CheckConstraint(condition=~models.Q(("raw_text", "")), name="model_response_text_present")),
        migrations.AddConstraint(model_name="modelresponse", constraint=models.CheckConstraint(condition=~models.Q(("raw_text_sha256", "")), name="model_response_hash_present")),
    ]
