# Generated by Django 5.2.17 on 2026-08-20 05:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

FORWARD_SQL = """
CREATE TRIGGER geo_competitor_entities_immutable
BEFORE UPDATE OR DELETE ON competitor_entities
FOR EACH ROW EXECUTE FUNCTION geo_reject_immutable_change();

CREATE TRIGGER geo_competitor_mentions_immutable
BEFORE UPDATE OR DELETE ON competitor_mentions
FOR EACH ROW EXECUTE FUNCTION geo_reject_immutable_change();

CREATE TRIGGER geo_competitor_dispositions_immutable
BEFORE UPDATE OR DELETE ON competitor_dispositions
FOR EACH ROW EXECUTE FUNCTION geo_reject_immutable_change();
"""

REVERSE_SQL = """
DROP TRIGGER IF EXISTS geo_competitor_dispositions_immutable ON competitor_dispositions;
DROP TRIGGER IF EXISTS geo_competitor_mentions_immutable ON competitor_mentions;
DROP TRIGGER IF EXISTS geo_competitor_entities_immutable ON competitor_entities;
"""


def install_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FORWARD_SQL)


def remove_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0005_score_results_model_scores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("canonical_name", models.CharField(max_length=255)),
                ("canonical_key", models.CharField(max_length=255)),
                ("aliases", models.JSONField(default=list)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("brand", "Brand"),
                            ("company", "Company"),
                            ("product", "Product"),
                        ],
                        max_length=16,
                    ),
                ),
                ("semantic_schema_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitor_entities",
                        to="geo.geodetectionjob",
                    ),
                ),
            ],
            options={
                "db_table": "competitor_entities",
            },
        ),
        migrations.CreateModel(
            name="CompetitorDisposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("competitor", "Competitor"),
                            ("not_competitor", "Not competitor"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitor_dispositions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispositions",
                        to="geo.competitorentity",
                    ),
                ),
            ],
            options={
                "db_table": "competitor_dispositions",
                "ordering": ("entity_id", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CompetitorMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                ("model_key", models.CharField(max_length=100)),
                ("occurrence", models.PositiveIntegerField()),
                ("recommendation_score", models.DecimalField(decimal_places=4, max_digits=7)),
                ("subject_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("competitor_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("rank_gap", models.IntegerField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("provenance", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mentions",
                        to="geo.competitorentity",
                    ),
                ),
                (
                    "score_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitor_mentions",
                        to="geo.scoreresult",
                    ),
                ),
            ],
            options={
                "db_table": "competitor_mentions",
            },
        ),
        migrations.AddConstraint(
            model_name="competitorentity",
            constraint=models.UniqueConstraint(
                fields=("job", "canonical_key"), name="competitor_entity_job_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitorentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("entity_type__in", ("brand", "company", "product"))),
                name="competitor_entity_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="competitordisposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ("competitor", "not_competitor"))),
                name="competitor_disposition_decision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="competitormention",
            constraint=models.UniqueConstraint(
                fields=("entity", "score_result"), name="competitor_mention_score_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitormention",
            constraint=models.CheckConstraint(
                condition=models.Q(("occurrence__gte", 1)),
                name="competitor_mention_occurrence_gte_1",
            ),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
