# Generated by Django 5.2.17 on 2026-08-20 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

FORWARD_SQL = r"""
DROP TRIGGER IF EXISTS geo_reports_immutable ON geo_reports;
CREATE TRIGGER geo_reports_immutable
BEFORE UPDATE OR DELETE ON geo_reports
FOR EACH ROW EXECUTE FUNCTION geo_reject_immutable_change();

DROP TRIGGER IF EXISTS report_exports_no_delete ON report_exports;
CREATE TRIGGER report_exports_no_delete
BEFORE DELETE ON report_exports
FOR EACH ROW EXECUTE FUNCTION geo_reject_history_delete();
"""

REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS geo_reports_immutable ON geo_reports;
DROP TRIGGER IF EXISTS report_exports_no_delete ON report_exports;
"""


def install_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FORWARD_SQL)


def remove_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_exposure_competitor_reference'),
        ('subjects', '0013_subject_enrichment_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retest_mode', models.CharField(blank=True, default='', max_length=16)),
                ('question_signature', models.CharField(max_length=64)),
                ('model_signature', models.CharField(max_length=64)),
                ('scoring_rule_version', models.CharField(max_length=64)),
                ('summary', models.JSONField()),
                ('provenance', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retests', to='geo.georeport')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='geo.geodetectionjob')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geo_reports', to='subjects.subject')),
                ('subject_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geo_reports', to='subjects.subjectversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geo_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geo_reports',
                'ordering': ('-generated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('brand_snapshot', models.JSONField(default=dict)),
                ('object_key', models.CharField(blank=True, default='', max_length=500)),
                ('safe_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='geo.georeport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_exports',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='georeport',
            constraint=models.CheckConstraint(condition=models.Q(('retest_mode__in', ('', 'quick', 'adjusted'))), name='geo_report_retest_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='georeport',
            constraint=models.CheckConstraint(condition=models.Q(('question_signature', ''), _negated=True), name='geo_report_question_sig_present'),
        ),
        migrations.AddConstraint(
            model_name='georeport',
            constraint=models.CheckConstraint(condition=models.Q(('model_signature', ''), _negated=True), name='geo_report_model_sig_present'),
        ),
        migrations.AddConstraint(
            model_name='georeport',
            constraint=models.CheckConstraint(condition=models.Q(('scoring_rule_version', ''), _negated=True), name='geo_report_rule_present'),
        ),
        migrations.AddConstraint(
            model_name='reportexport',
            constraint=models.CheckConstraint(condition=models.Q(('format__in', ('pdf', 'word', 'excel'))), name='report_export_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='reportexport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('queued', 'running', 'succeeded', 'failed'))), name='report_export_status_valid'),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
