# Generated by Django 5.2.17 on 2026-08-20 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models

FORWARD_SQL = r"""
DROP TRIGGER IF EXISTS geo_detection_retests_immutable ON geo_detection_retests;
CREATE TRIGGER geo_detection_retests_immutable
BEFORE UPDATE OR DELETE ON geo_detection_retests
FOR EACH ROW EXECUTE FUNCTION geo_reject_immutable_change();
"""

REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS geo_detection_retests_immutable ON geo_detection_retests;
"""


def install_guard(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FORWARD_SQL)


def remove_guard(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_georeport_reportexport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRetest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('quick', 'Quick'), ('adjusted', 'Adjusted')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detection_retests', to='geo.georeport')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retest_origin', to='geo.geodetectionjob')),
            ],
            options={
                'db_table': 'geo_detection_retests',
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ('quick', 'adjusted'))), name='geo_detection_retest_mode_valid')],
            },
        ),
        migrations.RunPython(install_guard, remove_guard),
    ]
