# Generated by Django 5.2.17 on 2026-08-20 10:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION geo_guard_strategy_report() RETURNS trigger AS $$
DECLARE report_row geo_reports%%ROWTYPE; hold_row quota_hold_groups%%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'STRATEGY_REPORT_DELETE_FORBIDDEN';
    END IF;
    IF TG_OP = 'INSERT' THEN
        SELECT * INTO report_row FROM geo_reports WHERE id = NEW.report_id;
        IF NOT FOUND OR NEW.user_id <> report_row.user_id
           OR NEW.subject_id <> report_row.subject_id
           OR NEW.subject_version_id <> report_row.subject_version_id
           OR NEW.status <> 'queued' OR NEW.attempts <> 0
           OR NEW.ai_body <> '{}'::jsonb OR NEW.usage_summary <> '{}'::jsonb
           OR NEW.safe_error_code <> '' OR NEW.started_at IS NOT NULL
           OR NEW.generated_at IS NOT NULL OR NEW.finished_at IS NOT NULL THEN
            RAISE EXCEPTION 'STRATEGY_REPORT_INITIAL_STATE_INVALID';
        END IF;
        IF NEW.billing_mode = 'free_initial' THEN
            IF EXISTS (
                SELECT 1 FROM strategy_reports
                 WHERE report_id = NEW.report_id AND status = 'succeeded'
            ) THEN
                RAISE EXCEPTION 'STRATEGY_FIRST_FREE_ALREADY_USED';
            END IF;
        ELSE
            IF NOT EXISTS (
                SELECT 1 FROM strategy_reports
                 WHERE report_id = NEW.report_id AND status = 'succeeded'
            ) THEN
                RAISE EXCEPTION 'STRATEGY_REGENERATION_REQUIRES_SUCCESS';
            END IF;
            SELECT * INTO hold_row FROM quota_hold_groups WHERE id = NEW.quota_hold_id;
            IF NOT FOUND OR hold_row.user_id <> NEW.user_id
               OR hold_row.quota_type <> 'strategy_regenerations'
               OR hold_row.business_type <> 'strategy_generation'
               OR hold_row.business_id <> NEW.id OR hold_row.requested_amount <> 1
               OR hold_row.status <> 'open' OR NOT EXISTS (
                    SELECT 1 FROM quota_holds h
                    JOIN quota_accounts a ON a.id = h.account_id
                     WHERE h.group_id = hold_row.id
                       AND h.subscription_id = NEW.subscription_id
                       AND a.subject_id = NEW.subject_id
               ) THEN
                RAISE EXCEPTION 'STRATEGY_QUOTA_HOLD_INVALID';
            END IF;
        END IF;
        RETURN NEW;
    END IF;
    IF ROW(
        NEW.report_id, NEW.user_id, NEW.subject_id, NEW.subject_version_id,
        NEW.subscription_id, NEW.quota_hold_id, NEW.period, NEW.period_days,
        NEW.billing_mode, NEW.report_facts, NEW.provider_key, NEW.model_key,
        NEW.provider_model_id, NEW.adapter_version, NEW.prompt_version,
        NEW.schema_version, NEW.input_digest, NEW.idempotency_key_digest,
        NEW.request_digest, NEW.request_id, NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.report_id, OLD.user_id, OLD.subject_id, OLD.subject_version_id,
        OLD.subscription_id, OLD.quota_hold_id, OLD.period, OLD.period_days,
        OLD.billing_mode, OLD.report_facts, OLD.provider_key, OLD.model_key,
        OLD.provider_model_id, OLD.adapter_version, OLD.prompt_version,
        OLD.schema_version, OLD.input_digest, OLD.idempotency_key_digest,
        OLD.request_digest, OLD.request_id, OLD.created_at
    ) THEN
        RAISE EXCEPTION 'STRATEGY_REPORT_BINDINGS_IMMUTABLE';
    END IF;
    IF OLD.status IN ('succeeded', 'failed') THEN
        RAISE EXCEPTION 'STRATEGY_REPORT_TERMINAL';
    END IF;
    IF OLD.status = 'queued' AND NEW.status = 'running' THEN
        IF NEW.attempts <> OLD.attempts + 1 OR NEW.generation = OLD.generation
           OR NEW.started_at IS NULL OR NEW.finished_at IS NOT NULL
           OR NEW.generated_at IS NOT NULL OR NEW.ai_body <> OLD.ai_body
           OR NEW.usage_summary <> OLD.usage_summary OR NEW.safe_error_code <> '' THEN
            RAISE EXCEPTION 'STRATEGY_REPORT_TRANSITION_INVALID';
        END IF;
    ELSIF OLD.status = 'queued' AND NEW.status = 'failed' THEN
        IF NEW.attempts <> OLD.attempts OR NEW.generation <> OLD.generation
           OR NEW.started_at IS DISTINCT FROM OLD.started_at
           OR NEW.generated_at IS NOT NULL OR NEW.finished_at IS NULL
           OR NEW.ai_body <> OLD.ai_body OR NEW.usage_summary <> OLD.usage_summary
           OR NEW.safe_error_code = '' THEN
            RAISE EXCEPTION 'STRATEGY_REPORT_TRANSITION_INVALID';
        END IF;
    ELSIF OLD.status = 'running' AND NEW.status = 'succeeded' THEN
        IF NEW.attempts <> OLD.attempts OR NEW.generation <> OLD.generation
           OR NEW.started_at IS DISTINCT FROM OLD.started_at
           OR NEW.generated_at IS NULL OR NEW.finished_at IS NULL
           OR NEW.ai_body = '{}'::jsonb OR OLD.ai_body <> '{}'::jsonb
           OR NEW.usage_summary = '{}'::jsonb OR NEW.safe_error_code <> '' THEN
            RAISE EXCEPTION 'STRATEGY_REPORT_TRANSITION_INVALID';
        END IF;
    ELSIF OLD.status = 'running' AND NEW.status = 'failed' THEN
        IF NEW.attempts <> OLD.attempts OR NEW.generation <> OLD.generation
           OR NEW.started_at IS DISTINCT FROM OLD.started_at
           OR NEW.generated_at IS NOT NULL OR NEW.finished_at IS NULL
           OR NEW.ai_body <> OLD.ai_body OR NEW.usage_summary <> OLD.usage_summary
           OR NEW.safe_error_code = '' THEN
            RAISE EXCEPTION 'STRATEGY_REPORT_TRANSITION_INVALID';
        END IF;
    ELSE
        RAISE EXCEPTION 'STRATEGY_REPORT_TRANSITION_INVALID';
    END IF;
    IF NEW.status IN ('succeeded', 'failed') AND NEW.billing_mode = 'regeneration' THEN
        SELECT * INTO hold_row FROM quota_hold_groups WHERE id = NEW.quota_hold_id;
        IF NOT FOUND OR hold_row.status <> 'settled'
           OR (NEW.status = 'succeeded'
               AND (hold_row.consumed_amount <> 1 OR hold_row.released_amount <> 0))
           OR (NEW.status = 'failed'
               AND (hold_row.consumed_amount <> 0 OR hold_row.released_amount <> 1)) THEN
            RAISE EXCEPTION 'STRATEGY_QUOTA_SETTLEMENT_INVALID';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION geo_guard_assistant_usage_event() RETURNS trigger AS $$
DECLARE subject_row subjects%%ROWTYPE; hold_row quota_hold_groups%%ROWTYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'ASSISTANT_USAGE_DELETE_FORBIDDEN';
    END IF;
    IF TG_OP = 'INSERT' THEN
        SELECT * INTO subject_row FROM subjects WHERE id = NEW.subject_id;
        IF NOT FOUND OR subject_row.user_id <> NEW.user_id
           OR subject_row.current_version_id <> NEW.subject_version_id
           OR NEW.provider_key <> 'deepseek' OR NEW.model_key <> 'deepseek'
           OR NEW.status NOT IN ('pending', 'refused')
           OR NEW.usage_summary <> '{}'::jsonb THEN
            RAISE EXCEPTION 'ASSISTANT_USAGE_INITIAL_STATE_INVALID';
        END IF;
        IF NEW.status = 'refused' THEN
            IF NEW.quota_hold_id IS NOT NULL OR NEW.safe_error_code = ''
               OR NEW.finished_at IS NULL THEN
                RAISE EXCEPTION 'ASSISTANT_REFUSAL_STATE_INVALID';
            END IF;
        ELSE
            SELECT * INTO hold_row FROM quota_hold_groups WHERE id = NEW.quota_hold_id;
            IF NOT FOUND OR hold_row.user_id <> NEW.user_id
               OR hold_row.quota_type <> 'assistant_messages'
               OR hold_row.business_type <> 'assistant_response'
               OR hold_row.business_id <> NEW.id OR hold_row.requested_amount <> 1
               OR hold_row.status <> 'open' OR NEW.safe_error_code <> ''
               OR NEW.finished_at IS NOT NULL OR NOT EXISTS (
                    SELECT 1 FROM quota_holds h
                    JOIN quota_accounts a ON a.id = h.account_id
                     WHERE h.group_id = hold_row.id
                       AND h.subscription_id = NEW.subscription_id
                       AND a.subject_id IS NULL
               ) THEN
                RAISE EXCEPTION 'ASSISTANT_QUOTA_HOLD_INVALID';
            END IF;
        END IF;
        RETURN NEW;
    END IF;
    IF ROW(
        NEW.user_id, NEW.subject_id, NEW.subject_version_id, NEW.subscription_id,
        NEW.quota_hold_id, NEW.provider_key, NEW.model_key, NEW.provider_model_id,
        NEW.adapter_version, NEW.prompt_version, NEW.schema_version,
        NEW.context_digest, NEW.idempotency_key_digest, NEW.request_digest,
        NEW.request_id, NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.user_id, OLD.subject_id, OLD.subject_version_id, OLD.subscription_id,
        OLD.quota_hold_id, OLD.provider_key, OLD.model_key, OLD.provider_model_id,
        OLD.adapter_version, OLD.prompt_version, OLD.schema_version,
        OLD.context_digest, OLD.idempotency_key_digest, OLD.request_digest,
        OLD.request_id, OLD.created_at
    ) THEN
        RAISE EXCEPTION 'ASSISTANT_USAGE_BINDINGS_IMMUTABLE';
    END IF;
    IF OLD.status <> 'pending' OR NEW.status NOT IN ('succeeded', 'failed')
       OR NEW.finished_at IS NULL THEN
        RAISE EXCEPTION 'ASSISTANT_USAGE_TRANSITION_INVALID';
    END IF;
    SELECT * INTO hold_row FROM quota_hold_groups WHERE id = NEW.quota_hold_id;
    IF NOT FOUND OR hold_row.status <> 'settled'
       OR (NEW.status = 'succeeded'
           AND (hold_row.consumed_amount <> 1 OR hold_row.released_amount <> 0
                OR NEW.safe_error_code <> '' OR NEW.usage_summary = '{}'::jsonb))
       OR (NEW.status = 'failed'
           AND (hold_row.consumed_amount <> 0 OR hold_row.released_amount <> 1
                OR NEW.safe_error_code = '' OR NEW.usage_summary <> OLD.usage_summary)) THEN
        RAISE EXCEPTION 'ASSISTANT_QUOTA_SETTLEMENT_INVALID';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS strategy_reports_guard ON strategy_reports;
CREATE TRIGGER strategy_reports_guard
BEFORE INSERT OR UPDATE OR DELETE ON strategy_reports
FOR EACH ROW EXECUTE FUNCTION geo_guard_strategy_report();

DROP TRIGGER IF EXISTS assistant_usage_events_guard ON assistant_usage_events;
CREATE TRIGGER assistant_usage_events_guard
BEFORE INSERT OR UPDATE OR DELETE ON assistant_usage_events
FOR EACH ROW EXECUTE FUNCTION geo_guard_assistant_usage_event();
"""

REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS assistant_usage_events_guard ON assistant_usage_events;
DROP TRIGGER IF EXISTS strategy_reports_guard ON strategy_reports;
DROP FUNCTION IF EXISTS geo_guard_assistant_usage_event();
DROP FUNCTION IF EXISTS geo_guard_strategy_report();
"""


def install_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FORWARD_SQL)


def remove_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0008_detection_retest"),
        ("plans", "0013_lifecycle_postgresql_guards"),
        ("quotas", "0012_subject_cycle_postgresql_guards"),
        ("subjects", "0013_subject_enrichment_postgresql_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("7d", "7 days"),
                            ("30d", "30 days"),
                            ("90d", "90 days"),
                            ("custom", "Custom"),
                        ],
                        max_length=16,
                    ),
                ),
                ("period_days", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("free_initial", "First strategy for report"),
                            ("regeneration", "Regeneration"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ai_body", models.JSONField(default=dict)),
                ("report_facts", models.JSONField()),
                ("provider_key", models.CharField(max_length=100)),
                ("model_key", models.CharField(max_length=100)),
                ("provider_model_id", models.CharField(max_length=255)),
                ("adapter_version", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=100)),
                ("schema_version", models.CharField(max_length=100)),
                ("input_digest", models.CharField(max_length=64)),
                ("idempotency_key_digest", models.CharField(max_length=64, unique=True)),
                ("request_digest", models.CharField(max_length=64)),
                ("request_id", models.UUIDField()),
                ("generation", models.UUIDField(default=uuid.uuid4)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("safe_error_code", models.CharField(blank=True, default="", max_length=100)),
                ("usage_summary", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quota_hold",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_report",
                        to="quotas.quotaholdgroup",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategies",
                        to="geo.georeport",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_reports",
                        to="subjects.subject",
                    ),
                ),
                (
                    "subject_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_reports",
                        to="subjects.subjectversion",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_reports",
                        to="plans.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="strategy_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "strategy_reports",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="StrategyNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note",
                        to="geo.strategyreport",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_notes",
            },
        ),
        migrations.CreateModel(
            name="AssistantUsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refused", "Refused"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider_key", models.CharField(max_length=100)),
                ("model_key", models.CharField(max_length=100)),
                ("provider_model_id", models.CharField(max_length=255)),
                ("adapter_version", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=100)),
                ("schema_version", models.CharField(max_length=100)),
                ("context_digest", models.CharField(max_length=64)),
                ("idempotency_key_digest", models.CharField(max_length=64, unique=True)),
                ("request_digest", models.CharField(max_length=64)),
                ("request_id", models.UUIDField()),
                ("safe_error_code", models.CharField(blank=True, default="", max_length=100)),
                ("usage_summary", models.JSONField(default=dict)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quota_hold",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_usage_event",
                        to="quotas.quotaholdgroup",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_usage_events",
                        to="subjects.subject",
                    ),
                ),
                (
                    "subject_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_usage_events",
                        to="subjects.subjectversion",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_usage_events",
                        to="plans.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assistant_usage_events",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["user", "subject", "created_at"], name="assistant_usage_scope_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ("pending", "succeeded", "failed", "refused"))
                        ),
                        name="assistant_usage_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("quota_hold__isnull", True), ("status", "refused")),
                            models.Q(
                                models.Q(("status", "refused"), _negated=True),
                                ("quota_hold__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="assistant_usage_hold_valid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="strategyreport",
            index=models.Index(
                fields=["user", "report", "created_at"], name="strategy_user_report_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategyreport",
            index=models.Index(fields=["status", "created_at"], name="strategy_status_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="strategyreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("queued", "running"))),
                fields=("report",),
                name="strategy_one_active_per_report",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategyreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("period__in", ("7d", "30d", "90d", "custom"))),
                name="strategy_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategyreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_days__gte", 1), ("period_days__lte", 365)),
                name="strategy_period_days_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategyreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("queued", "running", "succeeded", "failed"))),
                name="strategy_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategyreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("billing_mode", "free_initial"), ("quota_hold__isnull", True)),
                    models.Q(("billing_mode", "regeneration"), ("quota_hold__isnull", False)),
                    _connector="OR",
                ),
                name="strategy_billing_hold_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategynote",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="strategy_note_version_gte_1"
            ),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
