# Generated by Django 5.2.17 on 2026-08-21 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_parse_state_pointer_consistency'),
        ('geo', '0009_strategyreport_strategynote_assistantusageevent_and_more'),
        ('subjects', '0013_subject_enrichment_postgresql_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('report_snapshot', models.JSONField()),
                ('report_snapshot_digest', models.CharField(max_length=64)),
                ('brand_snapshot', models.JSONField()),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveBigIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='geo.georeport')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_shares', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_shares',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReportShareAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_digest', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('result', models.CharField(max_length=32)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='geo.reportshare')),
            ],
            options={
                'db_table': 'report_share_access_logs',
                'ordering': ('-accessed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubjectWhiteLabelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(default='#1677ff', max_length=7)),
                ('header_text', models.CharField(blank=True, max_length=500)),
                ('footer_text', models.CharField(blank=True, max_length=500)),
                ('contact', models.CharField(blank=True, max_length=500)),
                ('statement', models.TextField(blank=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='white_label_covers', to='documents.documentversion')),
                ('logo_document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='white_label_logos', to='documents.documentversion')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='white_label_config', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject_white_label_configs',
            },
        ),
        migrations.AddIndex(
            model_name='reportshare',
            index=models.Index(fields=['user', 'report', 'created_at'], name='report_share_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='reportshareaccesslog',
            index=models.Index(fields=['share', 'accessed_at'], name='share_access_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectwhitelabelconfig',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='white_label_version_gte_1'),
        ),
    ]
