# Generated by Django 5.2.17 on 2026-08-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_subject_competitor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assistantusageevent',
            name='assistant_usage_hold_valid',
        ),
    ]
