export const DETECTION_POLL_INTERVAL_MS = 3000;
export const DETECTION_RUNNING_POLL_INTERVAL_MS = 2000;
export const DETECTION_REQUEST_TIMEOUT_MS = 9000;
export const DETECTION_QUEUED_MODELS_POLL_INTERVAL_MS = 15000;
export const DETECTION_STALE_QUEUE_MS = 60000;
export const DETECTION_QUESTION_PAGE_SIZE = 20;
export const DETECTION_RESULT_PAGE_SIZE = 20;
