from django.urls import path

from .enrichment_views import (
    SubjectEnrichmentConfirmView,
    SubjectEnrichmentCreateView,
    SubjectEnrichmentDetailView,
    SubjectEnrichmentSourcesView,
)
from .risk_views import (
    AdminRiskCatalogPublishView,
    AdminRiskCatalogView,
    AdminRiskRuleDetailView,
    AdminRiskRuleListView,
    AdminRiskTypeDetailView,
    AdminRiskTypeListView,
    AdminSubjectReviewApproveView,
    AdminSubjectReviewDetailView,
    AdminSubjectReviewListView,
    AdminSubjectReviewRejectView,
)
from .subject_views import (
    SubjectActivateView,
    SubjectArchiveView,
    SubjectCommitView,
    SubjectCurrentView,
    SubjectDetailView,
    SubjectDraftView,
    SubjectListCreateView,
    SubjectVersionDetailView,
    SubjectVersionListView,
)
from .views import (
    AdminSubjectFieldOptionDetailView,
    AdminSubjectFieldOptionListView,
    AdminSubjectTypeDetailView,
    AdminSubjectTypeDisableView,
    AdminSubjectTypeEnableView,
    AdminSubjectTypeFieldDetailView,
    AdminSubjectTypeFieldListView,
    AdminSubjectTypeFieldOrderView,
    AdminSubjectTypeListView,
    PublicSubjectFormSchemaView,
    PublicSubjectTypeListView,
)

urlpatterns = [
    path("subject-types", PublicSubjectTypeListView.as_view(), name="subject-type-list"),
    path("subjects", SubjectListCreateView.as_view(), name="subject-list-create"),
    path("subjects/current", SubjectCurrentView.as_view(), name="subject-current"),
    path(
        "subjects/<uuid:subject_id>",
        SubjectDetailView.as_view(),
        name="subject-detail",
    ),
    path(
        "subjects/<uuid:subject_id>/ai-enrichment/sources",
        SubjectEnrichmentSourcesView.as_view(),
        name="subject-enrichment-sources",
    ),
    path(
        "subjects/<uuid:subject_id>/ai-enrichment",
        SubjectEnrichmentCreateView.as_view(),
        name="subject-enrichment-create",
    ),
    path(
        "subjects/<uuid:subject_id>/ai-enrichment/<uuid:job_id>",
        SubjectEnrichmentDetailView.as_view(),
        name="subject-enrichment-detail",
    ),
    path(
        "subjects/<uuid:subject_id>/ai-enrichment/<uuid:job_id>/confirm",
        SubjectEnrichmentConfirmView.as_view(),
        name="subject-enrichment-confirm",
    ),
    path(
        "subjects/<uuid:subject_id>/draft",
        SubjectDraftView.as_view(),
        name="subject-draft",
    ),
    path(
        "subjects/<uuid:subject_id>/commit",
        SubjectCommitView.as_view(),
        name="subject-commit",
    ),
    path(
        "subjects/<uuid:subject_id>/versions",
        SubjectVersionListView.as_view(),
        name="subject-version-list",
    ),
    path(
        "subjects/<uuid:subject_id>/versions/<uuid:version_id>",
        SubjectVersionDetailView.as_view(),
        name="subject-version-detail",
    ),
    path(
        "subjects/<uuid:subject_id>/activate",
        SubjectActivateView.as_view(),
        name="subject-activate",
    ),
    path(
        "subjects/<uuid:subject_id>/archive",
        SubjectArchiveView.as_view(),
        name="subject-archive",
    ),
    path(
        "subject-types/<uuid:subject_type_id>/form-schema",
        PublicSubjectFormSchemaView.as_view(),
        name="subject-form-schema",
    ),
    path("admin/subject-types", AdminSubjectTypeListView.as_view(), name="admin-subject-types"),
    path(
        "admin/subject-types/<uuid:subject_type_id>",
        AdminSubjectTypeDetailView.as_view(),
        name="admin-subject-type-detail",
    ),
    path(
        "admin/subject-types/<uuid:subject_type_id>/enable",
        AdminSubjectTypeEnableView.as_view(),
        name="admin-subject-type-enable",
    ),
    path(
        "admin/subject-types/<uuid:subject_type_id>/disable",
        AdminSubjectTypeDisableView.as_view(),
        name="admin-subject-type-disable",
    ),
    path(
        "admin/subject-types/<uuid:subject_type_id>/fields",
        AdminSubjectTypeFieldListView.as_view(),
        name="admin-subject-type-fields",
    ),
    path(
        "admin/subject-types/<uuid:subject_type_id>/field-order",
        AdminSubjectTypeFieldOrderView.as_view(),
        name="admin-subject-type-field-order",
    ),
    path(
        "admin/subject-type-fields/<uuid:config_id>",
        AdminSubjectTypeFieldDetailView.as_view(),
        name="admin-subject-type-field-detail",
    ),
    path(
        "admin/subject-type-fields/<uuid:config_id>/options",
        AdminSubjectFieldOptionListView.as_view(),
        name="admin-subject-field-options",
    ),
    path(
        "admin/subject-field-options/<uuid:option_id>",
        AdminSubjectFieldOptionDetailView.as_view(),
        name="admin-subject-field-option-detail",
    ),
    path(
        "admin/subject-risk-types",
        AdminRiskTypeListView.as_view(),
        name="admin-subject-risk-types",
    ),
    path(
        "admin/subject-risk-types/<uuid:risk_type_id>",
        AdminRiskTypeDetailView.as_view(),
        name="admin-subject-risk-type-detail",
    ),
    path(
        "admin/subject-risk-rules",
        AdminRiskRuleListView.as_view(),
        name="admin-subject-risk-rules",
    ),
    path(
        "admin/subject-risk-rules/<uuid:risk_rule_id>",
        AdminRiskRuleDetailView.as_view(),
        name="admin-subject-risk-rule-detail",
    ),
    path(
        "admin/subject-risk-catalog",
        AdminRiskCatalogView.as_view(),
        name="admin-subject-risk-catalog",
    ),
    path(
        "admin/subject-risk-catalog/publish",
        AdminRiskCatalogPublishView.as_view(),
        name="admin-subject-risk-catalog-publish",
    ),
    path(
        "admin/subject-reviews",
        AdminSubjectReviewListView.as_view(),
        name="subject-review-list",
    ),
    path(
        "admin/subject-reviews/<uuid:review_id>",
        AdminSubjectReviewDetailView.as_view(),
        name="subject-review-detail",
    ),
    path(
        "admin/subject-reviews/<uuid:review_id>/approve",
        AdminSubjectReviewApproveView.as_view(),
        name="subject-review-approve",
    ),
    path(
        "admin/subject-reviews/<uuid:review_id>/reject",
        AdminSubjectReviewRejectView.as_view(),
        name="subject-review-reject",
    ),
]
